- ibmcloud/README.md
- Add a new section to the ibmcloud documentation of how to clean up
the resources created in the demo
Fixes: #13
> ibmcloud | doc: Add clean up documentation

- ibmcloud/README.md
- ibmcloud/terraform/cos/main.tf
- ibmcloud/terraform/cos/output.tf
- ibmcloud/terraform/cos/provider.tf
- ibmcloud/terraform/cos/variables.tf
- ibmcloud/terraform/cos/versions.tf
Work completed to automate COS creation to store image from Build a 
pod VM image section of terraform/README.md. 
The main.tf file creates the instances. 
This automation allows the user to run a Terraform apply command
to create all the storage required to store an image.
Fixes: #17
> Terraform cos automation

- ibmcloud/README.md
- ibmcloud/terraform/cluster/main.tf
- ibmcloud/terraform/cluster/variables.tf
Have switched the cluster Terraform template to use the [ibm_is_ssh_key resource](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_ssh_key) over the old data source definition. This reduces the manual effort on the part of the developer.
Fixes: #24 
Signed-off-by: jtumber-ibm <james.tumber@ibm.com>
> Add creation of the IS SSH key to the cluster Terraform template

- cmd/parse.go
- pkg/adaptor/hypervisor/aws/server.go
- pkg/adaptor/hypervisor/aws/service.go
- pkg/adaptor/hypervisor/ibmcloud/service.go
- pkg/adaptor/hypervisor/libvirt/libvirt.go
- pkg/adaptor/hypervisor/libvirt/service.go
- pkg/adaptor/hypervisor/registry/aws.go
- pkg/adaptor/hypervisor/registry/ibmcloud.go
- pkg/adaptor/hypervisor/registry/libvirt.go
- pkg/adaptor/hypervisor/registry/register.go
- pkg/adaptor/hypervisor/types.go
Removed all the format warnings pointed out by gofmt tool so that `make
CLOUD_PROVIDER=ibmcloud fmt` show no errors.
> Fix gofmt errors

- pkg/adaptor/hypervisor/aws/service.go
The `addr` was already checked for `nil`, it is the result of
`net.ParseIP()` (i.e. `ip`) that should be checked too.
> aws: fix checking of pointer in service.go#getIPs()

- ibmcloud/terraform/cluster/ansible/kata-playbook.yml
- ibmcloud/terraform/cluster/ansible/kube-playbook.yml
- ibmcloud/terraform/cluster/main.tf
automation: split cluster playbook into two
Completed work to split cluster/ansible playbook into
initial cluster setup and peer pod enablement.
I split dependencies up after flagging them as kube or
kata related, or both.
Runbooks execute consecutively so no changes to README.
Fixes #22
Signed-off-by: [Jonah-Farrow] <jonah.farrow@ibm.com>
> Ability to run peer pod enablement on an existing cluster

- ibmcloud/demo/runtime-class.yaml
deprecated node.k8s.io/v1beta1 to avoid warning message when creating
the RuntimeClass
Fixes #31
Signed-off-by: Dave Hay <david_hay@uk.ibm.com>
> Updating runtime-class.yaml to use node.k8s.io/v1 API rather than the

- .github/workflows/commit-message-check.yaml
- Add in the commit message check based on the
https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/commit-message-check.yaml
given that we have matching commit guidance
Fixes: #45
> github: Add commit message check

- ibmcloud/demo/nginx.yaml
- ibmcloud/terraform/run-nginx-demo/ansible/apply_playbook.yml
- add a new secret with simple username and password
- use the secret as volume in nignx demo
- add verify configmap and secret volume steps in run-nginx-demo terraform
Fixes: #50
Signed-off by: Da Li Liu<liudali@cn.ibm.com>
> ibmcloud: configmap and secret volumes in nginx demo

- pkg/util/http/accesslog/accesslog_test.go
- pkg/util/http/upgrader/client.go
- pkg/util/http/upgrader/server_test.go
- pkg/util/http/upgrader/upgrader_test.go
- pkg/util/netops/netops.go
- pkg/util/netops/netops_test.go
Continuing with work start in #39, in this PR it is fixed all the errors pointed by `golangci-lint` in the util packages.
Fixes #32
> De-lint the util packages

- .github/workflows/build.yaml
- Makefile
- pkg/adaptor/hypervisor/ibmcloud/server_test.go
- pkg/adaptor/hypervisor/ibmcloud/shim_test.go
- pkg/internal/testing/testutils.go
- pkg/podnetwork/podnetwork_test.go
- pkg/podnetwork/tunneler/routing/iptables_test.go
- pkg/podnetwork/tunneler/routing/keepalive_test.go
- pkg/podnetwork/tunneler/routing/tunnel_test.go
- pkg/podnetwork/tuntest/tuntest.go
- pkg/util/netops/netops.go
- pkg/util/netops/netops_test.go
This adds a step on the build workflow in order to run the existing unit tests.
The tests for ibmcloud aren't compiling. I opened the issue #48 and disabled them all from CI.
The tests that need root privileges are refactored so that they use a common utility function for skipping. Even though running the CI pipeline as `sudo` some tests are failing to create network reosurces; those were also disabled from CI (see the issue #52).
I was working to get the test results nicely displayed on Github UI. I investigated the use of either https://github.com/marketplace/actions/junit-report-action or https://github.com/dorny/test-reporter but they both have limitations that didn't make me comfortable to enable them on the project. So for now they aren't used but I decided to keep the code that …
> github: run unit tests workflow

- .github/workflows/build.yaml
- pkg/adaptor/hypervisor/ibmcloud/server.go
- pkg/adaptor/hypervisor/ibmcloud/server_test.go
- pkg/adaptor/hypervisor/ibmcloud/shim_test.go
Fixes #48.
These unit tests are complicated due to historical reasons. This PR just fixes the build breaks. 
We will simply the unit tests by eliminating unnecessary tests in future PRs.
> Fix build breaks in unit tests

- ibmcloud/terraform/check-podvm-instance/version.tf
- ibmcloud/terraform/cluster/versions.tf
- ibmcloud/terraform/common/versions.tf
- ibmcloud/terraform/cos/versions.tf
- ibmcloud/terraform/podvm-build/versions.tf
- ibmcloud/terraform/run-nginx-demo/version.tf
- ibmcloud/terraform/start-cloud-api-adaptor/version.tf
- ibmcloud/terraform/version.tf
terraform modules updated:
Fixes: #76 and #60
Signed-Off-By: James Tumber <james.tumber@ibm.com>
> ibmcloud: provider version upgrade (1.43.0)

- go.sum
- ibmcloud/README.md
- ibmcloud/terraform/cluster/ansible/kata-playbook.yml
The latest [CCv0-peerpod branch](https://github.com/yoheiueda/kata-containers/tree/CCv0-peerpod) has the following code changes.
* `go.sum` is updated, since the upstream CCv0 branch has been rebased to the latest main branch.
* option name in `config.toml` is changed from remote_hypervisor to remote_hypervisor_socket based on a PR comment
https://github.com/kata-containers/kata-containers/pull/3697#discussion_r908641458
This PR includes necessary changes to synchronized with the latest CCv0-peerpod branch.
> Update to the latest CCv0-peerpod branch

- ibmcloud/terraform/run-nginx-demo/ansible/apply_playbook.yml
Update the wait logic in terraform template to check for the pod status
rather than be hard-coded to sleep for a certain amount of time
Fixes: #105
> ibmcloud: Update pod wait logic

- ibmcloud/image/.gitignore
- ibmcloud/image/Makefile
- ibmcloud/image/files/usr/bin/skopeo
skopeo is invoked from the kata-agent process, which runs as a systemd
service defined in /etc/systemd/system/kata-agent.service. This systemd
service launches kata-agent in a newly created network namespace called
"netns".  This network namespace is connected to Kubernetes pod network,
not host network of the pod VM. The skopeo command is used to pull
images from remote container registries, and requires network access
when pulling images. When network accesses to remote registries are
restricted by some mechanisms such as iptables, the skopeo command fails
to pull images, and kata-agent fails to create containers.
To work around this issue, this patch adds a wrapper script launches the
skopeo command in the the network namespace of the process with PID 1,
which is usually the systemd …
> ibmcloud: Run skopeo on host netns of pod VM

- go.sum
The latest CCv0-peerpod branch has been updated, and we need to update go.sum accordingly.
Fixes #114
> Update go.sum to synchronize the latest CCv0-peerpod branch 

- pkg/adaptor/hypervisor/aws/service.go
- pkg/adaptor/hypervisor/ibmcloud/service.go
- pkg/adaptor/hypervisor/libvirt/service.go
Fixes: #123
Signed-off by: Da Li Liu <liudali@cn.ibm.com>
> ibmcloud: remove internal sandbox data at the end of StopVM method

- .gitignore
- install/README.md
- install/pre-install-payload/Dockerfile
- install/pre-install-payload/Makefile
- install/pre-install-payload/config/remote-hyp.service
- install/pre-install-payload/hack/build.sh
- install/pre-install-payload/scripts/cloud-api-adaptor-deploy.sh
- install/pre-install-payload/scripts/post-uninstall.sh
- install/pre-install-payload/scripts/pre-install.sh
- install/pre-install-payload/scripts/run-hyp.sh
- install/runtime-payload/Dockerfile
- install/runtime-payload/Makefile
- install/runtime-payload/README.md
- install/runtime-payload/config/configuration-remote.toml
- install/runtime-payload/hack/binaries.sh
- install/runtime-payload/hack/build.sh
- install/runtime-payload/scripts/kata-deploy.sh
- install/runtime-payload/scripts/run-aws.sh
- install/runtime-payload/scripts/run-ibmcloud.sh
- install/runtime-payload/scripts/run-libvirt.sh
- install/yamls/ccruntime-peer-pods.yaml
- install/yamls/deploy.yaml
This is first iteration to install peer-pods stack via Operator.
The series includes the following
1. Deployment manifests 
2. Instructions to build the required images
3. README
Fixes: #121
> deploy: Installation via Operator

- ibmcloud/image/build.sh
Try to create the dir `/var/lib/kubelet` in peer pod VM in advance, so that it can be mounted to CSI driver node plugin running in peer pod.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/128
Signed-off-by: Lei Li [cdlleili@cn.ibm.com](mailto:cdlleili@cn.ibm.com)
> ibmcloud: create kubelet dir for CSI node plugin

- pkg/adaptor/hypervisor/libvirt/libvirt.go
The num field of vmConfig is used as the tail to generate a mac address;
however that field is never initialized. Previous versions of libvirt used
to let it by but newer versions complain of an empty mac address. Set tail
to sandbox.podNetworkConfig. Also, start mac addresses from 0.
Fixes: #117
> libvirt: fix mac address generation

- pkg/adaptor/hypervisor/aws/server.go
- pkg/adaptor/hypervisor/aws/types.go
- pkg/adaptor/hypervisor/aws/types_test.go
- pkg/adaptor/hypervisor/ibmcloud/server.go
- pkg/adaptor/hypervisor/ibmcloud/types.go
- pkg/adaptor/hypervisor/ibmcloud/types_test.go
- pkg/util/redacting.go
- Created tests to check approach works as designed
- Added utility function to redact provided fields
- Add redacting implementation for IBM cloud and AWS config type
Partial Fixes: #83 (Doesn't solve `ps -ef | grep cloud-api-adaptor` exposure)
Signed-Off-By: James Tumber <james.tumber@ibm.com>
> ibmcloud|aws: Mask cloud configuration sensitive fields

- ibmcloud/image/Makefile
- ibmcloud/image/build.sh
This PR adds the following code changes.
Run the `udpate-grub` command in `build.sh` to update GRUB configuration.
Fixes #143
We can build a pod VM image with a non-root user as follows.
```
make SUDO=sudo build
```
Add an option to change working directory to store temporary QCOW2 images.  We can speed up image builds by storing temporary images on tmpfs.
> ibmcloud: Run udpate-grub to update GRUB configuration

- cmd/agent-protocol-forwarder/main.go
- pkg/adaptor/hypervisor/ibmcloud/shim_test.go
- pkg/forwarder/forwarder.go
- pkg/forwarder/forwarder_test.go
- pkg/forwarder/interceptor/interceptor.go
- pkg/forwarder/interceptor/interceptor_test.go
This PR refactors  agent-protocol-forwarder to use `agentproto.Redirector` to create a proxy service, instead of just forwarding agent protocol connection.
https://github.com/confidential-containers/cloud-api-adaptor/issues/109#issuecomment-1205295195
The PR also fixes the confusing names in the related code as follows.
`pkg/forwarder/daemon.go` `daemon.Daemon` → `pkg/forwarder/forwarder.go` `forwarder.Daemon`
`pkg/forwarder/agent/agent.go agent.Forwarder` → `pkg/forwarder/interceptor/interceptor.go` `interceptor.Interceptor`
> Refactor agent-protocol-forwarder to use the agent protocol proxy service

- ibmcloud/image/verify.sh
- ibmcloud/terraform/podvm-build/ansible/playbook.yml
Allows skipping of console output during verify
Fixes: #89
Signed-off-by: Georgina Kinge <georgina.kinge@ibm.com>
> ibmcloud: add skip_verify_console variable

- pkg/adaptor/hypervisor/aws/service.go
- pkg/adaptor/hypervisor/aws/types.go
- pkg/adaptor/hypervisor/ibmcloud/service.go
IBM cloud and AWS implementations not redacting fields from service log. This series fixes the issue.
Fixes: #160
> Fix redaction of sensitive fields

- Dockerfile
- Makefile
- entrypoint.sh
- hack/build.sh
- install/README.md
- install/overlays/aws/cri_runtime_endpoint.yaml
- install/overlays/aws/kustomization.yaml
- install/overlays/libvirt/cri_runtime_endpoint.yaml
- install/overlays/libvirt/kustomization.yaml
- install/yamls/ccruntime-peer-pods-in-pod.yaml
Supports only libvirt and aws cloud providers
* set CLOUD_PROVIDER
```
export CLOUD_PROVIDER=<aws|ibmcloud|libvirt>
```
* `make image` builds the container image and push it to `$registry`
* `make deploy` deploys operator, runtime and cloud-api-adaptor pod in the configured cluster
* configure install/overlays/$(CLOUD_PROVIDER)/kustomization.yaml with your own settings
* validate kubectl is available in your `$PATH` and `$KUBECONFIG` is set
* `make delete` deletes the pod deployment from the configured cluster
Fixes: #5
**This was tested with aws (single noded) only**
As image was not pushed yet to repo to quickly deploy and test on an aws cluster:
1. Set your credentials on install/overlays/aws/kustomization.yaml (and newImage to: …
> deploy: run cloud-api-adaptor from within a pod

- ibmcloud/terraform/main.tf
- ibmcloud/terraform/podvm-build/main.tf
- ibmcloud/terraform/podvm-build/variables.tf
- ibmcloud/terraform/variables.tf
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/168
Set the skip_verify_console variable in the IBM Cloud
Terraform configurations.
Signed-off-by: Matthew Arnold <mattarno@uk.ibm.com>
> ibmcloud: Set skip_verify_console in Terraform configs

- ibmcloud/README.md
- ibmcloud/image/multipart_upload.sh
- ibmcloud/image/push.sh
- ibmcloud/terraform/cos/main.tf
- ibmcloud/terraform/cos/output.tf
- ibmcloud/terraform/cos/variables.tf
- ibmcloud/terraform/main.tf
- ibmcloud/terraform/podvm-build/ansible/playbook.yml
- ibmcloud/terraform/podvm-build/main.tf
- ibmcloud/terraform/podvm-build/variables.tf
- ibmcloud/terraform/variables.tf
- Allow the user to create and use a cross-region cos bucket
- Made uploads on slower networks more reliable by doing multipart uploads
Fixes #169 
Signed-Off-By: James Tumber <james.tumber@ibm.com>
> ibmcloud: Enable cross-region cos endpoints

- Dockerfile
as it's easy to miss dependencies during development
(such as ca certificates or protobuf)
Fixes: #182
> Dockerfile: use same image for building and executing

- install/README.md
- install/runtime-payload/scripts/kata-deploy.sh
- install/yamls/ccruntime-peer-pods-in-pod.yaml
- install/yamls/ccruntime-peer-pods.yaml
set its configuration files etc..
Fixes: #184
* io.kubernetes.cri.sandbox-name annotation doesn't propagate with crio, expected to be fixed in crio-1.24.3, meanwhile can be added manually
> install: enable installation when crio is used

- install/overlays/libvirt/ssh_mount.yaml
which is needed in order to mount the ssh key with libvirt
Fixes: #192
> install: add missing ssh_mount file

- aws/image/files/etc/systemd/system/agent-protocol-forwarder.service
- azure/image/files/etc/systemd/system/agent-protocol-forwarder.service
- ibmcloud/image/files/etc/systemd/system/agent-protocol-forwarder.service
- libvirt/image/files/etc/systemd/system/agent-protocol-forwarder.service
- pkg/forwarder/forwarder.go
- pkg/forwarder/forwarder_test.go
- pkg/forwarder/interceptor/interceptor.go
- pkg/util/agentproto/redirector.go
kata-agent of the latest CCv0 branch does not use abstract Unix domain socket, when we set KATA_AGENT_SERVER_ADDR as follows.
```
KATA_AGENT_SERVER_ADDR=unix:///run/kata-containers/agent.sock"
```
This patch changes agent-protocol-forwarder to connect to a regular Unix domain socket, instead of a abstract Unix domain socket.
This PR also improve error handling at connecting to kata-agent using Unix domain socket.
Fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/198
> Use normal Unix domain socket for kata-agent

- ibmcloud/README.md
- ibmcloud/terraform/.gitignore
- ibmcloud/terraform/cluster/ansible/kata-playbook.yml
- ibmcloud/terraform/cluster/ansible/kube-playbook.yml
- ibmcloud/terraform/cluster/main.tf
- ibmcloud/terraform/cluster/variables.tf
- ibmcloud/terraform/main.tf
- ibmcloud/terraform/variables.tf
This patch remove hard-coded source code repository URLs and branch names, and introduce variables to specify them. The default values are the original hard-coded ones.
Fixes #211
> ibmcloud: Use variables for source code repos

- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- Dockerfile
- README.md
- docs/DEVELOPMENT.md
- go.mod
- go.sum
- ibmcloud/README.md
- ibmcloud/terraform/cluster/variables.tf
- ibmcloud/terraform/variables.tf
The PR of remote hypervisor support has been merged.
We can switch from the `CCv0-peerpod` branch at https://github.com/yoheiueda/kata-containers to the `CCv0` branch at https://github.com/kata-containers/kata-containers.
Fixes #215
> Switch to upstream CCv0

- docs/DEVELOPMENT.md
- docs/addnewprovider.md
- install/README.md
The azure provider was missing in a couple of places in the documentation.
Fixes: #220 
> azure: add provider to documentation

- azure/README.md
- cmd/cloud-api-adaptor/main.go
- pkg/adaptor/hypervisor/azure/types.go
Tiny cleanup, there are a few properties and flags that are redundant/unused.
Fixes: #221
> azure: remove SubnetName and VnetName flags

- Dockerfile
to avoid old pkgs security risks
Fixes: #254
**It seems Debian (non-rawhide) based images has a lot of security risk warnings emits by quay's security scanner ([see](https://quay.io/repository/confidential-containers/cloud-api-adaptor-aws?tab=tags)), running in fedora container (build is still on debian) seem to solve all of them AFAIU that's should be safe for the static caa builds and i think it should be fine also for the libvirt build as the libs are installed.**
> caa-pod: run in fedora container

- pkg/adaptor/proxy/service.go
- pkg/forwarder/interceptor/interceptor.go
This PR fixes pull image errors when the custom containerd for CCv0 is used with the latest CCv0.
Fixes #259
> Fix pull image errors when the custom containerd for CCv0 is used with the latest CCv0

- pkg/adaptor/hypervisor/aws/service.go
- pkg/adaptor/hypervisor/azure/service.go
- pkg/adaptor/hypervisor/ibmcloud/service.go
- pkg/adaptor/hypervisor/libvirt/service.go
- pkg/adaptor/hypervisor/vsphere/service.go
- pkg/util/hvutil/hvutil.go
cri-o reports sandbox names in the different format than containerd.
This patch corrects pod names reported by cri-o so that they are consistent with containerd.
Fixes #261
> Correct pod names reported by cri-o

- aws/image/Makefile
- azure/image/Makefile
- ibmcloud/image/Makefile
- libvirt/image/Makefile
These patch remove the skopeo and umoci commands from the pod VM image for the following cloud providers.
* ibmcloud
* aws
* libvirt
* azure
We can still install skopeo and umoci commands by setting the optional variable USE_SKOPEO.
> Remove the skopeo and umoci  from the pod VM image

- pkg/adaptor/hypervisor/aws/service.go
- pkg/adaptor/hypervisor/azure/service.go
- pkg/adaptor/hypervisor/ibmcloud/service.go
- pkg/adaptor/hypervisor/libvirt/service.go
- pkg/adaptor/hypervisor/vsphere/service.go
- pkg/util/hvutil/hvutil.go
- pkg/util/hvutil/hvutil_test.go
This PR sanitizes input string values, and then generates a VM name.
This function generates a VM instance name from sanitized values of node name, pod namespace, pod name, and sandbox ID.
Fixes #265
> Sanitize strings when generating VM name

- entrypoint.sh
- install/overlays/ibmcloud/kustomization.yaml
Align ibmcloud cri-endpoint handling with other providers to avoid duplication in optionals.
Fixes: #279
> ibmcloud: cri-endpoint as optional

- pkg/adaptor/hypervisor/azure/service.go
Fixes: #275
There might be a state in which the creation of a VM has been triggered but the respective api call hasn't returned yet. If a create-vm call is then cancelled at the call site due to a timeout, the VM resources will not be garbage collected, because the sandbox's vm name has not been populated yet.
> azure: populate sandbox vm name earlier

- pkg/adaptor/hypervisor/azure/server.go
- pkg/adaptor/hypervisor/azure/types.go
- pkg/adaptor/hypervisor/azure/types_test.go
Use redacted config in log output like in ibmcloud, aws adaptors
Partially Fixes #83
> azure: mask sensitive fields in cloud config

- cmd/cloud-api-adaptor/main.go
Adds `os.Getenv` option to each sensitive field.
Fixes: #83
> cmd: Take sensitive defaults from environment variables

- aws/image/Makefile
- azure/image/Makefile
Final image that is built should have a generic name instead of
something random like uuid.
Fixes: #300
> Use unused IMAGE_NAME for image

- .github/workflows/image.yaml
When the code is pushed to the staging branch, we need container images for different cloud providers to be built automatically.
Fixes: #205
> Actions: Add jobs for building caa images

- ibmcloud/terraform/cluster/ansible/kata-playbook.yml
Increase timeout to 10mins from default 1min to help not error when pulling bigger images
Fixes: #334
> ibmcloud: Increase remote hypervisor timeout

- entrypoint.sh
- install/overlays/azure/kustomization.yaml
Fixes: #340
The latter is the proper env name and it's also used in code.
> Rename AZURE_SECRET to AZURE_CLIENT_SECRET

- install/overlays/aws/cri_runtime_endpoint.yaml
- install/overlays/azure/cri_runtime_endpoint.yaml
- install/overlays/azure/kustomization.yaml
- install/overlays/ibmcloud/cri_runtime_endpoint.yaml
- install/overlays/ibmcloud/kustomization.yaml
- install/overlays/libvirt/cri_runtime_endpoint.yaml
- install/overlays/vsphere/cri_runtime_endpoint.yaml
Setting CRI_RUNTIME_ENDPOINT defines only the in-container side socket path, the pre-defined default fixed address should work for both containerd and crio.
Fixes: #333
> all: remove redundant cri runtime endpoint configuration

- .github/workflows/webhook.yaml
- webhook/Makefile
- webhook/docs/DEVELOPMENT.md
- webhook/tests/e2e/run-local.sh
- webhook/tests/e2e/webhook_tests.bats
The webhook is a component that can be tested in isolation. You will only required a working Kubernetes cluster (which can be setup with Kind) and the tools to build the webhook itself. So this pull request contain an CI for the webhook which is triggered only and only if the webhook files changed.
The CI is built on a github action, runner script and bats tests. Developers will be able to run the same workflow locally by issuing `make test-e2e`.
Refer to the https://github.com/wainersm/cc-cloud-api-adaptor/actions/runs/3268928340 for a successful execution of the github action.
Note: there is a test case not passing which was marked to skip.
Fixes #291
> Add CI for the webhook

- .gitignore
- vsphere/README.md
- vsphere/image/Makefile
- vsphere/image/data/user-data.pkr.hcl
- vsphere/image/files/etc/agent-config.toml
- vsphere/image/files/etc/cloud/cloud.cfg.d/06_podvm.cfg
- vsphere/image/files/etc/containers/policy.json
- vsphere/image/files/etc/systemd/system/agent-protocol-forwarder.service
- vsphere/image/files/etc/systemd/system/kata-agent.service
- vsphere/image/files/etc/systemd/system/multi-user.target.wants/agent-protocol-forwarder.service
- vsphere/image/files/etc/systemd/system/multi-user.target.wants/kata-agent.service
- vsphere/image/files/etc/systemd/system/multi-user.target.wants/run-kata\x2dcontainers-shared-containers.mount
- vsphere/image/files/etc/systemd/system/multi-user.target.wants/run-kata\x2dcontainers.mount
- vsphere/image/files/etc/systemd/system/run-kata\x2dcontainers-shared-containers.mount
- vsphere/image/files/etc/systemd/system/run-kata\x2dcontainers.mount
- vsphere/image/scripts/createconfig.sh
- vsphere/image/variables.pkr.hcl
- vsphere/image/vsphere-ubuntu.pkr.hcl
v2: 
Added a few changes as pointed out in the reviews
- Added the option to configure disk size by the user 
- Cleaned up clutter in the Makefile and moved information gathering to a script
- Renamed data/user-data.pkrtpl.hcl to data/user-data.pkr.hcl
- Removed settings.auto.pkrvars.hcl, this will be created when building the template by the above script
- Added *auto*.hcl files to .gitignore
- Added a README
- Fix for #339 (included in a previous push)
Mostly, derived from its libvirt counterpart, this script creates an esx guest from a standard ubuntu iso and then converts it into a template.
Standard settings are in settings.auto.pkrvars.hcl. vsphere config is expected in vsphere.auto.pkrvals.hcl which will be created by the Makefile if not present; user-data.pkrtpl.hcl contains the …
> vsphere: use packer to create the podvm template

- azure/README.md
- entrypoint.sh
When using Calico CNI, it was unexpectedly dropping VXLAN packets unrelated to calico. To avoid manual route creation one has to configure VXLAN encapsulation on calico and a new VXLAN UDP port is used rather than the default one.
Fixes: #359
> azure: remove manual route creation

- ibmcloud/terraform/cluster/scripts/keygen.sh
When running on MacOS `ssh-copy-id` without the force (`-f`) flag fails to set up the SSH keys on the k8s worker and k8s control plane node correctly, resulting in this warning:
```
module.cluster.null_resource.ansible (local-exec): /usr/bin/ssh-copy-id: WARNING: All keys were skipped because they already exist on the remote system.
module.cluster.null_resource.ansible (local-exec): 		(if you think this is a mistake, you may want to use -f option)
module.cluster.null_resource.ansible (local-exec): # Host [localhost]:22022 found: line 2
module.cluster.null_resource.ansible (local-exec): /var/folders/tq/4s_zl3fx5xq4vf7ts_bd1q3w0000gn/T/tmp.AVcdIjrx/known_hosts updated.
module.cluster.null_resource.ansible (local-exec): Original contents retained as …
```
> Use ssh-copy-id -f if the OS is MacOS (Darwin)

- podvm/Makefile.inc
- podvm/copy-files.sh
- podvm/files/etc/agent-config.toml
- podvm/files/etc/containers/policy.json
- podvm/files/etc/systemd/system/agent-protocol-forwarder.service
- podvm/files/etc/systemd/system/kata-agent.service
- podvm/files/etc/systemd/system/multi-user.target.wants/agent-protocol-forwarder.service
- podvm/files/etc/systemd/system/multi-user.target.wants/kata-agent.service
- podvm/files/etc/systemd/system/multi-user.target.wants/run-image.mount
- podvm/files/etc/systemd/system/multi-user.target.wants/run-kata\x2dcontainers.mount
- podvm/files/etc/systemd/system/run-image.mount
- podvm/files/etc/systemd/system/run-kata\x2dcontainers.mount
- Adds Makefile which has the common code between providers
- Common files, copy-files.sh, services, etc
Each providers Makefile will be a child of their provider `aws/Makefile` vs `aws/image/Makefile`
Therefore I have updated the relative paths for this
Each provider can implement their own targets as there is variation (build, push, etc)
Fixes #314
> all: introduce common image directory

- pkg/podnetwork/tunneler/tunneler.go
- pkg/podnetwork/tunneler/vxlan/podnode.go
- pkg/podnetwork/tuntest/tuntest.go
- pkg/podnetwork/tuntest/util.go
- pkg/podnetwork/workernode.go
When using OVS (OpenvSwitch) based CNIs like openshift-sdn or ovn-kubernetes, POD IPs are unreachable from the cluster nodes (worker or controller).
There are two issues at play here
- OVS based CNIs uses flow rules specific to the mac address of pod. And the pod mac address is used from the CNI created namespace on the worker node. However the container process which runs in the Pod VM uses a different mac address and unless the flow rules are updated with the mac address from the Pod VM, Pod IP is not reachable from the cluster nodes
- Certain CNIs (eg ovn-kubernetes) disables ARP broadcast and uses the pod mac address assigned by the CNI. However it doesn't matches with the mac address used in Pod VM and hence packets are received by the Pod VM with incorrect dst address over the vxlan …
> podnetwork: Fix networking when using OVS

- libvirt/image/misc-settings.sh
- libvirt/image/qemu-ubuntu.pkr.hcl
Remove machine-id when creating base qcow2 image for Pod VM. This ensures that pod VMs created from the same image gets unique DHCP ips
Fixes: #363
> libvirt: Ensure pod VMs get unique DHCP ip

- vsphere/image/misc-settings.sh
- vsphere/image/vsphere-ubuntu.pkr.hcl
Remove machine-id when creating base qcow2 image for Pod VM. This ensures that pod VMs created from the same image gets unique DHCP ips.
Backported from the libvirt version for #376 
Fixes: #363
> vsphere: Ensure pod VMs get unique DHCP ip

- aws/image/files/etc/systemd/system/agent-protocol-forwarder.service
- azure/image/files/etc/systemd/system/agent-protocol-forwarder.service
- libvirt/image/files/etc/systemd/system/agent-protocol-forwarder.service
- podvm/files/etc/systemd/system/agent-protocol-forwarder.service
- vsphere/image/files/etc/systemd/system/agent-protocol-forwarder.service
RHEL 9 podvm image is encountering an issue where cloudconfig init hasn't completed before agent-protocol-forwarder starts and it fails because it can't find /peerpods/daemon.json. Restart the service on failure.
Fixes: #388
Suggested-by: Pradipta Banerjee <pradipta.banerjee@gmail.com>
> podvm: restart agent-protocol-forwarder on failure

- aws/README.md
- ibmcloud/README.md
- podvm/Makefile.inc
- podvm/files/etc/agent-config.toml
- Add attestation agent if AA_KBC has been set in the makefile
- Update ibmcloud docs to include steps for setting up the attestation agent with authenticated registry support
- Update AWS docs to remove the skopeo specific steps and replace it with using the attestation agent with authenticated registry support
> Add setup steps for the attestation agent to the podvm makefile

- podvm/files/etc/systemd/system/kata-agent.service
- podvm/files/usr/local/bin/kata-agent-clean
- Delete the ttrpc server socket when it stops
This helps handle podvm restarts, including during podvm image creation.
Fixes: #420
> podvm: Add cleanup helper

- vsphere/image/rhel/data/ks.pkr.hcl
- vsphere/image/rhel/scripts/createconfig.sh
- vsphere/image/rhel/variables.pkr.hcl
- vsphere/image/rhel/vsphere-rhel.pkr.hcl
RHEL8 kickstarts do not seem to recognize the isencrypted flag to user command. Use plaintext instead that works universally. While at it, also make username/password configurable.
Fixes: #429
> vsphere: template: workaround ks user bug

- peer-pod-controller/controllers/peerpodconfig_controller.go
Fix a simple type that led to the cloud-api-adaptor daemon set not being created.
error message:
"Failed setting ControllerReference for cloud-api-adaptor DS"
Fixes #426 
> controller: fix typo in environment variable for peerpods namespace

- vsphere/image/files/etc/systemd/system/kata-agent.service
Now that we are using legacy cgroups...
https://github.com/kata-containers/kata-containers/issues/4610
Fixes: #431
> vsphere: template: unmount misc cgroup as its not handled by kata

- ibmcloud/terraform/cluster/ansible/kata-playbook.yml
Instal version 1.19.3 of go in the Ansible playbook to match the kata-containers minimum version
Fixes: #440
> ibmcloud: Bump version of go

- peer-pod-controller/controllers/peerpodconfig_controller.go
This adds a volume and volumeMount to the cloud-api-adaptor pod definition. cloud-api-adaptor can then inject the auth.json file into the podvm and enable it to pull image from registries that require authentication.
Rename variable sshSecretOptional to be more generic and use it for all optional secrets
Fixes #443
> controller: add volume to mount auth.json

- ibmcloud/terraform/cluster/ansible/kata-playbook.yml
Add disable_guest_selinux = true to the kata configuration on the k8s worker.
With the change in https://github.com/confidential-containers/cloud-api-adaptor/pull/441 this makes setting up the nginx container demo environment using Terraform work again.
> Ibmcloud: fix guest selinux is enabled in k8s worker

- peer-pod-controller/api/v1alpha1/peerpodconfig_types.go
use kubebuilder annotations in the API definition. The annotations will be used to set the default names in the PeerPodConfig CRD when it is generated via make manifests.
Fixes #450 
> controller: set default values for name of config map and secret

- peer-pod-controller/controllers/peerpodconfig_controller.go
This fixes a typo in a function name as well as in the name that cloud-api-adaptor pods get. Change cca to caa.
Fixes: #452
> controller: fix typo cca vs caa

- peer-pod-controller/api/v1alpha1/peerpodconfig_types.go
- peer-pod-controller/controllers/peerpodconfig_controller.go
This adds an optional field to the PeerPodConfig spec section. It can be used to specify a label that matches the nodes where the cloud-api-adaptor daemonset is supposed to run.
Fixes: #456
> controller: add labelSelector to PeerPodConfig

- podvm/Makefile
as it doesn't match cloud-init configuration
Fixes: #471
> Makefile: remove fixed ssh user for rhel

- podvm/Dockerfile.podvm.rhel
- podvm/Dockerfile.podvm_builder.rhel
- podvm/qcow2/rhel/qemu-rhel.pkr.hcl
This has been tested with rhel 8.7 only 
Example:
This must be running on subscribed RHEL host
To build builder rhel container:
$ podman build -t podvm_builder_rhel -f Dockerfile.podvm_builder.rhel 
To build the podvm image:
$ RHEL_IMAGE_URL=<path/to/downloaded/image>
$ RHEL_IMAGE_CHECKSUM=<checksum>
$ podman build -t podvm_rhel_aws --build-arg BUILDER_IMG=localhost/podvm_builder_rhel:latest \
--build-arg CLOUD_PROVIDER=aws --build-arg RHEL_IMAGE_CHECKSUM=${RHEL_IMAGE_CHECKSUM} \
-v ${RHEL_IMAGE_URL}:/tmp/rhel.qcow2 -f Dockerfile.podvm.rhel 
Fixes: #472
Depends-on: confidential-containers/cloud-api-adaptor#473
NOTE: it should be possible to build without subscription, it will require to split  binaries build and packer build, which is a …
> podvm: build rhel image from in a container

- podvm/Dockerfile.podvm_builder.rhel
as it's required by kata-containers
Fixes: #481
Signed-off-by: Snir Sheriber ssheribe@redhat.com
> rhel: bump rust version to 1.66.0

- azure/image/Makefile
- ibmcloud/README.md
- podvm/Makefile.inc
- Update Makefiles to remove the skopeo and umoci targets that install them into the peer pod image.
- Note: The skopeo and umoci source targets are still needed to copy and unpack the pause image for now.
Fixes: #164
> image: Remove skopeo & umoci

- podvm/qcow2/rhel/qemu-rhel.pkr.hcl
to full path as it's not found in $PATH
Fixes: #472
> podvm: fix rhel's qemu binary path

- azure/go.mod
- podvm/go.mod
When cloud-api-adaptor is required by another Go project as a Go module, ignore the systemd/system directories as they contain a file run-kata\x2dcontainers.mount that breaks Go module imports.
Fixes #483
Signed-off-by: Matthew Arnold <mattarno@uk.ibm.com>
> build: exclude systemd/system dirs from CAA go module

- podvm/qcow2/centos/qemu-centos.pkr.hcl
- podvm/qcow2/rhel/qemu-rhel.pkr.hcl
This is useful if we are repurposing the qcow2 for a ovf.
Fixes: #502
> qcow2: template: attempt installing open-vm-tools for rhel and centos

- vsphere/vmdk-to-ovf.sh
This option overwrites an existing template by making sure to delete template files, if they exist, before the current run.
The default is yes - always assume a force install.
Fixes: #506
> vsphere: vmdk-to-ovf.sh: add a force option

- podvm/qcow2/centos/qemu-centos.pkr.hcl
- podvm/qcow2/centos/variables.pkr.hcl
- podvm/qcow2/misc-settings.sh
- podvm/qcow2/rhel/qemu-rhel.pkr.hcl
- podvm/qcow2/rhel/variables.pkr.hcl
- podvm/qcow2/ubuntu/qemu-ubuntu.pkr.hcl
- podvm/qcow2/ubuntu/variables.pkr.hcl
v2: 
* Remove the shell-local based hack entirely
* Assign environment vars CLOUD_PROVIDER and PODVM_DISTRO to packer user vars
* Use environment_vars in the shell provisioner referencing these variables
* Include logic in misc-settings.sh to install open-vm-tools
This script creates a target-script that is to executed on remote but is dependant on local variables. ATM, it is CLOUD_PROVIDER and is used to decide where we should install open-vm-tools but others can be easily added.
The way this works is:
1. Use the shell-local provisioner to create a script based on the value of CLOUD_PROVIDER. We use "generated = true" to make sure Packer does not complain about a failing stat.
2. Copy over as usual so that the shell provisioner can execute it.
3. To keep it simple, if nothing needs to be …
> qcow2: create an install script on the fly

- .github/workflows/podvm.yaml
- podvm/Dockerfile.podvm
- podvm/Makefile
- podvm/Makefile.inc
- podvm/hack/cross-build-extras.sh
- podvm/qcow2/ubuntu/qemu-ubuntu.pkr.hcl
- podvm/qcow2/ubuntu/variables.pkr.hcl
The `cd-rom` option for qemu doesn't work for s390x as it can't auto-detect the layout. Uses `virtio-scsi` instead works for both `s390x` and `amd64` for the cloud-init data. Addtionally to make sure it boots from the `qcow2` drive instead of the cloud-init, need to explictly define the device and drive.
Fixes: #512
> podvm/github-action: Support building public s390x qcow images 

- cmd/cloud-api-adaptor/main.go
When an invalid cloud provider is passed, it is currently not being handled by the adaptor. This PR adds a fix to display a message instead of failing silently.
Fixes: #523
Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>
> cmd: Display proper error message when invalid provider is passed

- podvm/Dockerfile.podvm
The ARCH argument to Dockerfile.podvm was introduced in commit 4df1c88d874d1 but it is not proper initialized so that if ARCH is not passed then the libseccomp build fails. This changed the dockerfile to ensure that ARCH is x86_64 by default.
Fixes #536
> podvm: initialize ARCH argument in Dockerfile.podvm

- podvm/qcow2/rhel/qemu-rhel.pkr.hcl
The relabeling in the provisioner is intended to fix labeling when packer copies over files to the image. It's run at the end during provisioning. However, misc-settings.sh may install packages and configure services to boot at startup. If the labels are not correct, this will fail.
Move labeling to right after we copy our target dir and run misc-settings in the end.
Fixes: #548
> podvm: rhel: relabel before running misc-settings.sh

- .github/workflows/image.yaml
- hack/build.sh
s390x build doesn't work for libvirt, additionally no other providers can run s390x so enabling it only for ibmcloud makes sense.
Test run: https://github.com/jtumber-ibm/cloud-api-adaptor/actions/runs/3960399170
Test results: 
libvirt https://hub.docker.com/r/jamesnelson/cloud-api-adaptor-libvirt/tags
ibmcloud https://hub.docker.com/r/jamesnelson/cloud-api-adaptor-ibmcloud/tags
I've moved `go_version` and `runs-on` out of the matrix to avoid duplicating them for the separate `ibmcloud` job, hope that is ok.
Fixes: #546
> github-action: Only build s390x image for ibmcloud

- libvirt/README.md
- libvirt/install_operator.sh
- libvirt/kcli_cluster.sh
In https://github.com/confidential-containers/cloud-api-adaptor/issues/16#issuecomment-1292524184 I drafted a framework that we could be using for running e2e tests on CI. To continue that work I want to create an implementation for libvirt because developers can run on their own workstation and this should allow others to test the framework.
But soon I realized the information to build an environment to develop for libvirt is spread in the repository or simply missing. Then I started fixing some stuffs and automating some steps. This pull request contain that work. Apart from using the changes I propose here on CI, I think it will be useful for developers setting up their environments for testing locally.
> libvirt: add e2e demo code and documentation

- entrypoint.sh
- install/overlays/azure/kustomization.yaml
In a setup where user has a VM different from the default setup then AZURE_VM_NAME won't work, as VNET, SUBNET, NSG name will be different.
Fixes: #551
> azure: update autogenerated AZURE_VM_NAME

- entrypoint.sh
- install/overlays/aws/cri_runtime_endpoint.yaml
- install/overlays/azure/cri_runtime_endpoint.yaml
- install/overlays/ibmcloud/cri_runtime_endpoint.yaml
- install/overlays/libvirt/cri_runtime_endpoint.yaml
- install/overlays/vsphere/cri_runtime_endpoint.yaml
The operator install for a kubernetes cluster using IBM Cloud VPC Infrastructure requires the following cri_runtime_endpoint.yaml to work.
Fixes: #530
Signed-off-by: Matthew Arnold <mattarno@uk.ibm.com>
> operator: fix cri runtime endpoint

- docs/consuming-prebuilt-podvm-images.md
- podvm/README.md
While working on https://github.com/confidential-containers/cloud-api-adaptor/pull/345 we realized the process to build podvm within container is not documented, can be confusing and demands memory/disk from the host. So the main goal of this PR is to document the process to build the podvm with or without containers.
And while working on the podvm/README.md  I realized that:
* we don't document how to consume the pre-built images either, so I add a new article in docs.
* we could have a script to ease the process to extract the qcow2 file from the container image, so I created a script. A few minutes about I noticed @jtumber-ibm  had the same idea (https://github.com/confidential-containers/cloud-api-adaptor/issues/563) and his script …
> Add documentation about podvm build process

- podvm/Dockerfile.podvm_builder.centos
- podvm/Dockerfile.podvm_builder.rhel
- podvm/Makefile
- podvm/qcow2/centos/qemu-centos.pkr.hcl
- podvm/qcow2/rhel/qemu-rhel.pkr.hcl
in the builder containers that installs qemu-kvm instead of setting qemu_binary in hcl files
Fixes: #566
> podvm: set qemu-system-* link to qemu-kvm

- install/pre-install-payload/Dockerfile
- install/pre-install-payload/Makefile
- install/pre-install-payload/hack/build.sh
Find test run resulting image [here](https://hub.docker.com/layers/jamesnelson/peer-pods-pre-install-payload/2023011914461674139575/images/sha256-0cab3c4d1823aab8d190ef5f1e201935619c9a2aef447ddc435e969e678de7f8?context=explore)
Switched from centos to ubuntu for base image. CentOS is out of support, but happy to discuss best alternative.
Fixes: #544
> operator: pre-install payload multiarch support

- ibmcloud/cluster/.gitignore
- ibmcloud/cluster/README.md
- ibmcloud/cluster/ansible/containerd.yaml
- ibmcloud/cluster/ansible/inventory.tmpl
- ibmcloud/cluster/ansible/tasks/binaries.yaml
- ibmcloud/cluster/ansible/tasks/bootstrap.yaml
- ibmcloud/cluster/ansible/tasks/k8s.yaml
- ibmcloud/cluster/kube-init.sh
- ibmcloud/cluster/main.tf
- ibmcloud/cluster/node/main.tf
- ibmcloud/cluster/node/outputs.tf
- ibmcloud/cluster/node/variables.tf
- ibmcloud/cluster/node/version.tf
- ibmcloud/cluster/provider.tf
- ibmcloud/cluster/variables.tf
- ibmcloud/cluster/version.tf
- ibmcloud/cluster/vpc/main.tf
- ibmcloud/cluster/vpc/outputs.tf
- ibmcloud/cluster/vpc/variables.tf
- ibmcloud/cluster/vpc/version.tf
To phase out the existing demo in favour of operator, we need
to split out the cluster creation from the cloud-api-adaptor
configuration.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/589
> ibmcloud: create ibmcloud self-managed cluster

- pkg/adaptor/cloud/aws/provider.go
- pkg/adaptor/cloud/azure/provider.go
- pkg/adaptor/cloud/cloud.go
- pkg/adaptor/cloud/cloud_test.go
- pkg/adaptor/cloud/ibmcloud/provider.go
- pkg/adaptor/cloud/libvirt/provider.go
- pkg/adaptor/cloud/vsphere/provider.go
- pkg/adaptor/server.go
- pkg/adaptor/server_test.go
This patch adds a hook to clean up a cloud provider.
Fixes #593
> pkg/adaptor: Add Teardown() to cloud.Provider

- cmd/cloud-api-adaptor/main.go
Re-add vshpere to the print,
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/477
Signed-off-by: Jordan Jackson <jordan.jackson@ibm.com>
> vshpere: Add vshpere back to the command help

- libvirt/README.md
Now that https://github.com/confidential-containers/cloud-api-adaptor/pull/568 is merged, we can remove duplicated information from libvirt/README.md. Also the document contains outdated information that was deleted in favor of the e2e demo section.
CC @stevenhorsman
> Libvirt README.md improvements

- .github/workflows/lint.yaml
- Makefile
Escape analysis checks results are useful for performance optimization, but not useful for finding bugs and memory leaks. Running this test in CI shows confusing errors.
Fixes #604
> Stop execution of escapes check in CI

- libvirt/README.md
- pkg/adaptor/proxy/service.go
- podvm/Makefile.inc
- volumes/csi-wrapper/hack/ibm/ibm-vpc-block-csi-driver.patch
This fix is a part of an umbrella issue https://github.com/kubernetes/k8s.io/issues/4780
> all: migrate from k8s.gcr.io to registry.k8s.io

- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- Makefile
- pkg/adaptor/cloud/libvirt/image.go
- pkg/adaptor/cloud/libvirt/libvirt.go
- pkg/adaptor/cloud/libvirt/provider.go
- pkg/adaptor/cloud/libvirt/stream.go
- pkg/adaptor/cloud/libvirt/types.go
- pkg/adaptor/cloud/libvirt/volume.go
to allow easy importing of the pkg
Fixes: #617
> libvirt: remove non-essential libvirt build tags

- peer-pod-controller/Makefile
Installing via `go get` is deprecated since 1.17. Instead, use `go install` to download the binaries.
Fixes: #515
Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>
> controller: download binaries via go install instead of go get

- Makefile
- test/e2e/README.md
- test/e2e/main_test.go
- test/e2e/provision.go
This PR contains some fixes and features missed in the https://github.com/confidential-containers/cloud-api-adaptor/pull/386 that introduced the e2e framework.
>  test/e2e: Introduce a e2e framework for testing - part 2

- ibmcloud/terraform/cluster/ansible/kata-playbook.yml
Build CAA with RELEASE_BUILD=true to exclude the libvirt provider.
Fixes: #636
> ibmcloud: build caa with release build set

- pkg/adaptor/cloud/azure/provider.go
- pkg/adaptor/server_test.go
- pkg/podnetwork/tuntest/util.go
Some functions in package `io/ioutil` are deprecated as of go 1.16 and 1.17. Move to using functions from package `io` or `os`.
Fixes:#646
> pkg: use io or os package instead of deprecated io/ioutil

- .github/workflows/lint.yaml
- .golangci.yaml
This PR updates the version of golangci-lint to 1.47.3. It also remove the deprecated linter - `structcheck`.
Fixes:#631
> update golangci-lint version

- test/e2e/README.md
- test/e2e/azure_test.go
- test/e2e/common_suite.go
- test/e2e/ibmcloud_test.go
- test/e2e/main_test.go
- test/e2e/provision.go
- test/e2e/provision_azure.go
- test/e2e/provision_ibmcloud.go
- test/e2e/provision_libvirt.go
Since commit 54ce74374be8a it has been passed all cloud providers in the golang -tags option because now it built a single cloud-api-adaptor.
That broke the e2e tests as the compiler find multiple implementations of GetCloudProvisioner(). In order to solve, it is added the `GetCloudProvisioner(provider)` function that returns an implementation based on `provider`.
Fixes: #573
> test/e2e: implement the GetCloudProvisioner() factory

- Makefile
- hack/build.sh
Fixes: #637
@jtumber-ibm @stevenhorsman @snir911 PTAL.
The PR will ensure both dev and release builds for every PR merged and use `dev-$timestamp` and `release-$timestamp` as tags. Also the `latest` tag will be only for dev release.
Hope this approach will be able to meet the requirements for multi-arch as well.
> gh-action: build dev and release images for every PR merge

- go.mod
- go.sum
- test/e2e/README.md
- test/e2e/main_test.go
- test/e2e/provision.go
- test/e2e/provision_libvirt.go
This allow passing properties to the provisioner via a file which path should be specified in the TEST_E2E_PROVISION_FILE variable.
Fixes #592
> test/e2e: read provision properties from file

- .github/workflows/build.yaml
- Makefile
- docs/DEVELOPMENT.md
This PR introduces the BUILTIN_CLOUD_PROVIDERS variable in Makefile to specify cloud providers that to be built into the cloud-api-adaptor binary.
This patch also refactors Makefile to simplify the rules to derive build tags and CGO_ENABLED.
Fixes #653
> makefile: Parameterize built-in cloud providers

- install/overlays/aws/kustomization.yaml
- install/overlays/azure/kustomization.yaml
- install/overlays/ibmcloud/kustomization.yaml
- install/overlays/libvirt/kustomization.yaml
- install/overlays/vsphere/kustomization.yaml
Added the missing kind and apiVersion fields to all install/overlays/*/kustomization.yaml
Fixes #666
> install: add kind and apiVersion to kustomization files

- test/e2e/libvirt_test.go
- test/provisioner/provision_azure.go
- test/provisioner/provision_ibmcloud.go
- test/provisioner/provision_libvirt.go
- test/provisioner/provision_libvirt_nocgo.go
Avoid compile error when using tag to filter tests 
Add CGO constraint for libvirt
Fixes #658
Signed-off-by: Lei Li [genjuro214@gmail.com](mailto:genjuro214@gmail.com)
> e2e: remove build tags in provision_*.go files

- .github/workflows/podvm.yaml
Keeping vsphere in for `open-vm-tools`.
Tested matrix logic using `act`
```
act -n -j build -W .github/workflows/podvm.yaml | grep Matrix
*DRYRUN* [Create Pod VM Image/Create pod vm image-3] 🧪  Matrix: map[arch:amd64 os:ubuntu provider:vsphere]
*DRYRUN* [Create Pod VM Image/Create pod vm image-1] 🧪  Matrix: map[arch:amd64 os:centos provider:generic]
*DRYRUN* [Create Pod VM Image/Create pod vm image-4] 🧪  Matrix: map[arch:s390x os:ubuntu provider:generic]
*DRYRUN* [Create Pod VM Image/Create pod vm image-2] 🧪  Matrix: map[arch:amd64 os:ubuntu provider:generic]
```
Will result in 4 images
- podvm-vsphere-ubuntu-amd64
- podvm-generic-centos-amd64
- podvm-generic-ubuntu-amd64
- podvm-generic-ubuntu-s390x
A more appropriate name than `generic` for the providers other than `vsphere` might be …
> github: remove provider specific podvm builds

- .github/workflows/controller.yaml
Add a new github workflow to run required checks for peerpod controller
This PR depend on: #675 
Fixes: #665
> gh-action: add peerpod controller workflow

- ibmcloud/terraform/cluster/ansible/kube-playbook.yml
> ibmcloud: remove go1.18.x from terraform build

- hack/build.sh
This patch fixes the problem that hack/build.sh fails due to unbound variable error when RELEASE_BUILD is not set.
Fixes #690
> build: Fix unbound variable error of hack/build.sh

- test/e2e/main_test.go
- test/provisioner/provision_ibmcloud_initializer.go
Fixes #693
I tried a solution by invoking `pv.GetCloudProvisioner`, regardless of whether `shouldProvisionCluster` is true or false.
Set TEST_E2E_PROVISION_FILE like:
```
APIKEY="xxx"
IAM_SERVICE_URL="https://iam.test.cloud.ibm.com/identity/token"
VPC_SERVICE_URL="https://us-south-stage01.iaasdev.cloud.ibm.com/v1"
```
> e2e: fix error to run tests with shouldProvisionCluster false

- peer-pod-controller/config/manager/manager.yaml
otherwise controller will fail to get namespace correctly
Fixes: #706
Related also to: https://github.com/confidential-containers/cloud-api-adaptor/issues/708
> controller: fix namespace variable name to match implementation

- pkg/adaptor/cloud/cloud.go
While setting instance details for the sandbox, `instanceID` is assigned to `instanceName`. Fix it.
Fixes: #718
> cloud: set the instance name correctly

- podvm/Makefile
- podvm/qcow2/centos/qemu-centos.pkr.hcl
- podvm/qcow2/centos/variables.pkr.hcl
- podvm/qcow2/rhel/qemu-rhel.pkr.hcl
- podvm/qcow2/rhel/variables.pkr.hcl
- podvm/qcow2/ubuntu/qemu-ubuntu.pkr.hcl
- podvm/qcow2/ubuntu/variables.pkr.hcl
Confidential VM images are UEFI based and in order to customise them, we need qemu builder to support UEFI
Fixes: #721
> podvm: Enable uefi for qemu builder

- test/provisioner/provision_ibmcloud.properties
- test/provisioner/provision_ibmcloud_initializer.go
If `TEST_E2E_PROVISION=no`, some properties should be initialized in `initProperties()` from the properties file.
Also adjust the properties check according to TEST_E2E_PROVISION value
Fixes #730
Signed-off-by: Lei Li <genjuro214@gmail.com>
Signed-off-by: Lei Li <cdlleili@cn.ibm.com>
> e2e: make tests pass for ibmcloud with TEST_E2E_PROVISION=no

- cmd/starter.go
- cmd/starter_test.go
- go.mod
- go.sum
- pkg/forwarder/forwarder.go
- podvm/files/etc/systemd/system/agent-protocol-forwarder.service
This patch enables notification to systemd using the sd_notify protocol.  When the program is running as a systemd service with type=notify, and becomes ready for serving requests, systemd gets notified.
Fixes #735
> cmd: Notify systemd about service state changes

- azure/go.mod
- podvm/go.mod
The `go.mod` file in the `podvm` directory is empty to void the issue addressed by #500. But, empty `go.mod` file causes errors when we run some go commands as described in #747.
This PR keeps the go.mod file, but changes the file to use a valid go.mod file format. I confirmed that referencing `cloud-api-adaptor` repo as a go module from another go program still works after this change is introduced.
This PR also removes `azure/go.sum`, since this file is no longer necessary, as #538 has removed the files that caused the problem.
> go: Use valid go.mod format in the podvm directory

- ibmcloud/terraform/cluster/main.tf
- ibmcloud/terraform/cluster/outputs.tf
- ibmcloud/terraform/run-nginx-demo/main.tf
- ibmcloud/terraform/start-cloud-api-adaptor/main.tf
The attribute `primary_ipv4_address` is deprecated. Instead, use `primary_ip.address`.
Fixes: #743
> terraform: remove deprecated attributes

- podvm/Makefile
The default boot_wait of 10s for packer qemu builder is not sufficient in some environments. Set it to a higher value of 5 min to give enough time for the VM to boot for customisations.
Fixes: #758
> podvm: Increase boot_wait time for all distros

- podvm/Makefile.inc
Running "make BINARIES= image" will not rebuild the BINARIES target and just create the image with what is already available under podvm/files.
This helps with quick podvm image customisations.
Fixes: #760
> podvm: Add the ability to disable BINARIES target

- cmd/cloud-api-adaptor/main.go
- entrypoint.sh
- pkg/adaptor/proxy/factory.go
- pkg/adaptor/proxy/proxy.go
- pkg/adaptor/proxy/proxy_test.go
- pkg/adaptor/server.go
- pkg/adaptor/server_test.go
- pkg/adaptor/shim_test.go
- pkg/forwarder/interceptor/interceptor.go
This PR introduces a new flag `proxy-timeout` which represents the maximum time in minutes for establishing agent proxy connection. It also refactors the retry logic for establshing connection between agent proxy and `agent-protocol-forwarder` on peer pod VM and between `agent-protocol-forwarder` and kata agent.
Fixes: #754
> pkg: enhance retry logic for establishing connections

- go.mod
- go.sum
- pkg/adaptor/proxy/proxy.go
- pkg/adaptor/proxy/proxy_test.go
Also increase the default timeout to account for different environments
Fixes: #794
> proxy: Fix proxytimeout handling

- test/provisioner/provision.go
Import oidc to prevent error
```
time="2023-03-31T06:56:01-07:00" level=trace msg="start of Deploy &{<nil> /root/.kube/config  <nil> <nil> map[] <nil> map[] <nil> false false false false}"
F0331 06:56:01.646445  114195 env.go:360] Setup failure: envconfig: client failed: no Auth Provider found for name "oidc"
```
Fixes: #777
> test/e2e: Add support for oidc

- ibmcloud/IMPORT_PODVM_TO_VPC.md
- ibmcloud/image/import.sh
- Add the ability to create the VPC image to staging, like push.sh does, by allowing the api endpoint to be overridden
Fixes: #774
> ibmcloud: Add the ability to import to staging

- cmd/cloud-api-adaptor/cloudmgr/manager.go
- cmd/cloud-api-adaptor/main.go
- cmd/parse.go
This PR makes `cloud-api-adaptor` shows a list of supported cloud providers that are actually built into the binary, instead of names hard-coded in the source code.
This PR also improves the command help message.
Fixes #787
> cmd: cloud-api-adaptor correctly shows builtin cloud provider names

- ibmcloud/terraform/README.md
- ibmcloud/terraform/cluster/ansible/kata-playbook.yml
- install/runtime-payload/config/configuration-remote.toml
This PR replaces configuration-remote.toml with the latest one from the upstream Kata Containers CCv0. The configuration file is modified to enable debug options.
The original file is a generated one from [`src/runtime/config/configuration-remote.toml.in`](
https://github.com/kata-containers/kata-containers/blob/dfa7ed06eb89f6bf7f5f20898ff5c6f28c9c5ba4/src/runtime/config/configuration-remote.toml.in) of https://github.com/kata-containers/kata-containers/commit/dfa7ed06eb89f6bf7f5f20898ff5c6f28c9c5ba4 
The following options are additionally enabled, since the [old `configuration-remote.toml`](https://github.com/confidential-containers/cloud-api-adaptor/blob/2a6a4d40690232874cb1206d159bc1e4c0da5d06/install/runtime-payload/config/configuration-remote.toml) also had these options enabled.
``` …
```
> Update configuration-remote.toml.in to enable static_sandbox_resource_mgmt

- test/provisioner/provision_ibmcloud.go
- test/utils/reader.go
- refine UploadPodvm function to support run e2e test with TEST_PODVM_IMAGE multi-times
Fixes: #812
> ibmcloud: refine UploadPodvm function

- peerpod-ctrl/Makefile
- pkg/adaptor/cloud/azure/manager.go
This add the necessary bits for azure support by the peerpod-ctrl, however:
WIP as I don't have access to azure required testing:
the [following](https://github.com/snir911/cloud-api-adaptor/tree/375merged_azure) is hacked branch that can be tested:
use `quay.io/snir/cloud-api-adaptor:test `for the caa pod
& deploy controller with `cd peerpod-ctrl && make docker-build docker-push IMG=quay.io/snir/osc-operator:rename`
**after merging this will require to update go.mod in peerpod-ctrl**
> peerpod-ctrl: build azure by default

- peerpod-ctrl/go.sum
- peerpod-ctrl/main.go
This is the follow-on PR of #786.
The location of `cmd/cloud-api-adaptor/cloudmgr` has been moved to `pkg/adaptor/cloud`. This PR updates its pacakge path in peerpod-ctrl. We need a separated PR, since peerpod-ctrl is an independent Go module that references the main module as a remote module.
Fixes #830
> Use new pkg path of cloudmgr in peerpod-ctrl

- .github/workflows/daily-e2e-tests-ibmcloud.yaml
- add e2e-test base on IKS with s390x worker nodes
- build podvm inside container
- provision/clean e2e-test resources via e2e-go-framework
Fixes: #828
> workflow: ibmcloud e2e-tests base on iks clusters

- peerpodconfig-ctrl/controllers/peerpodconfig_controller.go
otherwise it fails with:
panic: odd number of arguments passed as key-value pairs for logging
Fixes: #820
> peerpodconfig-ctrl: change logging format

- pkg/adaptor/server_test.go
This PR changes the test code to wait for the server to become ready by using a channel instead of sleep.
This PR also removes some leftover code in the test code.
Fixes #837
> Fix a flaky test in pkg/adaptor/server_test.go

- test/e2e/libvirt_test.go
The configmap and secret tests were introduced on commit ee4eef6df380a7a but only enabled to ibmcloud. Let's run them as part of the libvirt e2e suite as well.
Fixes #807
> test/e2e: Enable configmap and secret tests to Libvirt

- Makefile
- cmd/agent-protocol-forwarder/main.go
- cmd/cloud-api-adaptor/main.go
- cmd/version.go
- cmd/version_test.go
This patch updates Makefile to derive version information from the latest git release tag, and embed it in binaries.
The version information is also shown in the begging of log messages from the commands.
Fixes #850 
A version information is shown like this
```
cloud-api-adaptor version v0.5.0-dev
commit: f3f604e9cd8be01a1922b8c84e95bd4afd4b0bad-dirty
go: go1.19.4
```
> cmd: Show version information

- .github/workflows/lint.yaml
- .golangci.yaml
- volumes/csi-wrapper/cmd/csi-controller-wrapper/main.go
- volumes/csi-wrapper/cmd/csi-node-wrapper/main.go
- volumes/csi-wrapper/cmd/csi-podvm-wrapper/main.go
- volumes/csi-wrapper/pkg/peerpodvolume/monitor.go
- volumes/csi-wrapper/pkg/wrapper/controllerservice.go
- volumes/csi-wrapper/pkg/wrapper/identityservice.go
- volumes/csi-wrapper/pkg/wrapper/nodeservice.go
- volumes/csi-wrapper/pkg/wrapper/podvmservice.go
- volumes/csi-wrapper/pkg/wrapper/server.go
This PR fixes the errors reported by golangci-lint in the csi-wrapper module.
I only refactored the code to supress lint errors, and I only added TODO comments at the locations where
errors are reported like this.
```
Error return value of `func` is not checked (errcheck)
```
This PR also bumps the version of golangci-lint to v1.52.2, since  the old version has a bug in processing the --prefix-path option, which is necessary to run the lint tool in sub modules.
> csi-wrapper: Fix lint errors and enable lint checks in CI

- test/e2e/azure_test.go
Enable configmap and secret tests for azure
Fixes #807
Signed-off-by: Kartik Joshi <kartikjoshi@microsoft.com>
> test/e2e: Enable configmap and secret tests to azure

- .github/workflows/image.yaml
This PR changes the GitHub workflow job ([image.yaml](https://github.com/confidential-containers/cloud-api-adaptor/blob/078b6d3f1fb513b3230ea0d54b40cd9b44572b0a/.github/workflows/image.yaml)) to clone the repository to fetch Git tags, which are necessary to derive a correct version string.
Fetching all commits and tags are somewhat inefficient, but there is no other way to generate a version string. In the future, we may introduce a VERSION file like this one. https://github.com/kata-containers/kata-containers/blob/CCv0/VERSION
Fixes #878
> Fetch git tags when buliding container images in CI

- podvm/Makefile
When target distro is not ubuntu make will try to connect to the Internet to download a ubuntu checksum file.
Fixes #889
> podvm: skip download ubuntu checksum during build

- podvm/Makefile
Reverts confidential-containers/cloud-api-adaptor#890
You can't set variables in a Makefile recipe
Errors with 
```
make: UBUNTU_IMAGE_URL: Command not found
make: *** [Makefile:29: setopts] Error 127
```
> Revert "podvm: skip download ubuntu checksum during build"

- pkg/adaptor/cloud/azure/manager.go
fetch it from also environment for peerpod-ctrl usage
Fixes: #881
> azure: resource group is essential for deletion

- install/runtime-payload/scripts/kata-deploy.sh
- install/yamls/ccruntime-peer-pods.yaml
- install/yamls/deploy.yaml
- install/yamls/kustomization.yaml
This PR updates the peer pod fork of the runtime payload to install to the `kata-remote` runtime class.
This is in prep for us switching over to the upstream coco operator rather than using our own fork.
I don't think there is any automation for building the payload image, so this is fairly safe to merge, but then we will need to build the runtime-payload manually and follow up with the doc, webhook and e2e compatible fixes in #904
> Update runtime payload runtimeclassname

- azure/README.md
- azure/image/Dockerfile
- azure/image/Makefile
- azure/image/ubuntu/azure-ubuntu.pkr.hcl
- azure/image/ubuntu/variables.pkr.hcl
- entrypoint.sh
- install/overlays/azure/kustomization.yaml
- pkg/adaptor/cloud/azure/manager.go
- pkg/adaptor/cloud/azure/provider.go
- pkg/adaptor/cloud/azure/types.go
Adds support for building CVM compatible images and CVM support in CVM for azure provider.
Fixes: #799
TODO
> Azure: Support for booting CVMs

- .github/workflows/image.yaml
- entrypoint.sh
- install/overlays/ibmcloud-powervs/cri_runtime_endpoint.yaml
- install/overlays/ibmcloud-powervs/kustomization.yaml
- install/overlays/ibmcloud-powervs/tls_certs_volume_mount.yaml
With the IBM Cloud PowerVS provider support being added, this PR aims at adding the necessary changes to deploy cloud-api-adaptor as a pod running with powervs provider. It also adds support for building cloud-api-adaptor image for ppc64le platform.
Fixes: #801
> powervs: deploy ibmcloud-powervs provider as a pod

- peerpodconfig-ctrl/controllers/peerpodconfig_controller.go
The controller retrieves the list of nodes based on the peerpodconfig nodeselector. The number of nodes in the list is used to proportionally advertise the extended resources among the nodes. However the code didn't handle the case where the list can be empty. This PR fixes the same and doesn't advertise extended resources for empty nodesList
Fixes: #909
> peerpodconfig: Handle empty nodesList

- azure/README.md
- ibmcloud/demo/nginx.yaml
- ibmcloud/demo/runtime-class.yaml
- install/README.md
- libvirt/README.md
- test/e2e/common_suite_test.go
- test/provisioner/provision.go
- volumes/csi-wrapper/hack/ibm/nginx-kata-with-my-pvc-and-csi-wrapper.yaml
- webhook/config/manager/manager.yaml
- webhook/docs/INSTALL.md
- webhook/hack/deploy.yaml
- webhook/hack/pod.yaml
- webhook/hack/rc.yaml
- webhook/hack/webhook-deploy.yaml
- webhook/pkg/mutating_webhook/remove-resourcespec.go
This code depends on #903 and contains the e2e, doc and webhook changes to move us to use `kata-remote` as our peer pods runtime class in prep for switching to use the upstream operator to install the runtime payload.
> Update runtimeclassname in docs/tests/webhook

- azure/image/Dockerfile
With the switch to CVMs on Azure, we need to chose the right SKU offering for Ubuntu CVMs.
Fixes #928
> azure: update sku in Dockerfile to CVM

- ibmcloud/terraform/cluster/ansible/kata-playbook.yml
- ibmcloud/terraform/cluster/ansible/kube-playbook.yml
Update runtime handler to kata-remote in containerd config.
Fixes: #933
> ibmcloud: update runtime handler to kata-remote

- test/e2e/common.go
- test/e2e/common_suite_test.go
Refactor provider-common e2e tests so we have common methods for creating pod objects that all the test cases use.
Fixes: #918
> test/e2e: Refactor kata e2e tests

- ibmcloud/SECURE_EXECUTION.md
- test/provisioner/provision_ibmcloud.go
- test/provisioner/provision_ibmcloud.properties
- How to verify one container is SE enabled
- Use correct osName when create image base on se-podvm image
fixes: #959
> ibmcloud: upload se-podvm image with correct osName

- peerpodconfig-ctrl/config/manager/manager.yaml
- peerpodconfig-ctrl/controllers/peerpodconfig_controller.go
rename it to RELATED_IMAGE_ENV_VAR so that we can include it as a related image in the CSV and by that enable automatic digest pinning in tools like OSBS
(https://osbs.readthedocs.io/en/latest/users.html#creating-the-relatedimages-section)
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/962
> peerpodconfig-ctrl: rename CAA_IMAGE env var

- podvm/Makefile
- increase s390x podvm build boot_wait to 600s to avoid qemu ssh connection timeout 
fixes: #979
> podvm: increase s390x podvm build boot_wait

- podvm/Makefile
- podvm/qcow2/centos/qemu-centos.pkr.hcl
- podvm/qcow2/centos/variables.pkr.hcl
- podvm/qcow2/rhel/qemu-rhel.pkr.hcl
- podvm/qcow2/rhel/variables.pkr.hcl
- podvm/qcow2/ubuntu/qemu-ubuntu.pkr.hcl
- podvm/qcow2/ubuntu/variables.pkr.hcl
Currently, the `boot_wait` option is specified to packer. This option is necessary, because `boot_command` is specified and sent to the started VM via VNC. We are using public cloud VM images, and we do not need to send boot commands via VNC to start up VM.
This patch removes the `boot_command` option, and adds the `disable_vnc` option. This change makes `packer` wait using SSH instead of VNC for VM startup.
Fixes #981
The `ssh_wait_timeout` option is deprecated, and the `ssh_timeout` option is used instead.
https://github.com/hashicorp/packer-plugin-sdk/blob/8331daf9a68be731b67b59621179cd3909458986/communicator/config.go#L125-L131
`packer` proceeds to the next step, immediately after  it successfully connects to a started VM via SSH, so we can specify a large enough value to the …
> podvm: Disable VNC of Packer QEMU Builder

- azure/image/centos/azure-centos.pkr.hcl
- azure/image/centos/variables.pkr.hcl
- azure/image/rhel/azure-rhel.pkr.hcl
- azure/image/rhel/variables.pkr.hcl
- azure/image/ubuntu/azure-ubuntu.pkr.hcl
- azure/image/ubuntu/variables.pkr.hcl
Fixes: #972
---
Follow all the steps before https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/azure#build-pod-vm-image.
- Test the feature in this PR:
```bash
az login
cd image
export PKR_VAR_use_azure_cli_auth=true
export PKR_VAR_resource_group="${AZURE_RESOURCE_GROUP}"
export PKR_VAR_subscription_id="${AZURE_SUBSCRIPTION_ID}"
export PKR_VAR_az_gallery_name="${GALLERY_NAME}"
export PKR_VAR_az_gallery_image_name="${GALLERY_IMAGE_DEF_NAME}"
export CLOUD_PROVIDER=azure
PODVM_DISTRO=ubuntu make image && cd -
```
- The default method should work as is:
```bash
az logout 
cd image
export PKR_VAR_use_azure_cli_auth=false 
export PKR_VAR_resource_group="${AZURE_RESOURCE_GROUP}"
export PKR_VAR_subscription_id="${AZURE_SUBSCRIPTION_ID}"
export …
```
> azure-packer: Allow user to use local credentials

- .golangci.yaml
As the the check is currently failing from time to time due to timeout, increasing it to 10 minutes.
Fixes: #988
> ci: increase golangci-lint timeout

- entrypoint.sh
- install/overlays/ibmcloud/cr_token_projection.yaml
- install/overlays/ibmcloud/kustomization.yaml
- pkg/adaptor/cloud/ibmcloud/manager.go
- pkg/adaptor/cloud/ibmcloud/provider.go
- pkg/adaptor/cloud/ibmcloud/types.go
Remove the need to pass around apikeys when deploying to an IKS cluster by using a [Trusted Profile ](https://www.ibm.com/cloud/blog/introducing-trusted-profiles-for-kubernetes-service-accounts?mhsrc=ibmsearch_a&mhq=trusted%20IAM) in IBM Cloud.
To test this you will need to create a [Trusted Profile](https://cloud.ibm.com/iam/trusted-profiles) in cloud.ibm. This must have the VPC access required to create the peer pod vsi. And you can limit it to the cloud-api-adaptor pod in various ways. I just used the namespace condition for testing.
When setting up the kustomizations, uncomment the IAM PROFILE ID sections (including the patch to mount the volume), and don't set the APIKEY.
> ibmcloud: Support Container Auth with IAM Profiles

- .github/workflows/daily-e2e-tests-ibmcloud.yaml
- download the built podvm-generic-ubuntu oci images from cos
- push them to quay.io with caa_commitid as tag
fixes: #732
for https://github.com/confidential-containers/cloud-api-adaptor/issues/732#issuecomment-1560646723
> podvm: contribute podvm-generic-ubuntu oci images

- install/overlays/ibmcloud/kustomization.yaml
- use old style of install/overlays/ibmcloud/kustomization.yaml
fixes: #1021
> e2e-ibmcloud: quick fix to unblock ibmcloud e2e test

- entrypoint.sh
This was introduced after the last rebase of #955 and found by shellcheck.
Fixes: #1025
> entrypoint: fix shellcheck issue

- test/tools/README.md
- Swap `actions`, for `action` to match the code
Fixes: #1033
> doc: Fix typo

- test/e2e/common.go
- test/e2e/common_suite_test.go
- test/e2e/ibmcloud_test.go
- This added a test case to create SE pod VM in ibmcloud and verify it's SE pod instead of simple pod.
fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/1014
Signed-off-by: yuanyuanwang <wyuany@cn.ibm.com>
> add e2e test case to verify SE pod vm

- .github/workflows/daily-e2e-tests-ibmcloud.yaml
- fix daily podvm image failed to push issue
fixes: #1079
> e2e-test: use a new way to get caa commit_it in ibmcloud e2e-test pipeline

- ibmcloud/README.md
- ibmcloud/cluster/ansible/tasks/bootstrap.yaml
- ibmcloud/cluster/ansible/tasks/k8s.yaml
- ibmcloud/cluster/label-nodes.sh
- ibmcloud/cluster/main.tf
- ibmcloud/cluster/vpc/main.tf
- ibmcloud/cluster/vpc/outputs.tf
- test/provisioner/provision_ibmcloud_initializer.go
Since #1074 has been merged we can achieve the same outcome with the selfmanaged cluster by adding our own labels.
At the same time I have done some quality of life updates to the cluster and README.md to reduce the about of variables that need to be specifed. This also includes no longer erroring if these variables are not set in the provisioner-cli.
> ibmcloud: self-managed cluster qol updates

- .github/workflows/commit-message-check.yaml
When the commit message check runs skip if the author of the PR is dependabot
Fixes: #1096
> dependabot: Skip Fixes Check if user is dependabot

- ibmcloud-powervs/README.md
- ibmcloud-powervs/image/Makefile
- ibmcloud-powervs/image/copy-files.sh
- ibmcloud-powervs/image/prereq.sh
- podvm/Makefile.inc
This PR adds the instructions to build a pod VM image to be used with IBM Cloud PowerVS provider.
Fixes: #785
> powervs: add podvm image documentation for IBM Cloud PowerVS provider

- test/e2e/common.go
- test/e2e/common_suite_test.go
- test/e2e/fixtures/Dockerfile.testworkdir
- test/e2e/ibmcloud_test.go
Added test cases to check whether peer pod logs work directory while created using a custom dockerfile in ibmcloud cloud-provider
Fixes: #1045
> ibmcloud: e2e Test cases for ibmcloud to check Peer Pod Logs Working Directory from container

- test/e2e/common.go
- test/e2e/common_suite_test.go
- test/e2e/fixtures/Dockerfile.testenv
- test/e2e/ibmcloud_test.go
Added test cases to check peer pod logs environment variables in ibmcloud cloud-provider
Fixes: #1044, https://github.com/kata-containers/kata-containers/issues/5730
> ibmcloud: Added test cases to check peer pod logs environment variables

- .github/workflows/commit-message-check.yaml
community was renamed to confidential-containers, so fixing the broken link.
Fixes: #1120
> ci: fix broken link to community repo

- .github/workflows/build-golang-fedora.yaml
- Dockerfile
- hack/Dockerfile.golang
- hack/update-go-container.sh
Previously, the docker build used the golang image, which is based
on debian, and copied the dynamically linked binary into a fedora
layer. This change switches the build to use a custom golang-fedora
image as builder.
Fixes #1093
Fixes #1113
Please check if this works for other platforms than amd64.
> image: use golang-fedora as builder

- test/e2e/common_suite_test.go
As containers fails to reach completed status on first attempt, this fix resolves the issue by restarting the container if failure happens
Fixes: #1128
> ibmcloud: Fix for container failure on test cases

- test/e2e/common.go
- test/e2e/common_suite_test.go
- test/e2e/ibmcloud_test.go
- volumes/csi-wrapper/README.md
- volumes/csi-wrapper/hack/ibm/cleanandreinstall.sh
- volumes/csi-wrapper/hack/ibm/ibm-vpc-block-csi-driver-v5.2.0.yaml
- volumes/csi-wrapper/hack/ibm/nginx-kata-with-my-pvc-and-csi-wrapper.yaml
- csi-wrapper must is ready to use
- only run the test case when env TEST_CSI_WRAPPER=yes
- create pvc and pod with csi-wrapper containers
- clean created pvc after the test case
fixes: #1124
> e2e: csi-wrapper test case base on ibm-vpc-block-csi-driver:master

- .github/workflows/links.yml
- .lycheeignore
- test/e2e/README.md
This new workflow will detect broken links.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/1134
> ci: add workflow to detect broken links 

- .github/workflows/lint.yaml
- Makefile
- go.mod
- go.sum
- hack/go-tidy.sh
- volumes/csi-wrapper/go.sum
Adding a CI workflow to check if all Go modules are tidy. Also adding
the required make targets.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/1141
> ci: add go tidy check

- azure/README.md
- install/overlays/azure/.gitignore
- install/overlays/azure/kustomization.yaml
This PR uses the kustomization facility to reference an env file for a key/value map. We can then put the env file into gitignore.
fixes #1131
> Azure: Use env file for secrets in kustomization

- pkg/adaptor/cloud/azure/provider.go
https://github.com/confidential-containers/cloud-api-adaptor/pull/954 introduces a bug in Azure provider.
Fixes #1150
> azure: Fix IP address parsing error

- test/provisioner/provision.go
Apparently 60 seconds is not enough to wait for the cc-operator-daemon-install DaemonSet to be scheduled, as the libvirt e2e has failed on waiting. So increased the timeout to 5 minutes.
> test/e2e: increase timeout to wait cc-operator-daemon-install

- docs/tls-proxy-forwarder.md
- install/overlays/aws/kustomization.yaml
- install/overlays/azure/kustomization.yaml
- install/overlays/ibmcloud-powervs/kustomization.yaml
- install/overlays/ibmcloud/kustomization.yaml
- install/overlays/libvirt/kustomization.yaml
- install/overlays/vsphere/kustomization.yaml
- update related strings to make it more clearly where the created cert files will be put
- remove bad arg '-days' when create *.crs file to avoid `Ignoring -days; not generating a certificate` message
fixes: #1154
> tls-certs: tow tiny changes for tls-proxy-forwarder document

- .github/workflows/build.yaml
- .github/workflows/commit-message-check.yaml
- .github/workflows/controller.yaml
- .github/workflows/csi_wrapper_images.yaml
- .github/workflows/daily-e2e-tests-ibmcloud.yaml
- .github/workflows/image.yaml
- .github/workflows/lint.yaml
- .github/workflows/test-images.yaml
- .github/workflows/webhook-build.yaml
- .github/workflows/webhook-test.yaml
Adding workflow_dispatch as trigger where it makes sense, so workflows can be triggered manually when needed, e.g., on forks. Removing values that are already present as default.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/1170
> ci: minor refactoring of workflow triggers

- test/e2e/fixtures/Dockerfile.testuser
Modified Dockerfile to resolve unstable test results of TestCreatePeerPodAndCheckUserLogs
Fixes: #1127
> ibmcloud: Bug fix to resolve unstable testuser image

- install/overlays/libvirt/kustomization.yaml
- pkg/adaptor/cloud/libvirt/libvirt.go
- pkg/adaptor/cloud/libvirt/manager.go
- pkg/adaptor/cloud/libvirt/types.go
- test/e2e/README.md
- test/provisioner/provision_libvirt.go
It is not too convinient to always hardcode the image used by libvirt to podvm-base.qcow2. Use LIBVIRT_VOL_NAME to specify a custom qcow2 image to use.
> libvirt: add LIBVIRT_VOL_NAME environment variable

- .github/workflows/daily-e2e-tests-ibmcloud.yaml
fix: https://github.com/confidential-containers/cloud-api-adaptor/issues/1188
This enable workflow to display e2e test result of csi wrapper. The e2e test of csi wrapper includes creating self managed kubeadm cluster in IBMCloud, then installing cloud api adapater and csi wrapper to the cluster, at last testing csi wrapper.
Signed-off-by: yuanyuanwang wyuany@cn.ibm.com
> e2e: add workflow for csi wrapper e2e test

- test/provisioner/provision_azure.go
> provisioner-azure: Use API to label nodes

- volumes/csi-wrapper/examples/azure/README.md
It mentions the `hack/` directory but it's now `examples/`
Fixes #1209
> csi-wrapper: fix README

- pkg/adaptor/cloud/azure/provider.go
Several changes that will allow us to publish demo images for CAA:
- support passing community gallery id in caa
- ~allow building a second attestation-agent (w/ grpc)~
- ~add tdx dependencies to ubuntu podvm image (azure-only but should go everywhere) so that cc_kbc can be used~
> Azure community gallery support

- pkg/podnetwork/tunneler/vxlan/workernode.go
The workerNodeTunneler.Setup() can get an empty list of pod node IPs and it will panic due to `index out of range` access. Added handlers for the following situations:
* podNodeIPs is zero then return error
* podNodeIPs is less than 2 IPs on a dedicated tunnel config then return error
Fixes #1207
> podnetwork: Fix workerNodeTunneler.Setup() panic

- azure/image/centos/azure-centos.pkr.hcl
- azure/image/rhel/azure-rhel.pkr.hcl
- azure/image/ubuntu/azure-ubuntu.pkr.hcl
Right now the `toupload` directory is referenced with ./ in some places
and in some places without it. This causes the packer to be not able to
find the directory and hence the build fails.
Fixes #1179
> azure-packer: Provide consistent path of toupload dir

- peerpod-ctrl/go.mod
- peerpod-ctrl/go.sum
- volumes/csi-wrapper/go.mod
- volumes/csi-wrapper/go.sum
I've already tagged `main` with `v0.7.0`. It is time to update the peerpod-ctrl and csi-wrapper modules to use the tagged cloud-api-adaptor go module.
> Release 0.7.0 tagging go modules

- test/provisioner/kustomize.go
Adds a check to avoid adding a file to secretGenerator in kustomization.yaml if it already is listed there.
Originally, in the libvirtd tests, if libvirtd_ssh_key_file was set and TEST_PROVISION_FILE environment variable was used, it would fail if one did not remember to reset the kustomization.yaml between tests.
Fixes: #1192
> test/provisioner: avoid adding duplicate file in secretGenerator

- libvirt/kcli_cluster.sh
- test/e2e/README.md
- test/provisioner/provision_libvirt.go
Creates a cluster_name property that can be added to the libvirt properties file and corresponding LibvirtProvisioner struct.
Before createCluster executes kcli_cluster.sh, it adds the cluster name, network, and storage pool to the environment.
Fixes: #1163
> test/e2e/livirt: allow prop file overwrite cluster name

- test/provisioner/common.go
- test/provisioner/provision_libvirt.go
libvirt e2e tests did not properly label worker nodes with the worker label.
This creates a function in test/provisioner/common.go that adds the worker label to the libvirt e2e createCluster.
Fixes: #1107
> tests: add worker label through go

- Dockerfile
The use of `--platform=$TARGETPLATFORM` was introduced by mistake in #1116, and caused long build times, as it emulates the target platform instead of using Go cross-compilation.
Fixes: #1234
Run finished in 19 min: https://github.com/katexochen/cloud-api-adaptor/actions/runs/5678850841
> image: revert to use amd64 as build platform

- install/yamls/caa-pod.yaml
> install: add rollingUpdate strategy in caa daemonset

- .github/workflows/podvm_builder.yaml
- ibmcloud-powervs/image/prereq.sh
- podvm/Dockerfile.podvm_builder
- podvm/Dockerfile.podvm_builder.centos
- podvm/Dockerfile.podvm_builder.rhel
- podvm/README.md
- versions.yaml
Upgrading to the version currently used by kata. A dependency of attestation-agent required a upgrade to at least 1.67.
Fixes: #1277
> deps: upgrade rust to 1.69.0

- .github/workflows/podvm_builder.yaml
- Makefile
- install/overlays/aws/kustomization.yaml
- install/overlays/azure/kustomization.yaml
- install/overlays/ibmcloud-powervs/kustomization.yaml
- install/overlays/libvirt/kustomization.yaml
- install/overlays/vsphere/kustomization.yaml
- podvm/Dockerfile.podvm_builder
- podvm/Dockerfile.podvm_builder.centos
- podvm/Dockerfile.podvm_builder.rhel
As delineated in our [release process post-release phase](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#post-release) we should revert some changes after the release to get latest updates of components. Actually this PR contain two reverts that aren't described on current release document, but are on the new version on PR #1254 (Release process document improvements).
Ran the libvirt e2e tests successfully: 
```
Wait for the cc-operator-daemon-install DaemonSet be available
Wait for the pod cc-operator-daemon-install-xr8kf be ready
Wait for the cloud-api-adaptor-daemonset DaemonSet be available
Wait for the pod cloud-api-adaptor-daemonset-f9bwl be ready
Wait for the kata-remote runtimeclass be created
=== RUN   TestLibvirtCreateSimplePod …
```
> Post v0.7.0 release updates

- test/provisioner/provision_azure_initializer.go
Right now the default instance type for podvm is a regular VM instead of a CVM. This commit switches the default to CVM.
Fixes: #1295
> azure-provisioner: Default to CVM instead of VM

- test/provisioner/provision_azure.go
When we create the "Resource Group" from the test provisioner code we get the RG object and we use it as is when running the code. But when the RG is managed by CI we don't get the RG object and we need to get it from the Azure API. This commit adds the code to get the RG object when the RG is managed by CI.
Currently the test panics because there is no RG object.
Fixes #1290
> azure-provisioner: Get RG when using CI managed RG

- test/e2e/common_suite_test.go
Added skip for user test cases until kata fix
Fixes: #1127
Skipping `TestCreatePeerPodAndCheckUserLogs` until [issue-5732](https://github.com/kata-containers/kata-containers/issues/5732) is Fixed
> ibmcloud: Added test skip for userlogs

- install/overlays/ibmcloud/kustomization.yaml
- test/provisioner/provision_ibmcloud.go
- test/provisioner/provision_ibmcloud.properties
- test/provisioner/provision_ibmcloud_initializer.go
- test/provisioner/provision_ibmcloud_kustomize.go
Uncomment profile id steps in kustomize.yaml
Add extra validation for steps which require API key to be set
Fixes: #1243
> provisioner-cli: Update provisioner files to include profile id support

- pkg/adaptor/cloud/ibmcloud/manager.go
- pkg/adaptor/cloud/ibmcloud/provider.go
- pkg/adaptor/cloud/ibmcloud/provider_test.go
- pkg/adaptor/cloud/ibmcloud/types.go
- pkg/adaptor/cloud/ibmcloud/types_test.go
Add the ability to specify a list of allowed image-ids Trim the list to remove image-ids not found in the same region as the node
Adds check that the ARCH matches the spec request, but that currently doesn't work as the instance spec ARCH value doesn't currently get populated.
Fixes: #1266
> ibmcloud: allow list of image-ids

- test/provisioner/provision_ibmcloud_kustomize.go
Removed extra properties in tag response other than Name and Manifest
Fixes: #1311
> ibmcloud: Auto update CAA tag

- pkg/adaptor/cloud/libvirt/libvirt.go
- pkg/adaptor/cloud/libvirt/libvirt_test.go
- pkg/adaptor/cloud/libvirt/types.go
Fixes #1248
This PR creates a domainXML based on the architecture of the target host.
First it finds the architecture via the GetNodeInfo method. Then if the architecture (aka Model) is s390x we'd create the domain XML with the s390x specifics, else it returns the x86_64 version as before.
> pkg/adaptor/libvirt: adds support for s390x based libvirt hosts

- test/provisioner/provision_ibmcloud.properties
- test/provisioner/provision_ibmcloud_initializer.go
Fixes: #1328
Allow the default IBM Cloud Kubernetes Service endpoint to be overriddden by a custom private or Staging Kubernetes service endpoint.
> ibmcloud: allow kubernetes service endpoint to be overridden

- cmd/cloud-api-adaptor/main.go
- install/rbac/peer-pod.yaml
- install/yamls/caa-pod.yaml
- pkg/probe/checker.go
- pkg/probe/probe.go
- pkg/probe/probe_test.go
> install: add probes for caa ds rolling update

- test/e2e/libvirt_test.go
enables tests in common suite test:
TestLibvirtCreatePeerPodContainerWithExternalIPAccess TestLibvirtCreatePeerPodWithJob
TestLibvirtCreatePeerPodAndCheckUserLogs
TestLibvirtCreatePeerPodAndCheckWorkDirLogs
TestLibvirtCreatePeerPodAndCheckEnvVariableLogsWithImageOnly TestLibvirtCreatePeerPodAndCheckEnvVariableLogsWithDeploymentOnly TestLibvirtCreatePeerPodAndCheckEnvVariableLogsWithImageAndDeployment TestLibvirtCreatePeerPodWithLargeImage
Haven't gotten to enabling:
TestLibvirtCreatePeerPodWithPVCAndCSIWrapper
TestLibvirtCreateConfidentialPod - Not going to enable until #1019
Currently fails on:
--- FAIL: TestLibvirtCreatePeerPodAndCheckEnvVariableLogsWithDeploymentOnly (600.01s)
--- FAIL: TestLibvirtCreatePeerPodAndCheckEnvVariableLogsWithDeploymentOnly/EnvVariablePeerPodWithDeploymentOnl …
> tests/e2e/libvirt: close test gap.

- volumes/csi-wrapper/examples/ibm/README.md
Updated path from hack to examples in Test CSI Wrapper with ibm-vpc-block-csi-driver for peer pod demo on IBM Cloud VPC  documentation
Fixes: #1336
> ibmcloud: Updated path in Test CSI Wrapper documentation

- .github/workflows/image.yaml
The CAA image build on push is very important to not fail otherwise features and fixes don't properly get into devel/release cycle. But we recently have noticed errors like:
ERROR: failed to solve: DeadlineExceeded: failed to push quay.io/confidential-containers/cloud-api-adaptor:b277c1ae739ae318926ef4f39c88fac16050d13a: no active session for pj7teq3k1b3tqjew1y3tf5mgp: context deadline exceeded
Error that goes away when the workflow is manually re-trigger after a few minutes. So this added a retry mechanism that will try again the build command after 2 minutes and for the maximum of 3 tentatives.
> workflow: retry caa image build

- test/tools/Makefile
Make the provisioner CLI Makefile choose the GOOS automatically
Choose the default GOOS based on the machine type the provisioner CLI is being built on 
Set the value to either linux or darwin
Fixes #1091
Signed-off-by: Tia Shah <tia.shah@ibm.com>
> 1091: Make the provisioner CLI Makefile choose the GOOS automatically

- test/provisioner/common.go
- test/provisioner/provision_ibmcloud_initializer.go
- test/tools/provisioner-cli/main.go
Skip checking properties unnecessary for image upload are set if the provisioner only does the upload image action
Use the Action variable as a way to check if uploadimage is being performed 
Skip checks for unneeded variables if this is the action set
Set TEST_PROVISION to yes if the action is only uploadimage
Fixes #1092 
Signed-off-by: Tia Shah <tia.shah@ibm.com>
> 1092: Skip checking properties unnecessary for image upload are set if the provisioner only does the upload image action

- .github/workflows/azure-e2e-test.yml
fixes #1375
The podvm-related build steps/jobs will be skipped if the input is empty.
The test provisioner code will use the image id if available, otherwise fall-back to the one built in prior steps.
The test job will hence always run, unless the workflow is cancelled. Drive-by fixed some minor things.
Partially successful (the tests are flaky, atm) run with the 0.7 podvm image [here](https://github.com/mkulke/cloud-api-adaptor/actions/runs/6024476613/job/16343401526)
> Allow prebuilt podvm image in e2e test

- .github/workflows/azure-e2e-test.yml
fixes #1367
The build time w/ filled cache is being reduced from [35min](https://github.com/mkulke/cloud-api-adaptor/actions/runs/5975499062) => [11min ](https://github.com/mkulke/cloud-api-adaptor/actions/runs/5999088167)
- kata-agent is being cached depending on the revision specified in the workflow
- attestation-agent and the pause image are cached depending on the revisions specified in the podvm/Makefile.inc file
- agent-protocol-forwarder is always built
Related changes:
- Only install the musl-toolchain for Rust
- Skip cloning kata-containers, if we don't need to rebuild it
- The podvm image target skips building binaries, since kata-agent has a "force" dependency and would always trigger a rebuild.
> azure: cache podvm binaries in e2e test workflow

- .github/workflows/caa_build_and_push.yaml
- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_on_pull.yaml
- .github/workflows/image.yaml
- hack/build.sh
- libvirt/kcli_cluster.sh
- test/e2e/libvirt_test.go
- test/provisioner/provision.go
This is my second tentative to have the libvirt e2e tests running for pull requests.
From the user point of view, the workflow is executed by adding the `test_e2e_libvirt` label. In theory if we add support for other providers, it would be a matter of adding a new label. However it may not work as the common jobs (see below) will be triggered every time a `test_e2e_*` label is added to the PR. I prefer to defer that discussion for when (and if) we add other e2e jobs.
Still regarding how it is triggered, an alternative would be to use comments on PR (e.g. `/test_e2e_libvirt`) but then we hit a bunch of limitations on Github actions design. To mention the most basic: on commenting the workflow runs on context of the `main` branch meaning that it doesn't give the reference to the pull …
> Libvirt e2e CI for pull requests

- webhook/Makefile
This PR adds ppc64le as a supported architecture for webhook image and to build and publish it.
Fixes: #1342
> webhook: add ppc64le platform support

- podvm/Dockerfile.podvm_builder
- podvm/Dockerfile.podvm_builder.centos
- podvm/Dockerfile.podvm_builder.rhel
Fixes: #1357
Tested creating a podvm qcow2 image in docker. After uploading it to ibmcloud.
```
$ ibmcloud is instances
Listing instances in all resource groups and region eu-gb under account James Tumber's Account as user james.tumber@ibm.com...
ID                                          Name                   Status    Reserved IP    Floating IP      Profile   Image                                VPC               Zone      Resource group   
07a7_6ba80928-d0ce-4505-85fc-f7851d1073e5   caa-cluster-node-0     running   10.242.128.4   158.176.188.76   bx2-2x8   ibm-ubuntu-20-04-3-minimal-amd64-1   caa-cluster-vpc   eu-gb-3   Default   
07a7_ca0fa384-83c5-49bc-b843-5ccd4af06741   caa-cluster-node-1     running   10.242.128.5   158.176.175.94   bx2-2x8   ibm-ubuntu-20-04-3-minimal-amd64-1 …
```
> podvm: Add clang libraries from llvm

- .github/workflows/azure-e2e-test.yml
- .github/workflows/azure-podvm-image-build.yml
- .github/workflows/azure-podvm-image-nightly-build.yml
- ci-infra/azure/main.tf
- ci-infra/azure/outputs.tf
Fixes: #1327
Add workflow to build podvm nightly image for the azure provider and share it with the azure e2e test workflow.
The image gallery has been adjusted to work as community gallery, to be able to consume podvm images.
The podvm build workflow has been moved into a reusable workflow, so we can share the code with the e2e test
Successful test runs for [podvm build](https://github.com/mkulke/cloud-api-adaptor/actions/runs/6046881374/job/16409270080) + [e2e test](https://github.com/mkulke/cloud-api-adaptor/actions/runs/6046604079)
Co-authored-by: Kartik Joshi <kartikjoshi@microsoft.com>
> azure: add workflow to build nightly podvm images

- aws/image/Makefile
- azure/image/Makefile
- ibmcloud-powervs/image/Makefile
- ibmcloud/image/Makefile
- podvm/Makefile
- podvm/Makefile.inc
- vsphere/image/Makefile
Ensure that the included Makefiles can always be found if run from other working directory.
Previously if you were to try to run the podvm make target from other directories it would fail to find Makefile.defaults
> Relative make includes

- Makefile.defaults
On some systems Make would not find the `command` command. As Make tries to avoid launching a new shell for a simple command. The issue is then that `command` is a built-in and does not have an associated executable.
By adding the redirect we force Make to launch the new shell.
> podvm: force Make to use shell with redirect

- entrypoint.sh
- install/overlays/aws/kustomization.yaml
- pkg/adaptor/cloud/aws/manager.go
- pkg/adaptor/cloud/aws/provider.go
- pkg/adaptor/cloud/aws/provider_test.go
- pkg/adaptor/cloud/aws/types.go
This change allows CAA to use the public IP of the pod VM to make a connection to the kata-agent.
The communication between CAA and podVM uses TLS.
Fixes: #1379
> aws: Enable publicIP usage for pod VM

- Dockerfile
- go.mod
- go.sum
- pkg/adaptor/cloud/libvirt/cloudinit.go
- pkg/adaptor/cloud/libvirt/cloudinit_test.go
- pkg/adaptor/cloud/libvirt/image.go
- pkg/adaptor/cloud/libvirt/libvirt.go
- pkg/adaptor/cloud/libvirt/types.go
- pkg/adaptor/cloud/libvirt/volume.go
Fixes #1251
Fixes #1250
This PR uses a native go implementation of an tool to create the cloud init ISO file, removing the dependency on an external tool. It also creates the ISO in-memory. This makes sense because the ISO file is very small and the content is backed in memory anyway. Creating the ISO file in-memory reduces the potential of errors, since nothing has to be written to the file system of the hosting container.
ISO file generation as well as memory based image uploader are backed by unit tests.
> pkg/adaptor/libvirt: cloud init ISO file using native go

- .github/workflows/caa_build_and_push.yaml
- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_on_pull.yaml
- test/e2e/common_suite_test.go
- test/e2e/libvirt_test.go
Two fixes, being the first really important:
* fix checkout on libvirt workflow
* skip libvirt tests only on CI
Cc @ldoktor the last being your suggestion :)
> Libvirt e2e_on_pull workflow fixes

- .github/workflows/build.yaml
- .github/workflows/caa_build_and_push.yaml
- .github/workflows/controllers.yaml
- .github/workflows/csi_wrapper_images.yaml
- .github/workflows/e2e_libvirt.yaml
- .github/workflows/image.yaml
- .github/workflows/lint.yaml
- .github/workflows/podvm_builder.yaml
- .github/workflows/webhook-build.yaml
- .github/workflows/webhook-test.yaml
A bunch of our workflows have hard-coded go version and bumping the value requires "search & replace" of many files. This is error prone. On the other hand, we got the `versions.yaml` that ideally should be the source of truth of external dependencies. Thus, in this PR I changed most workflows that had go version declared on them to read the value from `versions.yaml`
Related to https://github.com/confidential-containers/cloud-api-adaptor/pull/1422#discussion_r1319834023
Note:
* Split in several commits to ease review. As the changes are repetitive I will squash them all before the merge
* I didn't change Azure workflows as I don't know if they should be following `versions.yaml` (FYI @sudharshanibm3)
* Looked at `ibmcloud-powervs/image/prereq.sh` but decided to not touch it because I …
> workflows: read properties from versions.yaml

- .github/workflows/webhook-test.yaml
- webhook/Makefile
- webhook/config/webhook/kustomization.yaml
- webhook/config/webhook/manifests.yaml
- webhook/config/webhook/namespace_selector_patch.yaml
This PR adds verify targets to check if go modules and manifests are up to date. It also adds the check in webhook test workflow.
Fixes: #1347
> webhook: add verify targets

- .github/workflows/azure-podvm-image-build.yml
This commit updates the Azure specific workflows to read the `versions.yaml` file at the root of the repository. Azure workflows were missed in the recent update, where all the workflows were updated to read from the `versions.yaml` file in this PR:
https://github.com/confidential-containers/cloud-api-adaptor/pull/1423.
> azure-ci: Use versions.yaml for Rust, Go & Kata

- pkg/probe/checker.go
- pkg/probe/probe.go
- pkg/probe/probe_test.go
When creating e2e test case for CAA DeamonSet rolling update, I found the test sometimes fails. For a peerpod deployment with 2 replicas, the **AvailableReplicas** may change to zero when CAA DeamonSet rolling update. That means the service based on the deployment will be unavailable when rolling update. It's not as expected.
After investigation, it looks like it's not a good idea to check `pod.Status.Phase` is "Running" to determine if the PeerPod is available or not:
https://github.com/confidential-containers/cloud-api-adaptor/blob/c30eaac2f971229c9059f4a7a935294c8d9f8524/pkg/probe/checker.go#L50C4-L50C4
According to go docs, pod phase **Running** means:
https://pkg.go.dev/k8s.io/api/core/v1#PodPhase
```
// PodRunning means the pod has been bound to a node and all of the containers have …
```
> install: enhance start probe checker conditions

- test/e2e/ibmcloud_test.go
- test/e2e/rolling_update_test.go
initialize a new test TestCaaDaemonsetUpgrade
* Setup: 
* prepare an IKS cluster with 2 workers, and install PeerPod operator  
* create a nginx deployment with 2 replicas, so that there are 2 nginx PeerPods, and each pod for a worker
* create a nginx service based on the deployment, and get the service cluster IP
* create a verify pod to curl the cluster IP every 1 second; the verify pod will exit with error if curl return non-zero result
* Access:
* edit **cloud-api-adaptor-daemonset** to increase `StartupProbe.FailureThreshold`, so that the daemonset will be updated, and the CAA pods on each worker will be recreated
* wait for CAA daemonset updated, and the nginx deployment be available again
* check the status of verify pod, if it's still running. If yes, that means nginx deployment …
> e2e test: add test case for non-disruptive PeerPod upgrade

- volumes/csi-wrapper/examples/ibm/nginx-kata-with-my-pvc-and-csi-wrapper.yaml
Specify Command in yaml
Not sure why the entrypoint in image is not be used. Maybe we need dig into kata agent code for image later.
> volumes: fix the error to create nginx pod for ibm

- .github/workflows/azure-podvm-image-build.yml
The versions parsing is happening in the wrong working directory, [breaking the builds](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/azure-e2e-test.yml).
> azure: fix cwd for versions.yaml parsing

- cmd/process-user-data/main_test.go
- cmd/process-user-data/provision.go
- cmd/process-user-data/test-data/sample-agent-config.toml
- cmd/process-user-data/types.go
- cmd/process-user-data/update.go
- entrypoint.sh
- go.mod
- go.sum
- pkg/adaptor/cloud/aws/manager.go
- pkg/adaptor/cloud/aws/manager_test.go
- pkg/adaptor/cloud/aws/misc.go
- pkg/adaptor/cloud/aws/provider.go
- pkg/adaptor/cloud/aws/types.go
- pkg/adaptor/cloud/aws/types_test.go
- pkg/adaptor/cloud/azure/misc.go
- pkg/adaptor/cloud/cloud.go
- pkg/forwarder/forwarder.go
- pkg/util/cloudinit/cloudconfig.go
This patch series includes the following:
1. Adds support for providing the registry authentication file via userdata. 
2. Removes usage of multiple files via cloud-config. All required values are part of daemon Config which is then processed by process-user-data command inside podvm
3. Adds support for fetching of userdata from metadata service in AWS.
4. Adds some misc improvements and tests to the AWS code
> Handle container registry authentication via userdata

- .github/workflows/azure-podvm-image-build.yml
- Makefile.defaults
fixes #1446 
A kata build process will install yq v3 to `/usr/local/bin`, taking preference over the system-provided yq v4, which we need. The workaround is not particularly pretty, but it's a stopgap to make nighly builds work, until we make the switch to mkosi-based builds. 
- Add a yq version assertion to the Makefiles (a kata build will install v3, but our yq queries require v4)
- Make the yq command overridable
- In the azure podvm build remove the yq v3 installed by kata-agent
```bash
$ yq_v3 --version | sed -nE 's/.* v?([0-9]+).*/\1/p'
3
$ yq --version | sed -nE 's/.* v?([0-9]+).*/\1/p'
4
```
> build: make yq version.yml processing more robust

- entrypoint.sh
- install/overlays/ibmcloud-powervs/kustomization.yaml
- pkg/adaptor/cloud/ibmcloud-powervs/manager.go
- pkg/adaptor/cloud/ibmcloud-powervs/provider.go
- pkg/adaptor/cloud/ibmcloud-powervs/types.go
Adds support to use public IP to connect to the agent-protocol-forwarder running in the peer pod VM.
Fixes: #1461
> powervs: use public IP to connect to the peer pod vm

- .github/workflows/azure-podvm-image-build.yml
We probably want to have `cc_kbc` (being able to talk to kbs) in the nightly images instead of `offlinefs_kbc`, which is the default. it's not trivial to have a build that supports that feature, so it would be good to have it baked into the image
> azure: build podvm with cc_kbc by default

- test/e2e/rolling_update_test.go
Do not print the whole Status object
> e2e/test: reduce the output of TestCaaDaemonsetRollingUpdate

- .github/workflows/azure-podvm-image-build.yml
We weren't including the new CDH binaries in the aszure PodVM image build yet. They probably don't work yet as intended, but the systemd state will be degraded without those binaries.
> azure: add CDH binaries to podvm build

- ibmcloud-powervs/image/prereq.sh
Fix the attestation-agent build by installing perl packages as one of the dependencies.
Fixes: #1468
> podvm: fix attestation-agent build on ppc64le

- .github/workflows/azure-e2e-test.yml
This allows to pass a prebuilt caa container image to the test.
> e2e: allow prebuilt caa image in Azure test

- podvm/files/etc/systemd/system/api-server-rest.service
- podvm/files/etc/systemd/system/confidential-data-hub.service
There is a race condition in the current code flow that is starting the CDH binaries. The `api-server-rest` unit will fail after 5 unsuccessful restart attempts ultimately. This is because it's relying on a unix sockets provided by `attestation-agent` and `confidential-data-hub`:
The sockets aren't created socket immediately, but the units are already active. `api-server-rest`, being a small app, fails to detect the necessary socket and restarts 5 times in quick succession. (the same applies to `confidential-data-hub` (dependent on the aa socket), but it, being a larger app and having only 1 socket doesn't fail as quickly, so it'll only have 2 restarts, before it's able to use the AA the socket.
The easiest fix is to add a delay between the restarts to `api-server-rest`, after 2 restarts …
> podvm: fix CDH's api-server-rest startup

- test/e2e/aws_test.go
- test/provisioner/provision_aws.go
This is a continuation of  https://github.com/confidential-containers/cloud-api-adaptor/pull/1370
--
Implemented the CloudAssert interface for AWS.
The following tests are enabled and passing:
TestAwsCreateSimplePod
TestAwsCreatePeerPodWithJob
TestAwsCreatePeerPodAndCheckUserLogs
TestAwsCreatePeerPodAndCheckWorkDirLogs
TestAwsCreatePeerPodAndCheckEnvVariableLogsWithImageOnly
TestAwsCreatePeerPodAndCheckEnvVariableLogsWithDeploymentOnly
TestAwsCreatePeerPodAndCheckEnvVariableLogsWithImageAndDeployment
TestAwsCreatePeerPodWithLargeImage
TestAwsDeletePod
Those two are not passing, so kept them disabled:
TestAwsCreatePodWithConfigMap
TestAwsCreatePodWithSecret
TestAwsCreatePeerPodContainerWithExternalIPAccess
And finally the following tests seem more complex and might require changes, so I …
> test/e2e: enable tests for AWS

- .github/workflows/azure-podvm-image-build.yml
Use repository vars instead of hardcoded values. This makes it easier to test in an alternate CI setup created on private Azure accounts.
> azure-podvm-image-build: Use repository vars

- .github/workflows/azure-e2e-test.yml
- test/e2e/azure_test.go
- test/provisioner/provision_azure.go
- test/provisioner/provision_azure_cli_auth.properties
- test/provisioner/provision_azure_initializer.go
I've thrown those in a single PR, mostly because it's friday. We can untangle, if desired, ofc.
- Remove option to pass secrets to test run
since leakage of secrets in the CI is a risk and federated credentials work well on github actions we remove the option to pass a CLIENT_SECRET to a test run. Local runs can keep using cli auth.
- Parallize the tests
it will speed up a test run and is a valid test path. there are no dependencies between the test cases, so flakes due to this would imply a bug we want to be aware of.
Later, when we add more tests, we probably want to increase the parallelism when invoking go test, since it'll use nproc by default but the tests are not cpu-bound.
- There is a misnomer in the ssh key parameter.
- There is no need to query the API for the rg name in the …
> test: misc enhancements to the azure e2e test code

- versions.yaml
Since confidential-containers/guest-components/pull/371 has been merged, we need to update guest components in the podvm. Otherwise remote attestation via cc_kbc will not work for peer pods.
> podvm: bump guest-components version

- test/e2e/common_suite_test.go
This ensures that all the pods are deleted before we move on to clean up CAA and other resources.
Fixes: #1480
> e2e-tests: Add a default deletion time for all tests

- azure/build-image.md
Right now we don't specify any KBC for the Azure's PodVM. So defaulting to the Azure SNP vTPM KBC will allow users to utilize the attestation features provided on the Azure CVM.
> azure-build-pod-vm-image: Default to SNP vTPM KBC

- test/e2e/common.go
- test/e2e/ibmcloud_test.go
- test/e2e/rolling_update_test.go
We have test case `TestCaaDaemonsetRollingUpdate` to test CAA DS rolling update feature. We need enhance this test to also verify if **peerpod-ctrl** can work as expected to delete old Pod VMs caused by rolling update after peer pod deleted.
Just for ibmcloud provider so far
> e2e/test: enhance TestCaaDaemonsetRollingUpdate

- .github/workflows/peerpodconfig-ctrl_image.yaml
- .github/workflows/webhook-build.yaml
- .github/workflows/webhook-test.yaml
- peerpodconfig-ctrl/Makefile
- peerpodconfig-ctrl/config/manager/kustomization.yaml
- peerpodconfig-ctrl/config/rbac/role.yaml
- peerpodconfig-ctrl/controllers/peerpodconfig_controller.go
- webhook/Makefile
- webhook/config/manager/kustomization.yaml
This series includes misc fixes for webhook and peerpodconfig-ctrl
1. Updates the Makefile and kustomization.yaml to use the default images. This makes it easy to deploy these controllers via simple `make -C <dir> <target>` invocation
2. Create a gh-action job to build and push peerpodconfig-ctrl image to quay.io
3. Adds missing daemonset related rbac rules for peerpodconfig-ctrl
4. Fix the webhook gh-action jobs to point to the correct location for versions.yaml
> Misc controller fixes

- docs/Release-Process.md
Closes #1254
I've rebased Wainer's PR, resolved the conflicts and added the only outstanding change I requested in https://github.com/confidential-containers/cloud-api-adaptor/pull/1254#issuecomment-1659840822, so we can get this merged before the next release.
> Release process document improvements

- peerpod-ctrl/controllers/peerpod_controller.go
- test/e2e/rolling_update_test.go
For Create and Update events without DeletionTimestamp,
check if there is old PeerPod object owned by the same Pod,
and delete it to clean the dangling Pod VM
Fixes #1510
> peerpod-ctrl: check and clean old PeerPod objects 

- test/e2e/ibmcloud_test.go
- test/e2e/rolling_update_test.go
* replace nginx image with python image, because it's not stable to create a peerpod with nginx image (#1450)
* wait for CAA DaemonSet updated before assess
* refine "VerifyOldVmDeleted", if old instance exists, check if status is "deleting"
> e2e/test: improve TestCaaDaemonsetRollingUpdate

- test/e2e/rolling_update_test.go
Use "quay.io/curl/curl:latest" that supports multi-arch images: https://quay.io/repository/curl/curl?tab=tags
> e2e/test: Use multi-arch images in quay for update test

- .github/workflows/azure-e2e-test.yml
Use versions.yaml to read go version in e2e test
Fixes: #1496
> Azure: Use versions.yaml to read go version in e2e test

- test/e2e/assessment_runner_test.go
- test/e2e/common_suite_test.go
- Included possible failure messages for PodVMwithAnnotationsLargerCPU_test case
- Enabled deletion condition of pods for avoiding failures in nightly jenkins run
Fixes: #1161
> ibmcloud: Fix instance test case failures

- Dockerfile
- Makefile
- hack/build.sh
After the changes in #1448 the root Makefile now references Makefile.defaults, this file and the yq binary need to be included for the build
> caa: Fix missing defaults and yq in image build

- Dockerfile
As we are using emulation for the build step (sorry I didn't notice this before), because of requiring CGO, we need to build yq for each arch instead of using upstream releases.
> caa: install yq from source for crossarch builds

- Dockerfile
Save some computation by using cross-compiliation vs. emulation when we don't need CGO.
Testing building s390x release/dev image (exact timings don't matter but shows clear improvement).
```
RELEASE_BUILD=true ARCHES="linux/s390x" make image-with-arch 
=> [builder 9/9] RUN CC=gcc make ARCH=s390x COMMIT=dcb7b651d6f7b5f348c3930dcc28dd52c248  32.7s
RELEASE_BUILD=false ARCHES="linux/s390x" make image-with-arch 
=> [builder 9/9] RUN CC=gcc make ARCH=s390x COMMIT=dcb7b651d6f7b5f348c3930dcc28dd52c24  380.4s
```
Roughly 10x improvement for the release image vs dev image.
> caa: cross-compile for release images

- aws/raw-to-ami.sh
- pkg/adaptor/cloud/aws/manager.go
- pkg/adaptor/cloud/aws/manager_test.go
1. Add uefi support when registering AMI created from raw image. This is tested with mkosi fedora image
2. Adjust disable-cvm option to align with other providers
> Misc CVM fixes for AWS

- test/e2e/assessment_helpers_test.go
- test/e2e/assessment_runner_test.go
- test/e2e/common.go
- test/e2e/common_suite_test.go
- Add io.containerd.cri.runtime-handler annotation
to pods and jobs, so that the nydus-snapshotter can be picked
up by containerd if configured
- Add a new function to check the CAA logs
for messages to indicate if nydus-snapshotter
was used to pull the image in the peer pod
Note: this only enables things for the simple pod test, we might want to roll it out to all of the tests?
> Add nydus-snapshotter enablement and verification

- docs/Release-Process.md
- go.mod
- go.sum
- peerpod-ctrl/go.mod
- peerpod-ctrl/go.sum
- versions.yaml
- volumes/csi-wrapper/go.mod
- volumes/csi-wrapper/go.sum
Beginning the [release candidate testing](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#release-candidate-testing) phase for the release 0.8.0.
* Updated kata-containers/runtime to commit 424de1cbfa4e1da9ecf9a56b1d1e1a11a4f339cd which is the actual payload reference on CoCo's operator.
* Updated guest-components to commit 615a46ff16ee8670014946d14e44e85cede82f01 (same commit pinned on kata's 424de1cbfa4e1da9ecf9a56b1d1e1a11a4f339cd)
> Release 0.8.0-rc1 - update dependencies

- .github/workflows/podvm.yaml
- .github/workflows/podvm_binaries.yaml
- .github/workflows/podvm_builder.yaml
- Makefile
- podvm/Dockerfile.podvm.centos
- podvm/Dockerfile.podvm.rhel
- podvm/Makefile.inc
I've run tests for creating the builders using act.
Still running through the rest but it is a slow process. 
- Using the make targets for the steps, so that is grabs the versions 
- Added back in the cloud-provider specific image builds for the vsphere build
- Minor clean up of the workflow
> Fix workflow podvm builds

- peerpod-ctrl/go.mod
- peerpod-ctrl/go.sum
- volumes/csi-wrapper/go.mod
- volumes/csi-wrapper/go.sum
Update csi-wrapper and peerpod-ctrl to use the v0.8.0-alpha.1 tagged go module following this section:
> Update the csi-wrapper and peerpod-ctrl go modules to use the tagged version of cloud-api-adapter, by running:
> ```
> go get github.com/confidential-containers/cloud-api-adaptor@v<version>-alpha.1
> go mod tidy
> ```
> in their directories and removing the local replace references if we needed to add them earlier.
Of the RC release doc
> V0.8.0 alpha.1 caa tag updates

- .github/workflows/e2e_libvirt.yaml
On commit 662d96b27d02 the workflow changed to get Go from versions.yaml but yq is not installed so it fails.
> tests/e2e_libvirt: install yq

- test/e2e/assessment_helpers_test.go
- test/e2e/assessment_runner_test.go
If a cluster has multiple nodes running then it will also have multiple caa daemon sets running, so we want to check the logs for the correct one.
Get the node name for the pod we are testing and then use it as a check when we identify the CAA pod to get the logs for
> tests/e2e: Handle multi-node cluster

- test/e2e/aws_test.go
- test/e2e/azure_test.go
- test/e2e/common.go
- test/e2e/common_suite_test.go
- test/e2e/ibmcloud_test.go
- test/e2e/libvirt_test.go
- Given that nydus-snapshotter doesn't seem stable, we want to
add a separate test for the nydus snapshotter
so that we can consider skipping it for cloud-providers that aren't
working
- Given that on AKS the runtime-handler annotation seems to cause issues
and the nydus-snapshotter isn't stable, we don't want to add it
to every pod.job anymore
> Add separate nydus-snapshotter test

- test/e2e/README.md
- test/e2e/main_test.go
Cloud API Adaptor is installed everytime when run e2e test. When use existing cluster which has already installed CAA, it may get conflict or error to install CAA again. The PR introduce a environment variable to control the installation of CAA during e2e test.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/1544
> caa e2e: Install Cloud API Adaptor according to environment variable.

- test/e2e/assessment_helpers_test.go
- test/e2e/common_suite_test.go
- Fix the regex matcher and improve error handling
- Switch the nydus test to use alpine over nginx to avoid hitting annotation caching issues reported in: https://github.com/kata-containers/kata-containers/issues/8337
> Nydus test fixes

- install/overlays/aws/kustomization.yaml
- install/overlays/azure/kustomization.yaml
- install/overlays/ibmcloud-powervs/kustomization.yaml
- install/overlays/ibmcloud/kustomization.yaml
- install/overlays/libvirt/kustomization.yaml
- install/overlays/vsphere/kustomization.yaml
Using the
quay.io/repository/confidential-containers/cloud-api-adaptor:d4496d008b65c979a4d24767979a77ed1ba21e76
image.
Fixes #1548
> install: pin cloud-api-adaptor image for v0.8.0

- peerpod-ctrl/go.mod
- peerpod-ctrl/go.sum
- volumes/csi-wrapper/go.mod
- volumes/csi-wrapper/go.sum
Updating the csi-wrapper and peerpod-ctrl to use the CAA v0.8.0 module.
> Post 0.8.0 release - tagging modules

- podvm-mkosi/Makefile
Without providing this option the image will not contain an attestation-agent with cc_kbc support.
> podvm-mkosi: Add option in mkosi build for AA_KBC

- pkg/adaptor/cloud/azure/provider.go
Otherwise the cleanup won't be executed if the context was canceled.
> adaptor/azure: use context.Background for cleanup

- .github/workflows/azure-e2e-test.yml
- test/tools/provisioner-cli/main.go
The test itself will perform an installation of the operator/CAA on the cluster as a [setup step](https://github.com/confidential-containers/cloud-api-adaptor/blob/b18675f52f54ad7d8eae72ce7a6668be81329c11/test/e2e/main_test.go#L120), so installing it twice is redundant.
The installation should be idempotent, but having 2 places performing the installation is probably suboptimal and might lead to undesired effects if different provisioner config files are used. If we want to test whether a re-installation works, we should have a dedicated test for that.
I would opt for removing the CAA installation from the `provision` action, but a `createcluster` action might be a good middle ground.
> test: Add createcluster action to provisioner cli

- install/overlays/azure/kustomization.yaml
- pkg/adaptor/cloud/aws/manager.go
- pkg/adaptor/cloud/azure/manager.go
and setting default CVM type for Azure
setting using env fixes peerpod-ctrl error:
`The following supplied instance types do not exist: []`
> azure: aws: set defaults from environment to instanceTypes 

- peerpod-ctrl/go.mod
- peerpod-ctrl/go.sum
to include latest fixes
related to: https://github.com/confidential-containers/cloud-api-adaptor/pull/1582
> peerpod-ctrl: bump cloud-api-adaptor

- podvm-mkosi/README.md
- podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-debug.conf
- podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora.conf
- podvm-mkosi/mkosi.skeleton/etc/systemd/system/process-user-data.service.d/10-override.conf
- podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system-preset/20-coco-sys.preset
- podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/afterburn-checkin.service.d/10-override.conf
This is based on #1524, which should be reviewed and merged first.
Fixes #1467 (for x86, we should check with the IBM folks if they want to remove cloud init for s390x as well)
This requires `DISABLE_CLOUD_CONFIG=true` in your `install/overlay/${CSP}/kustomization.yaml`
> podvm-mkosi: remove cloud-init

- podvm/hack/download-image.sh
- We only publish the podvm containing container images as amd64 arch images, but as @tumberino has pointed out it doesn't contain any executable code, so when downloading it, we can just force the platform to be amd64.
> podvm: Enable download-image on multi-arch

- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_on_pull.yaml
- .github/workflows/podvm.yaml
- .github/workflows/podvm_binaries.yaml
- .github/workflows/podvm_builder.yaml
- .github/workflows/podvm_publish.yaml
- Makefile
The [libvirt e2e workflow on pull request](https://github.com/confidential-containers/cloud-api-adaptor/actions/workflows/e2e_on_pull.yaml) currently does not create a podvm, instead it uses the pre-built images. We have two problems here: 1) podvm built images are usually old and outdated; 2) not building on pull request means changes on podvm aren't tested on CI.
By the time I introduced the libvirt e2e workflow in PR #1318, @stevenhorsman mentioned on Slack that it would be better to build the podvm too. I agreed, and despite its build takes a lot of time to complete, then I am sending these changes to exactly enable podvm build alongside the libvirt e2e workflow.
Currently the [podvm_builder](https://github.com/confidential-containers/cloud-api-adaptor/tree/main/.github/workflows/podvm …
> Refactor podvm workflows and enable on libvirt e2e

- .github/workflows/daily-e2e-tests-ibmcloud.yaml
- show e2e-test result for libvirt cloud_provider base on self-managed amd64 cluster base libvirt
- only push images when it not in registry
fixes: #1588
> e2e: daily libvirt e2e-test with podvm-generic-ubuntu-amd64 podvm image

- ibmcloud/cluster/README.md
- ibmcloud/cluster/main.tf
- ibmcloud/cluster/outputs.tf
- ibmcloud/cluster/variables.tf
Current IBM Cloud terraform to create self-managed cluster will always create new VPC and subnet for VSIs.
As a result, it's easy to see vpc quota exceeded errors because by default only 10 VPCs could be created in a region under an account.
In this PR, we introduced 2 new variables to specify existing VPC and subnet names. If they are set, will create VSIs in existing VPC; otherwise, will create new VPC and subnet as usual
> terraform: add new variables for existing VPC and subnet

- .github/workflows/e2e_on_pull.yaml
- .github/workflows/podvm.yaml
- .github/workflows/podvm_binaries.yaml
- .github/workflows/podvm_builder.yaml
- .github/workflows/podvm_publish.yaml
As currently implemented on builder/binaries/podvm workflows, the actions/checkout@v3 will checkout the code based on GITHUB_SHA. When used with the pull_request_target event (which is the case of the tests for libvirt on pull request), GITHUB_SHA is the SHA of the base branch but we are interested on the SHA of the head on the pull request branch (i.e. github.event.pull_request.head.sha).
> workflows: fix checkout of the code on podvm

- .github/workflows/e2e_libvirt.yaml
- libvirt/kcli_cluster.sh
Ubuntu 22.04 packages containerd 1.7 that is the mininum required version as of CoCo 0.8.0. Updated the libvirt/kcli_cluster.sh to install Ubuntu 22.04 instead of 20.04.
There is needed to use a kcli version newer than the build of today (2023/11/21) that contains the fix to [1].
[1] https://github.com/karmab/kcli/issues/619
Fixes #1593
> libvirt/kcli: defaults to Ubuntu 22.04

- Makefile.defaults
- podvm/Dockerfile.podvm_builder.rhel
- versions.yaml
This PR updates the podvm/Dockerfile.podvm_binaries.rhel and podvm/Dockerfile.podvm_builder.rhel to enable building a rhel based peer pod VM image qcow2 image for s390x. Packer binary is conditionally built from source s390x. The PR also allows building the Builder image either on a subscribed or an unsubscribed rhel host.
Signed-off-by: Obed Tetteh <obed.tetteh@ibm.com>
> podvm: build rhel peer pod VM qcow2 image for s390x

- .github/workflows/daily-e2e-tests-ibmcloud.yaml
- .github/workflows/e2e_libvirt.yaml
- libvirt/README.md
- libvirt/config_libvirt.sh
- libvirt/kcli_cluster.sh
fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/1598
- create s390x cluster with libvirt
- show e2e-test result for s390x libvirt cluster
> libvirt: support s390x cluster

- .github/workflows/azure-e2e-test.yml
- Do not overwrite image_id in e2e test when specified, at the moment it will be ignored
- Add cluster subnet id to provisioner file to we can decouple running tests from cluster installation
> azure: Misc e2e fixes

- test/e2e/assessment_runner_test.go
- test/e2e/common_suite_test.go
- test/provisioner/provision.go
- fix the e2e-test cases around Annotations for ibmcloud provider
- remove useless withCustomPodState(v1.PodRunning), as by [default all new testcases are with PodRunning status](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/test/e2e/assessment_helpers_test.go#L51).
fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/1613
> e2e-test: fix one e2e-test bug

- podvm/Dockerfile.podvm_builder
- pined the pakcer version to 1.9.4-1 which still in MPL license, and with this old version podvm image build with packer work as expected.
fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/1616
> podvm: fix podvm packer image build

- .github/workflows/e2e_libvirt.yaml
Docker is required to pull and extract the podvm qcow2.
I hope it fixes the problem on https://github.com/confidential-containers/cloud-api-adaptor/pull/1617
> WIP: workflows: install docker in e2e_libvirt

- Dockerfile
- Now we are using fedora 38 and golang 1.20.12, bump the builder base image to pick these up
> version: Bump Builder base

- test/e2e/libvirt_test.go
Add delete pod test to libvirt e2e as part of #1604 libvirt gap closes
> test/e22: libvirt: Add delete pod test

- .github/workflows/caa_build_and_push.yaml
- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_run_all.yaml
- .github/workflows/podvm.yaml
- .github/workflows/podvm_binaries.yaml
- .github/workflows/podvm_builder.yaml
- hack/ci-helper.sh
The e2e_on_pull workflow run on pull_request_target event that uses the the merge branch. Unlike the pull_request event, the merge branch is not rebased on top of the target branch (usually 'main'). In simple terms, the e2e_on_pull workflow does not automatically rebase the code so that changes merged on 'main' after the pull request creation are disregarded.
This added a renamed (to ci-helper.sh) and modified version of https://github.com/kata-containers/kata-containers/blob/main/tests/git-helper.sh that's called after 'actions/checkout' step to rebase the code atop of 'main'.
Because the touched workflows may be called on different workflows and events (e.g. release and dispatch_workflow), the rebase step is guarded by `if: github.event_name == 'pull_request_target'` to only run on …
> workflows: rebase code on pull_request_target

- test/e2e/assessment_helpers_test.go
- test/e2e/assessment_runner_test.go
when testing in parallel, just listening for the last log won't work, we'll get matches for unrelated peerpod log lines.
> e2e-test: grep for container id in nydus test

- aws/image/Makefile
- aws/image/rhel/aws-rhel.pkr.hcl
- aws/image/rhel/variables.pkr.hcl
- aws/image/ubuntu/aws-ubuntu.pkr.hcl
- aws/image/ubuntu/variables.pkr.hcl
- azure/image/Makefile
- azure/image/rhel/azure-rhel.pkr.hcl
- azure/image/rhel/variables.pkr.hcl
- azure/image/ubuntu/azure-ubuntu.pkr.hcl
- azure/image/ubuntu/variables.pkr.hcl
- podvm/addons/README.md
- podvm/addons/nvidia_gpu/README.md
- podvm/addons/nvidia_gpu/setup.sh
- podvm/addons/setup_addons.sh
This commit enables NVIDIA gpu support for aws and azure podvm image. For example enabling gpus etc.
NVIDIA GPU support is enabled by default when building packer based
image for aws and azure
A default build of podvm in aws took 10 min
```
==> Wait completed after 10 minutes 16 seconds
==> Builds finished. The artifacts of successful builds are:
--> peer-pod-ubuntu.amazon-ebs.ubuntu: AMIs were created:
us-east-2: ami-0463ae5aa8d5b3606
rm -fr toupload
real    10m34.352s
user    0m18.919s
sys     0m10.044s
```
If you want to disable, then run with ENABLE_NVIDIA_GPU=no
For example:
cd azure/image
PODVM_DISTRO=ubuntu ENABLE_NVIDIA_GPU=no make image
Few additional work is required going forward which I plan to handle in subsequent PRs.
1. Add gpu verification test case
2. Add gpu support in …
> packer: Enable support for adding nvidia gpu to podvm image

- test/e2e/README.md
Adding instruction on how tests can be triggered against an existing deployment of CAA. This is useful for debugging tests and testing local changes.
> docs: Add docs for e2e tests on CAA deployment

- aws/README.md
- aws/image/rhel/aws-rhel.pkr.hcl
- aws/image/rhel/variables.pkr.hcl
- aws/image/ubuntu/aws-ubuntu.pkr.hcl
- aws/image/ubuntu/variables.pkr.hcl
- azure/image/rhel/azure-rhel.pkr.hcl
- azure/image/rhel/variables.pkr.hcl
- azure/image/ubuntu/azure-ubuntu.pkr.hcl
- azure/image/ubuntu/variables.pkr.hcl
- entrypoint.sh
- ibmcloud-powervs/README.md
- ibmcloud-powervs/image/Makefile
- ibmcloud-powervs/image/copy-files.sh
- install/overlays/aws/kustomization.yaml
- install/overlays/azure/kustomization.yaml
- install/overlays/ibmcloud-powervs/kustomization.yaml
- podvm/files/etc/systemd/system/agent-protocol-forwarder.service
- podvm/qcow2/misc-settings.sh
By default the port is 15150, this adds the support to customize it to a specific port. Currently changes added for AWS, Azure and IBM Cloud PowerVS providers.
Fixes: #1457
> forwarder: customize the listener port

- cmd/process-user-data/types.go
- podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/kata-agent.service.d/10-override.conf
- podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/process-user-data.service.d/10-override.conf
- podvm/files/etc/systemd/system/kata-agent.service
The ./podvm kata-agent unit has been set to use a config file in /etc. Having the kata-agent config file in /run will break the CAA libvirt tests, since we have dependencies that rely on the config being in /etc. ./podvm-mkosi will override this path to a configuration in /run.
Tested w/ PodVM images built w/ packer + mkosi
> podvm: revert agent-config path to /etc

- pkg/adaptor/cloud/aws/manager.go
- pkg/adaptor/cloud/azure/manager.go
- pkg/adaptor/cloud/ibmcloud-powervs/manager.go
- pkg/adaptor/cloud/ibmcloud/manager.go
- pkg/adaptor/cloud/libvirt/manager.go
- pkg/adaptor/cloud/vsphere/manager.go
- Add new GetConfig function
Fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/1628
> provider: make existing provider managers can be reused

- pkg/podnetwork/podnetwork_test.go
- pkg/util/netops/netops.go
Fixes #1630
The problem is `r.Destination.Bits()` may return different results if building with different Go versions 
`r.Destination.Bits()` return 0 for go1.20.5, but return -1 for go1.21.1
I tried to change the condition to `!r.Destination.IsValid()` because it returns consistent results.
The code of `IsValid()` for go1.20.5:
```
// IsValid reports whether p.Bits() has a valid range for p.Addr().
// If p.Addr() is the zero Addr, IsValid returns false.
// Note that if p is the zero Prefix, then p.IsValid() == false.
func (p Prefix) IsValid() bool { return !p.ip.isZero() && p.bits >= 0 && int(p.bits) <= p.ip.BitLen() }
```
The code of `IsValid()` for go1.21.1:
```
func (p Prefix) IsValid() bool { return p.bitsPlusOne > 0 }
func PrefixFrom(ip Addr, bits int) Prefix {
var bitsPlusOne uint8 …
```
> forwarder: update the condition for default route

- .github/workflows/azure-e2e-test.yml
The community gallery and image definition are supposed to be stored as vars not as secret, reference is usage in the nightly image build.
https://github.com/confidential-containers/cloud-api-adaptor/blob/afe662c4b09f63168e8dae594e67c48871d96c3c/.github/workflows/azure-podvm-image-build.yml#L29-L31
> azure: fix image reference string

- aws/README.md
- install/overlays/aws/.gitignore
- install/overlays/aws/kustomization.yaml
This series provides the following
1. Update instructions for AWS
2. Use env file for secrets (similar to Azure)
> Update AWS setup instructions

- test/e2e/assessment_runner_test.go
- test/e2e/aws_test.go
- test/e2e/azure_test.go
- test/e2e/common.go
- test/e2e/common_suite_test.go
- test/e2e/ibmcloud_test.go
- test/e2e/libvirt_test.go
- test/e2e/nginx_deployment_test.go
- image layer order issue is fixed by https://github.com/confidential-containers/cloud-api-adaptor/pull/1632, thanks @mkulke 
- change to check container status for pod with running and testcommands. 
- keep simplepod test using nginx
- use busybox to reduce e2e-test execution time
- add a new doTestNginxDeployement test case
part of https://github.com/confidential-containers/cloud-api-adaptor/issues/1450
> e2e: use busybox to reduce e2e-test execution time

- test/e2e/assessment_helpers_test.go
- test/e2e/assessment_runner_test.go
- test/e2e/common.go
- test/e2e/common_suite_test.go
- test/e2e/ibmcloud_test.go
- test/e2e/libvirt_test.go
Enable test framework to support more than one pod in one test case
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/16
> e2e: enable more than one pod in one test case

- Makefile
- test/provisioner/provision.go
- pin operator manager to use release v0.8.0 tag
From last Saturday, the opensource e2e test pipelines are failed with error:
```
[2024-01-06T00:22:04.027Z] confidential-containers-system   cc-operator-daemon-install-jptsh                          0/1     Error              4 (65s ago)   3m12s
``` 
eg: https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/7429572885/job/20218312686#step:5:1827
Did a dig found that log from the `cc-operator-daemon-install` looks like:
```
kubectl logs -f -n confidential-containers-system   cc-operator-daemon-install-88f4z
/opt/kata-artifacts/scripts/kata-deploy.sh: line 417: SNAPSHOTTER: unbound variable
Environment variables passed to this script
* NODE_NAME: peer-pods-worker-0
* DEBUG: false
* SHIMS: remote
* DEFAULT_SHIM:
* …
```
> e2e-test: fix e2e-test pipelines

- test/e2e/assessment_helpers.go
- test/e2e/common_suite.go
- test/e2e/main_test.go
- test/e2e/nginx_deployment.go
- test/e2e/rolling_update.go
- Currently we are run e2e-test cases under a  namespace defined by
```
namespace := envconf.RandomName("default", 7)
```
The way that
[envconf.RandomName](https://pkg.go.dev/sigs.k8s.io/e2e-framework/pkg/envconf#RandomName) works is to add random name after the prefix, up to the specified length. As default is 7 chars long then envconf.RandomName("default", 7) will just return `default`.
- This means that we have a lot of duplicated code in each test case that does nothing, so we should resolved this.
- It's also a good idea to have a single namespace for testing anyway, like we;ve done in kata-containers,  as in case things fail and go wrong it's easier to clean up by deleting the namespace, though obviously `default` shouldn't be that namespace here.
- This PR adds a new e2e-test …
> test/e2e: Switch tests away from default namespace

- peerpod-ctrl/Makefile
When I tried to build peerpod-ctrl image locally with command `make docker-buildx`, it failed:
```
docker buildx build --push --platform=linux/arm64,linux/amd64,linux/s390x,linux/ppc64le --tag quay.io/cdlleili/peerpod-ctrl:latest -f Dockerfile.cross
ERROR: "docker buildx build" requires exactly 1 argument.
```
So I tried to fix it:
* `--platform=$TARGETPLATFORM` has been set in Dockerfile, so we don't need to insert `--platform=${BUILDPLATFORM}` for cross-platform support
* add 2 build args
* add `.` as the latest argument
> peerpod-ctrl: fix Make command docker-buildx

- podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/kata-agent.service.d/10-override.conf
- versions.yaml
fixes: #1637
~blocked-by: https://github.com/confidential-containers/guest-components/pull/429~
On a podvm using an guest-components build from the PR, `KATA_AGENT_CONFIG_PATH` is set and picked up by attestation-agent and cdh:
```bash
$ cat /proc/$(pgrep -i attest)/environ | xargs --null echo
LANG=C.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin SYSTEMD_SULOGIN_FORCE=1 INVOCATION_ID=ad04b8c4ff6c4f2c8617dfcfed24c183 JOURNAL_STREAM=8:3090 SYSTEMD_EXEC_PID=552 KATA_AGENT_CONFIG_PATH=/run/peerpod/agent-config.toml RUST_BACKTRACE=full OCICRYPT_KEYPROVIDER_CONFIG=/tmp/ocicrypt_config.json
```
Verified w/ a kbs deployment that the mkosi-podvm performs a remote attestation.
Once this is the guest-components PR is merged, we need to bump its revision in `versions.yaml`
> podvm-mkosi: override kata-agent config path

- aws/image/rhel/aws-rhel.pkr.hcl
- aws/image/ubuntu/aws-ubuntu.pkr.hcl
- azure/image/rhel/azure-rhel.pkr.hcl
- azure/image/ubuntu/azure-ubuntu.pkr.hcl
- cmd/process-user-data/main.go
- cmd/process-user-data/main_test.go
- cmd/process-user-data/provision.go
- cmd/process-user-data/types.go
- cmd/process-user-data/update.go
- entrypoint.sh
- install/overlays/azure/kustomization.yaml
- pkg/adaptor/cloud/aws/manager.go
- pkg/adaptor/cloud/aws/misc.go
- pkg/adaptor/cloud/aws/provider.go
- pkg/adaptor/cloud/aws/types.go
- pkg/adaptor/cloud/azure/manager.go
- pkg/adaptor/cloud/azure/misc.go
- pkg/adaptor/cloud/azure/provider.go
- pkg/adaptor/cloud/azure/types.go
- podvm-mkosi/README.md
fixes #1639 
The process-user-data tool is processing cloud-config data now instead of a raw daemon config json file. The latter required setting a parameter on the DaemonSet configuration, depending on whether a PodVM image has been built w/ cloud-config disabled or not.
The support is limited to the `write_files` directive and a subset of properties, specifically `path` and `content`, as those are set by the cloud provider code. Parsing will fail if additional properties are encountered.
In theory provider code can set additional properties, but atm we don't. (we might consider removing the unused props in the cloudconfig code, to avoid confusion)
All `write_files` entries but the one with `path: $daemonConfigPath` will be ignored.
In the CAA code the `DISABLE_CLOUD_CONFIG` flag has …
> process-user-data: process cloud-config yamls

- install/README.md
This ensures users and developers always access the most up-to-date instructions, which is already documented at the CoCo level, eliminating the risk of outdated or duplicated content in our documentation.
> docs: update docs to point to CoCo instructions

- test/e2e/assessment_helpers.go
In testing I saw that the default ServiceAccount for the newly created namespace wasn't always available straight away, especially as the cluster gets more namespaces in.
To try and fix this I've added a new waitForNamespaceToBeUseable method and done a poll in there every 5 seconds to check if the 'default' serviceAccount is in the namespace yet
Fixes: #1657
> test/e2e: Add wait for namespace service account

- pkg/util/tlsutil/certgen.go
- test/e2e/assessment_runner.go
- test/e2e/common.go
- test/e2e/common_suite.go
- test/e2e/ibmcloud_test.go
- test/e2e/libvirt_test.go
Export secure port and extra secret for pods' secure communication
fix: https://github.com/confidential-containers/cloud-api-adaptor/issues/1658
> e2e: Add support for pods' secure communication

- aws/README.md
Add missing space that prevents command from being pasted verbatim in shell
> aws: minor doc update

- cmd/process-user-data/provision.go
The azure logic has been used in the AWS branch.
> process-user-data: use aws endpoint on aws

- Makefile
- install/README.md
- test/provisioner/provision.go
The default value of RESOURCE_CTRL is set to true to allow deletion of dangling resources.
> install: Deploy peerpod-ctrl by default

- entrypoint.sh
Remove redundant `-aws-region` argument.
This arg is processed in the code:
https://github.com/confidential-containers/cloud-api-adaptor/blob/e7bf868a7d2ffcc59c38ed57a5fa2e346cbda4e9/entrypoint.sh#L48
This argument is (also) passed with an empty value if `AWS_REGION` is not specified.
> aws: remove redundant aws-region flag on cloud-api-adaptor invocation

- libvirt/config_libvirt.sh
Sorry, I missed it in my test of the PR yesterday as I already had `yq` installed, but the ordering is incorrect now:
Move the `REQUIRED_GO_VERSION` fetch below the check for whether yq is installed
> libvirt: Fix config_libvirt script

- podvm/README.md
Add YQ_VERSION in `--build-arg`
to resolve the issue below:
```
$ docker build -t podvm_builder \
--build-arg CAA_SRC=https://github.com/huoqifeng/cloud-api-adaptor \
--build-arg CAA_SRC_REF=fedora-s390x-build \
--build-arg GO_VERSION=1.20.12 \
--build-arg PROTOC_VERSION=3.11.4 \
--build-arg RUST_VERSION=1.72.0 \
--build-arg KATA_SRC=https://github.com/kata-containers/kata-containers   \
-f Dockerfile.podvm_builder .
[+] Building 0.6s (11/20)                                                                                                                                                       docker:default
=> [internal] load .dockerignore …
```
> doc: Update README.md add YQ_VERSION

- podvm-mkosi/Makefile
- podvm/Dockerfile.podvm_binaries.fedora
- podvm/Dockerfile.podvm_builder.fedora
- podvm/Makefile.inc
Fixes: #1640
As a 1st step to enable mkosi images on s390x on fedora, we'll enable s390x binaries build on fedora with same Dockerfile on a s390x host in this PR.
There are other options to build s390x binaries on fedora like:
- Build the s390x binaries on x86 host and s390x container
- Build the s390x binaries on x86 host and x86 container with compilers cross platform 
But it looks not easy, as we tried, both of the other 2 options failed. We'll track and maybe switch the approach in further PR as investigation move ahead.
In this PR, the fedora Dockerfile is revised following same format as ubuntu. It'll be more easier to maintain the Dockerfile.
To try the changes:
- on s390x
To run the builder build:
```
docker buildx build \
-t fedora-binaries-builder-s390x \
--build-arg ARCH=s390x …
```
> s390x: build fedora binaries for peerpod

- test/e2e/assessment_helpers.go
- test/e2e/assessment_runner.go
- test/e2e/common.go
- test/e2e/common_suite.go
- test/provisioner/ibmcloud/provision_kustomize.go
- add ImagePullSecret to default ServiceAccount
- make PodVM with Authenticated Registry cases can be reused by other cloud providers
- support given Authenticated Registry
Fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/1680
> e2e: update PodVM with Authenticated Registry cases

- aws/README.md
- entrypoint.sh
- install/overlays/aws/kustomization.yaml
- pkg/adaptor/cloud/aws/manager.go
- pkg/adaptor/cloud/aws/manager_test.go
- pkg/adaptor/cloud/aws/provider.go
- pkg/userdata/provision.go
1. The provisioning command used a wrong ordering of daemonconfig and authJson files, resulting in startup errors for process-user-data
2. Change AWS default instance type to CVM to align with the default  disable-cvm option
3. Fix handling of describeimages
> Misc fixes

- .github/workflows/podvm_mkosi_image.yaml
Fixes: #1640 
The code has been tested in personal repo via GHA: https://github.com/huoqifeng/cloud-api-adaptor/actions/runs/7811452618
> s390x: add s390x runner to build fedora binaries

- test/e2e/assessment_helpers.go
- test/e2e/assessment_runner.go
- test/e2e/aws_common.go
- test/e2e/azure_common.go
- test/e2e/common.go
- test/e2e/common_suite.go
- test/e2e/ibmcloud_common.go
- test/e2e/libvirt_common.go
fixes #1704
The Azure tests will not reliably pass the deletion tests within 60s. Added a per-cloudprovider default setting and made the deletionWithin param mandatory for the TestCase struct.
> e2e-test: default delete timeout per cloudprovider

- test/e2e/libvirt_common.go
fixes #1701
The libvirt go modules require a local installation of libvirt, without it will fail to run:
```bash
go test -c -tags=notlibvirt ./test/e2e
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lvirt-lxc
/usr/bin/ld: cannot find -lvirt-lxc
/usr/bin/ld: cannot find -lvirt-qemu
/usr/bin/ld: cannot find -lvirt-qemu
/usr/bin/ld: cannot find -lvirt
collect2: error: ld returned 1 exit status
```
We shouldn't require libvirt to be present on a machine running kubernetes tests, hence the added directive to fix the test build:
```
go test -c -tags=notlibvirt ./test/e2e
```
> e2e-test: Add build directive to libvirt code

- azure/build-image.md
Azure image build documentation was missing a bunch of prerequisites. This commit adds them explicitly.
---
Tested these instructions in an ubuntu container.
> azure-image-build: Add missing pre-reqs

- podvm-mkosi/Makefile
- podvm/Makefile.inc
The podvm makefile would be invoked with an empty default policy file setting from the mkosi docker build, in which the docker-build arg is set to an empty string. The podvm makefile would hence not pick the default, but attempt to use the empty string in the creation of the symbolic link, resulting in a symbolic link that points to itself.
The change will make sure that the env is only set in the Dockerfile invocation if the variable is set in the mkosi makefile. Also we quote the the source file for the symbolic link creation, so we bail out properly, instead of creating a self-pointing symbolic link.
> policy: fix broken default policy symlink on mkosi

- versions.yaml
> kbs: pin down to released working kbs image version

- Makefile
Nightly podvm-binaries build has been failing with:
```
956.9 cd /src/cloud-api-adaptor/podvm/files/etc/kata-opa && ln -s -f "" default-policy.rego
956.9 ln: failed to create symbolic link 'default-policy.rego' -> '': No such file or directory
```
So port over the mkosi fix for this that Magnus did in #1718
> podvm: Fix podvm-binaries build

- peerpod-ctrl/Makefile
- peerpodconfig-ctrl/Makefile
- webhook/Makefile
- upgrade kustomize to v5.3.0 which has s390x arch support
fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/1732
> kustomize: upgrade kustomize to v5.3.0

- .github/workflows/azure-podvm-image-build.yml
There was an apt-get update statement missing that is causing CI failures.
> ci: update deb sources in azure podvm build

- podvm-mkosi/Makefile
It's related to PR https://github.com/confidential-containers/cloud-api-adaptor/pull/1734.
After updating PROTOC version to v3.15.0, still failed to build s390x fedora-binaries-builder image with following error:
```
=> ERROR https://github.com/protocolbuffers/protobuf/releases/download/v3.15.0/protoc-3.15.0-linux-s390x_64.zip
```
https://github.com/protocolbuffers/protobuf/releases/download/v3.15.0/protoc-3.15.0-linux-s390x_64.zip is not a valid url.
The valid url is: https://github.com/protocolbuffers/protobuf/releases/download/v3.15.0/protoc-3.15.0-linux-s390x.zip
So need revise the value of PROTOC_ARCH
> podvm: use correct PROTOC_ARCH value for s390x

- podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system-preset/30-coco.preset
- podvm/files/etc/systemd/system/api-server-rest.path
- podvm/files/etc/systemd/system/multi-user.target.wants/api-server-rest.path
- podvm/files/etc/systemd/system/multi-user.target.wants/api-server-rest.service
fixes #1695
there will be a race condition when CDH, started by kata-agent doesn't listen on cdh.sock yet, but api-server-rest attempts to use the socket immediately.
This change adds adds a path unit that will activate api-server-rest once the socket is being created and remove it from the default target.
A sophisticated e2e test has scientifically proven that this works reliably:
```bash
$ for i in $(seq 1 7); do k apply -f nginx-caa.yaml; sleep 90; k exec -it deploy/nginx-caa -- curl http://127.0.0.1:8006/cdh/resource/one/two/key; k delete deploy/nginx-caa; done
deployment.apps/nginx-caa created
ohai
deployment.apps "nginx-caa" deleted
deployment.apps/nginx-caa created
ohai
deployment.apps "nginx-caa" deleted
deployment.apps/nginx-caa created
ohai
deployment.apps "nginx-caa" deleted …
```
> podvm: trigger api-server-rest activation by file

- cmd/process-user-data/main.go
- pkg/adaptor/cloud/cloud.go
- pkg/cdh/config.go
- pkg/cdh/config_test.go
- pkg/userdata/provision.go
- pkg/userdata/provision_test.go
- podvm/files/etc/systemd/system/kata-agent.service
- versions.yaml
fixes #1720
This change will add a write_files entry to the cloud-config file that is produced by CAA. aa-kbc-params are converted into a config file with kbc name and kbc url.
process-user-data has been made more flexible to also support this entry.
guest-components in versions.yaml has been updated to a new revision that requires a cdh config file.
the kata-agent service unit has been extended to have the env `CDH_CONFIG_FILE=/run/confidential-containers/cdh.toml` set, which is the path that we add as a cloud-config directive.
> cloud-config: add support for CDH config

- hack/build-s390x-image.sh
- podvm-mkosi/Makefile
- podvm-mkosi/README.md
- podvm-mkosi/mkosi.presets/initrd/mkosi.conf.d/fedora-s390x.conf
- podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-bootable.conf
- podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-s390x.conf
- podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora.conf
- podvm-mkosi/mkosi.presets/system/mkosi.finalize.chroot
- podvm-mkosi/mkosi.profiles/debug.conf
- podvm-mkosi/mkosi.profiles/production.conf
According to #1640 , there are 2 problems for mkosi to build s390x images:
* The [nix OS](https://nixos.org/download/#download-nix) does not support s390x, but we can use the mkosi **ToolsTree** feature defined in `mkosi.conf` to download latest tools automatically:
```
[Host]
ToolsTree=default
```
* s390x does not support UEFI, so mkosi cannot build a bootable s390x image. Instead, we can first use **mkosi** to build non-bootable system files, then use **zipl** to generate the bootloader (podvm-mkosi/build-s390x-image.sh)
We need run **mkosi** from the repository:
```sh
git clone -b v21 https://github.com/systemd/mkosi
ln -s $PWD/mkosi/bin/mkosi /usr/local/bin/mkosi
mkosi --version
```
For the new mkosi release, there is an issue to set environment (#1746). Instead, we try to use profile …
> podvm-mkosi: support to build s390x fedora image

- .github/workflows/podvm_mkosi.yaml
- .github/workflows/test-images.yaml
- src/cloud-api-adaptor/test/provisioner/provision.go
- fix bad docker images build for test images
- the `context` and `file` need be set correctly when using `docker/build-push-action`
- also fix the e2e-test failed at `Installing peerpod-ctrl`
fixes for:
- https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/8385253126
- https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/8385451930/job/22965030759?pr=1757
> workflow: fix the bad workflows after we are in new file structure

- src/peerpod-ctrl/Makefile
the `undeploy` target is using the `KUSTOMIZE` binary, but it hasn't necessarily been created so add the kustomize target to it that creates
Fixes: 1755
> peerpod-ctrl: Make undeploy depend on kustomize target

- src/cloud-api-adaptor/podvm-mkosi/Makefile
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/initrd/mkosi.conf.d/fedora-s390x.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-bootable.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-s390x.conf
When build x86 podvm image with mkosi, we may hit following error:
```
Architecture cannot be used in [Match]
```
We depend on nix to setup mkosi build environment. Current mkosi version in nix is `17.1`:
```
warning: Git tree '/root/cloud-api-adaptor' is dirty
mkosi 17.1
```
According to the v17.1 doc, Architecture in [Match] has not been supported in this version:
https://github.com/systemd/mkosi/blob/v17.1/mkosi/resources/mkosi.md
If upgrading mkosi version in nix, we may hit some other new errors. So I'd like to keep mkosi version and use flag files instead to fix the Architecture error.
> podvm-mkosi: fix Architecture cannot be used in [Match]

- src/cloud-api-adaptor/aws/image/rhel/aws-rhel.pkr.hcl
- src/cloud-api-adaptor/aws/image/ubuntu/aws-ubuntu.pkr.hcl
- src/cloud-api-adaptor/azure/image/rhel/azure-rhel.pkr.hcl
- src/cloud-api-adaptor/azure/image/ubuntu/azure-ubuntu.pkr.hcl
Reasons:
* avoid unexpected bugs (there's one in latest azure plugin)
* avoid license changes
* packer usage for podvm creation is expected to be deprecated soon
> pin packer plugins versions

- src/cloud-api-adaptor/test/e2e/assessment_runner.go
Added code to handle the pod fail scenario by cross checking the error message we pass in .WithFailReason(reason string)
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/1760
> PodFailing scenario: updated assessment_runner.go

- .github/workflows/azure-podvm-image-build.yml
fixes #1703 
~draft until #1713 is merged.~
Tested packer-based image successfully with a TDX instance size. Starts and performs remote attestation w/ cc_kbc.
> ci: add tdx attester to azure podvm image

- src/cloud-api-adaptor/libvirt/README.md
- src/cloud-api-adaptor/libvirt/install_operator.sh
- src/cloud-api-adaptor/test/e2e/README.md
Few things that should simplify the setup for the newcomers
> libvirt: Improve the setup instructions to run libvirt tests

- src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
The service principal env file was needed when we used to rely on using service principal and its secrets. But we have moved away from using SP and now we use managed identities. So, we don't need this file anymore. But if someone needs it they still have a reference, so this commit comments it out, instead of removing it altogether.
Also another problem with this is that the CI runs fail as this file does not exists and kustomize errors out. In the CI run we don't provide the kustomization file we modify the existing kustomization file.
> azure: Comment out service principal env file

- .github/workflows/azure-podvm-image-build.yml
The packer based build takes more than 10 minutes to cleanup. And after the build if we use az CLI to clean up the intermediate image, it fails because the assertion is valid for 5 minutes only.
So relogin before we move on to cleanup the intermediate image.
Fixes: #1771
> azure-podvm-image-build: Relogin before cleanup

- .github/workflows/azure-e2e-test.yml
Since the project's folders have been reorgarnized the workflow needs an adjusted directories.
Successful run on a fork:  https://github.com/mkulke/cloud-api-adaptor/actions/runs/8614880290
> ci: fix working dir for azure e2e test

- src/cloud-api-adaptor/install/yamls/caa-pod.yaml
change dns setting of the CAA daemonset's pod-spec
name: cloud-api-adaptor-daemonset
namespace: confidential-containers-system
Should use `dnsPolicy: ClusterFirstWithHostNet`
> cloud-api-adaptor: Set dnsPolicy to ClusterFirstWithHostNet

- src/cloud-api-adaptor/go.mod
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
As part of the 0.8.1-alpha release we need to update the following go modules. make tidy didn't updated anything else.
> 0.8.1-alpha: updating go modules

- src/cloud-api-adaptor/hack/build.sh
podman does not support a `--push` flag.
Replaces #1739
> Build: Update build.sh

- src/cloud-api-adaptor/go.mod
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
Let's make sure we are using v0.8.1 for those modules.
> v0.8.1: bumping go modules

- src/cloud-api-adaptor/test/e2e/main_test.go
- src/cloud-api-adaptor/test/tools/README.md
- src/cloud-api-adaptor/test/tools/provisioner-cli/main.go
> test: add condition for kbs deploy in provisioner to align with e2e test

- src/cloud-api-adaptor/go.mod
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
Let's make sure we are using v0.8.2 for those modules.
> v0.8.2: bumping go modules

- .github/workflows/podvm_mkosi_image.yaml
- src/cloud-api-adaptor/hack/build-s390x-image.sh
- src/cloud-api-adaptor/podvm-mkosi/Makefile
- src/cloud-api-adaptor/podvm/Dockerfile.podvm.fedora
Update workflow, to build and push s390x Pod VM image with the s390x runner
Build a image including the s390x Pod VM qcow2 image, and push it to Quay container Registry: quay.io/confidential-containers/podvm-generic-fedora-s390x
Succeed to run the workflow in branch: https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/8643044858/job/23695257457
Verify the qcow2 image:
```
docker pull quay.io/confidential-containers/podvm-generic-fedora-s390x:latest
docker create --name "fedora-podvm-exporter" "quay.io/confidential-containers/podvm-generic-fedora-s390x:latest" /bin/sh
docker cp "fedora-podvm-exporter:/podvm-s390x.qcow2" .
docker rm -f "fedora-podvm-exporter" 
```
> podvm-mkosi: build and push images with s390x runner in workflow

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/go.sum
- src/cloud-providers/go.mod
- src/cloud-providers/go.sum
- src/peerpod-ctrl/go.mod
- src/peerpod-ctrl/go.sum
- src/peerpodconfig-ctrl/go.mod
- src/peerpodconfig-ctrl/go.sum
- src/webhook/go.mod
- src/webhook/go.sum
We have multiple security warnings for:
> Golang protojson.Unmarshal function infinite loop when unmarshaling certain forms of invalid JSON CVE-2024-24786
So we should try and bump them to see if we can resolve these without causing any other issues
> Bump google.golang.org/protobuf 1.33

- src/cloud-api-adaptor/test/e2e/assessment_runner.go
updating the code to check caa logs for podfail reason instead of podstatus
fixes: #1807
> test/e2e: update assessment_runner.go

- src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
- src/cloud-api-adaptor/install/rbac/kustomization.yaml
- src/cloud-api-adaptor/install/yamls/kustomization.yaml
- src/peerpod-ctrl/config/crd/kustomization.yaml
- src/peerpod-ctrl/config/default/kustomization.yaml
- src/peerpod-ctrl/config/manifests/kustomization.yaml
- src/peerpod-ctrl/config/prometheus/kustomization.yaml
- src/peerpod-ctrl/config/rbac/kustomization.yaml
- src/peerpod-ctrl/config/samples/kustomization.yaml
- src/peerpod-ctrl/config/scorecard/kustomization.yaml
- src/peerpodconfig-ctrl/config/crd/kustomization.yaml
- src/peerpodconfig-ctrl/config/default/kustomization.yaml
- src/peerpodconfig-ctrl/config/manifests/kustomization.yaml
- src/peerpodconfig-ctrl/config/prometheus/kustomization.yaml
- src/peerpodconfig-ctrl/config/rbac/kustomization.yaml
- src/peerpodconfig-ctrl/config/samples/kustomization.yaml
- src/peerpodconfig-ctrl/config/scorecard/kustomization.yaml
- src/webhook/config/certmanager/kustomization.yaml
- src/webhook/config/default/kustomization.yaml
- src/webhook/config/prometheus/kustomization.yaml
- src/webhook/config/rbac/kustomization.yaml
- src/webhook/config/webhook/kustomization.yaml
While setting-up my libvirt+kcli I noticed a few warnings from kustomize. I used `kustomize edit fix` to learn what to replace and then addressed all places using `sed`. Note the behaviour should not change but I have only tested the default libvirt e2e setup with kcli.
> Resolve kustomize warnings

- src/cloud-api-adaptor/test/e2e/main_test.go
- src/cloud-api-adaptor/test/provisioner/provision.go
- src/cloud-api-adaptor/test/tools/provisioner-cli/main.go
> provisioner: Add support to fetch kbs nodeport service ip

- src/cloud-api-adaptor/hack/build-s390x-se-image.sh
- src/cloud-api-adaptor/podvm-mkosi/Makefile
Refer to [build-s390x-se-image.sh](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/podvm/qcow2/build-s390x-se-image.sh) for building ubuntu image. Use **mkosi** to update initrd image, instead of **update-initramfs** which is not supported on fedora.
Need download host keys according to [SECURE_EXECUTION.md](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/ibmcloud/SECURE_EXECUTION.md), and set key folder path in env **HOST_KEYS_DIR**
Run `make image` to build production image with SE enabled.
> podvm-mkosi: build s390x fedora image with SE enabled

- .github/workflows/azure-podvm-image-build.yml
- src/cloud-api-adaptor/Dockerfile
- src/cloud-api-adaptor/Makefile.defaults
- src/cloud-api-adaptor/hack/yq-shim.sh
- src/cloud-api-adaptor/libvirt/config_libvirt.sh
yq3 (installed in kata builds as a side effect) and yq4 are different in cli and query syntax. the shim should abstract from those differences
> ci: add yq shim for v3/v4 support

- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-debug-ssh.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-debug.conf
For debug image, sshd service failed to start on s390x:
```
Apr 15 02:35:49 cdlleili-custom sshd[1353]: sshd: no hostkeys available -- exiting.
Apr 15 02:36:31 cdlleili-custom sshd[1395]: Unable to load host key: /run/ssh/ssh_host_rsa_key
Apr 15 02:36:31 cdlleili-custom sshd[1395]: Unable to load host key: /run/ssh/ssh_host_ecdsa_key
Apr 15 02:36:31 cdlleili-custom sshd[1395]: Unable to load host key: /run/ssh/ssh_host_ed25519_key
Apr 15 02:36:31 cdlleili-custom sshd[1395]: sshd: no hostkeys available -- exiting.
```
ssh config is overwritten by extra package: [mkosi.skeleton-debug/etc/ssh/sshd_config](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton-debug/etc/ssh/sshd_config)
However, it conflicts with cloud-init on …
> podvm-mkosi: sshd failed for s390x fedora image

- src/cloud-api-adaptor/podvm/Dockerfile.podvm_binaries
Re-add the cross-build install (I guess specifically the arch specific gcc is the issues) so get the s390x podvm back working.
> podvm: podvm_binaries - Revert s390x breakage

- .github/workflows/azure-e2e-test.yml
- src/cloud-api-adaptor/test/provisioner/provision.go
- src/cloud-api-adaptor/versions.yaml
> Provisioner: Add kbs provisioning steps in CI

- src/cloud-api-adaptor/libvirt/config_libvirt.sh
Update script to config libvirt not only work with Ubuntu but also RHEL 
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/1821
> libvirt: update script to config libvirt on RHEL.

- src/cloud-api-adaptor/libvirt/config_libvirt.sh
https://github.com/confidential-containers/cloud-api-adaptor/pull/1822 broke the e2e libvirt tests jobs (https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/8873277040/job/24359701508). We should have added the test_e2e_libvirt label, so sorry for missing that during the review.
config_libvirt.sh has `set -o errexit`, so we can't use a grep for rhel and test if it fails as this will exit the script. Instead use the ID field from `/etc/os-release` or `/usr/lib/os-release`
> libvirt: Fix config_libvirt to not exit

- src/cloud-api-adaptor/libvirt/README.md
- src/cloud-api-adaptor/libvirt/install_operator.sh
If we have a default IP address the logic that will calculate the IP based on the libvirt network will never be executed.
> libvirt: fix default IP logic

- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_run_all.yaml
- In preparation for the switch to use the latest operator we need to add code that will pass the CAA Image in to the e2e test properties file and try and work with both the new and old operator so that the workflow tests can pass pulled from main by the `pull_request_target` trigger
- In a future PR we will remove the old kustomize versions
> workflows: e2e: Add the CAA image setup

- src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
- src/cloud-api-adaptor/libvirt/README.md
- src/cloud-api-adaptor/podvm/Makefile.inc
- src/cloud-api-adaptor/test/e2e/README.md
- src/cloud-api-adaptor/test/e2e/azure_test.go
- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/test/e2e/main_test.go
- src/cloud-api-adaptor/test/provisioner/libvirt/provision_common.go
- src/cloud-api-adaptor/test/provisioner/provision.go
- src/cloud-api-adaptor/test/tools/provisioner-cli/main.go
Fixes: #1825 
This PR is based on the azure approach: https://github.com/confidential-containers/cloud-api-adaptor/pull/1735
- Add `AA_KBC_PARAMS` in libvirt provider
- Wait kbs deployment ready before retrieve the endpoint from it
- Add test case for attestation secret
- Revise a little for the caa ds waiting, as pod ready is enough as the condition
- Change the KBS opa policy to allow_all
> libvirt: e2e test for attestation for sample tee

- src/cloud-api-adaptor/test/e2e/libvirt_test.go
The TestLibvirtCreatePeerPodAndCheckEnvVariableLogsWithImageOnly test is failing semi-regularly on the CI, but seems to run okay locally, so skip it until we have a chance to debug. See https://github.com/confidential-containers/cloud-api-adaptor/issues/1831
> test/e2e: Skip unstable libvirt test

- .github/workflows/podvm_binaries.yaml
- src/cloud-api-adaptor/podvm-mkosi/Makefile
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_binaries
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_binaries.fedora
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_binaries.rhel
> libvirt: use AA_KBC=cc_kbc as default for peerpod binaries

- src/cloud-api-adaptor/podvm/Makefile
- src/cloud-api-adaptor/podvm/qcow2/rhel/qemu-rhel.pkr.hcl
we started seeing below error recently for s390x rhel podvm image builds.
```
packer build -var qemu_image_name=podvm-a589f66-dirty-s390x.qcow2 -var cloud_image_url=https://access.redhat.com/downloads/content/433/ver=/rhel---9/9.3%20Beta/s390x/product-software -var cloud_image_checksum=sha256:d436ffeac7d468f75526ca8b8bab1cba64ba3ab2889ccd11fa107a7323b267db -var disk_size=11144 -var machine_type=s390-ccw-virtio -var cpu_type=max -var qemu_binary=qemu-system-s390x qcow2/rhel
Error: Missing plugins
The following plugins are required, but not installed:
* github.com/hashicorp/qemu 1.1.0
Did you run packer init for this project ?
make: *** [Makefile:85: podvm-a589f66-dirty-s390x.qcow2] Error 1
Error: building at STEP "RUN LIBC=gnu make image": while running runtime: exit status 2
make: *** …
```
> podvm: rhel: Qemu plugin build for s390x

- src/cloud-api-adaptor/pkg/agent/test-data/sample-agent-config.toml
- src/cloud-api-adaptor/pkg/agent/update.go
- src/cloud-api-adaptor/pkg/agent/update_test.go
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton-debug/usr/lib/systemd/system/api-server-rest.service.d/20-debug.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton-debug/usr/lib/systemd/system/attestation-agent.service.d/20-debug.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton-debug/usr/lib/systemd/system/confidential-data-hub.service.d/20-debug.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system-preset/30-coco.preset
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/attestation-agent.service.d/10-override.conf
- src/cloud-api-adaptor/podvm/files/etc/agent-config.toml
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/attestation-agent.service
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/confidential-data-hub.path
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/confidential-data-hub.service
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-agent.service
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/multi-user.target.wants/attestation-agent.service
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/multi-user.target.wants/confidential-data-hub.path
- src/cloud-api-adaptor/versions.yaml
Prior to this change the kata-agent was launching the guest-components programatically as child process. For CAA it is preferable to launch the processes as systemd units for improved reliability and to remove redundancy (due to the network ns requirement api-server-rest was spawned in the root ns by kata and via systemd in the podns ns by systemd)
We need to make the "update" functionality aware of the `guest_components_procs` agent setting, so it will be copied to the destination agent configuration file.
The attestation-agent unit is spawned after process-user-data, because it will consume the templated kata-agent config. The confidential-data-hub and api-server-rest units are activated by the presence of the unix sockets they connect to.
attestation-agent will keep defaulting to the …
> podvm: launch guest-components as systemd units

- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-debug.conf
- add dnf to debug image for packages management
- add openssh-clients to  debug image for scp etc
> fedora: add dnf and openssh-clients for debug

- hack/Dockerfile.golang
- src/cloud-api-adaptor/Dockerfile
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.fedora
- src/peerpod-ctrl/Dockerfile
- Fedora 38 has passed EoL 3 weeks ago, so we should try and bump to the next version (or possibly even 40?).
- Once `golang-fedora:1.21.11-39` is built, this will be followed up with a bump of the builder_base we use as well,
but do to the chance of breaking things I'll keep it separate for now.
> versions: Bump fedora base image versions

- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- The rest of the libvirt env tests are also a bit flaky, so skip them on CI to try and get it stable
> test/e2e: Skip all libvirt env tests

- src/cloud-api-adaptor/Dockerfile
- src/cloud-api-adaptor/docs/addnewprovider.md
- src/csi-wrapper/Dockerfile.csi_wrappers
- src/peerpod-ctrl/Dockerfile
Now that `golang-fedora:1.21.11-39` has been built to quay, we can update our builds to use this and remove our use of fedora 38 which is EoL
> versions: Bump golang-fedora image version

- src/cloud-api-adaptor/libvirt/config_libvirt.sh
- src/cloud-api-adaptor/versions.yaml
Switch kcli to use pip to install and pin the version we are using to avoid breaking changes
> Kcli version pinning

- src/cloud-api-adaptor/versions.yaml
- Bump to commit fe9560bb99c0e89c0d81f24f08ac4b63d3e22821 for se-attester
- cd src/cloud-api-adaptor/podvm-mkosi && ATTESTER=se-attester make binaries
> ibmse: bump guest components commit to support se-attester

- .github/workflows/azure-podvm-image-build.yml
new guest-components feature toggles use hyphens, not underscores
> ci: fix azure image build

- src/cloud-api-adaptor/azure/image/ubuntu/azure-ubuntu.pkr.hcl
westeurope may not offer free k8s tiers all the time
> azure: set northeurope as default replication loc

- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
- src/cloud-api-adaptor/pkg/forwarder/forwarder.go
- src/cloud-api-adaptor/pkg/userdata/provision_test.go
This field is not used by the forwarder component or anywhere else, aa-kbc-params is managed as part of AA and CDH, having this field duplicated in daemon.json could produce confusion.
> forwarder: remove aa_kbc_params from daemon.jsom

- README.md
- docs/architecture.md
- src/cloud-api-adaptor/README.md
- src/cloud-api-adaptor/docs/DEVELOPMENT.md
- src/cloud-api-adaptor/docs/tls-proxy-forwarder.md
- src/cloud-api-adaptor/ibmcloud-powervs/README.md
- src/cloud-api-adaptor/podvm/README.md
Now we aren't using the kata-container's `CCv0` branch, remove the references to it and switch them out to `main`, or remove if no longer applicable.
Note: There is more work needed on the documentation to review and update it, but this is out of the current scope of this PR.
> doc: Remove references to `CCv0`

- src/cloud-api-adaptor/podvm/Makefile.inc
This PR adds two commits
1. Enables downloading pause image from an authenticated registry before embedding
2. Allows overriding the default pause binary name to a custom name if needed.
> Enable support for embedding custom pause image from authenticated registry in the pod VM image

- src/cloud-api-adaptor/libvirt/config_libvirt.sh
Extend the script to also detect fedora and centos.
I personally tested this on centos and it works fine.
> config_libvirt.sh: detect also rhel-like distros

- docs/Release-Process.md
- Rework our release process documentation based on the change of process in CoCo
> doc: Release process

- src/cloud-api-adaptor/Makefile
- Fix the version of the operator used for the 0.9.0-alpha1 release of peer pods to the matching version to try and ensure that if people deploy the release this from the Makefile at a later date, it will be compatible
> release: Pick operator release in install

- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-s390x.conf
Both NetworkManager and systemd-networkd are currently installed and each tries to obtain an IP address from an DHCP server. This results in two IP addresses assigned to a single network interface of a booted pod VM. The agent-protocol-forwarder process fails to start when multiple IP addresses are assigned.
This patch removes NetworkManager from s390x fedora image, and fix the error of agent-protocol-forwarder.
Fixes #1893
> mkosi-podvm: Remove NetworkManager from s390x fedora image

- src/cloud-api-adaptor/go.mod
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
We are working on the `v0.9.0-alpha1` pre-release, so bump the go modules to use the new tag we will create once they are merged.
> release: Update go modules for pre-release

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
- Pin the cloud-api-adaptor image in the instal kusomizations to the latest pre-release tag, so that the v0.9.0-alpha1 release will have a stable version
- Bump the go modules to use the new alpha release tag we will create once this is merged.
> v0.9.0-alpha1 release

- src/cloud-api-adaptor/docker/.gitignore
- src/cloud-api-adaptor/docker/README.md
- src/cloud-api-adaptor/docker/image/Dockerfile
- src/cloud-api-adaptor/docker/image/Makefile
- src/cloud-api-adaptor/docker/kind-config.yaml
- src/cloud-api-adaptor/docker/kind_cluster.sh
- src/cloud-api-adaptor/docker/prereqs.sh
- src/cloud-api-adaptor/docs/troubleshooting/nydus-snapshotter.md
- src/cloud-api-adaptor/entrypoint.sh
- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
- src/cloud-api-adaptor/test/e2e/README.md
- src/cloud-api-adaptor/test/e2e/docker_common.go
- src/cloud-api-adaptor/test/e2e/docker_test.go
- src/cloud-api-adaptor/test/provisioner/docker/provision.go
- src/cloud-api-adaptor/test/provisioner/docker/provision_common.go
- src/cloud-api-adaptor/test/provisioner/docker/provision_docker.properties
- src/cloud-providers/docker/docker.go
- src/cloud-providers/docker/manager.go
- src/cloud-providers/docker/provider.go
- src/cloud-providers/docker/types.go
Also makes docker network and podvm image configurable to help with e2e, and some minor fixes
> Add e2e tests for docker

- .github/workflows/azure-e2e-test.yml
- src/cloud-api-adaptor/test/provisioner/azure/provision_common.go
- src/cloud-api-adaptor/test/provisioner/azure/provision_initializer.go
- src/cloud-providers/azure/provider.go
Sometime resources aren't properly deleted in the azure e2e test. It impacts VM + aux resources, but also AKS cluster cleanup b/c the VM is still attached to a cluster's node subnet. Matrix tests are short-circuited if one of them fails, so it's not unlikely that we're not able to clean up properly.
* resource tags are being used to mark resources created by specific test run.
* also tag nics
* removed deprovisioner step (it adds a couple of minutes to a test run, and the cluster is discarded anyway)
* cleanup will always run
Created a VM in the RG of the test using the tags and confirmed it was removed by the cleanup, in both a successful and a failed run.
> ci: delete dangling vms in azure e2e test

- src/cloud-api-adaptor/versions.yaml
This patch bumps the version of kcli to 99.0.202407031308. This version includes a fix https://github.com/karmab/kcli/commit/2babdf6fda2f04a4c1e7a814b89193fdac14f664 for the issue that prevents from creating a cluster with libvirt/kcli_cluster.sh on s390x.
Fixes #1907
> libvirt: Bump to kcli 99.0.202407031308

- src/cloud-api-adaptor/ibmcloud/README.md
- src/cloud-providers/ibmcloud/provider.go
I followed the guide to [Deploy the Confidential-containers operator](https://github.com/confidential-containers/cloud-api-adaptor/tree/main/src/cloud-api-adaptor/ibmcloud#deploy-the-confidential-containers-operator) on a self-managed cluster in IBM Cloud VPC. However, it doesn't work as expected. I try to fix 2 problems:
- Fix the default VPC service url, revert it to the value in v0.8.0: https://github.com/confidential-containers/cloud-api-adaptor/blob/v0.8.0/pkg/adaptor/cloud/ibmcloud/provider.go#L79
- Add missing settings in selfmanaged_cluster.properties.  Without those settings, CAA will fail to create instance with errors like below:
```
failed to create an instance : Expected only one oneOf fields to be set: got 0 and the response is {
"code": "validation_failed_oneof",
"message": …
```
> ibmcloud: revise ibmcloud README

- hack/Dockerfile.golang
- src/cloud-api-adaptor/Dockerfile
- src/peerpod-ctrl/Dockerfile
- src/peerpodconfig-ctrl/Dockerfile
- src/webhook/Dockerfile
https://docs.docker.com/reference/build-checks/from-as-casing/ states the FROM and AS keywords in Dockerfiles
should match, so some of our jobs and is throwing warnings in our build steps
> build: Fix Dockerfile from-as-casing warnings

- docs/Release-Process.md
- src/cloud-api-adaptor/Makefile
- src/cloud-api-adaptor/Makefile.defaults
- src/cloud-api-adaptor/install/README.md
- src/cloud-api-adaptor/test/provisioner/provision.go
- src/cloud-api-adaptor/test/utils/versions.go
- src/cloud-api-adaptor/versions.yaml
Added 'git.coco-operator' entry to the project's versions.yaml with information about the repository URL and reference (commit SHA1, tag...etc) as a way to have a single source truth and avoiding the need to update the references in many places at release time (then roll-back after the release).
Now `make deploy` will read the operator's URL and reference from versions.yaml. Likewise, the e2e test's provision.
> versions: add entry for CoCo operator

- src/cloud-api-adaptor/docker/README.md
- src/cloud-api-adaptor/docker/kind-config-crio.yaml
- src/cloud-api-adaptor/docker/kind_cluster.sh
- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/main_test.go
- src/cloud-api-adaptor/test/provisioner/docker/provision_common.go
- src/cloud-api-adaptor/test/provisioner/docker/provision_docker.properties
A new parameter CONTAINER_RUNTIME is added. Default value is "containerd". Set the value to "crio" to execute e2e tests on a crio based kind cluster.
Also fix few test cases.
> docker: add support for crio based e2e tests

- docs/Release-Process.md
- hack/release-helper.sh
Update the release process with some optimizations found during the release process:
- Merge the pre-release operator version bump and go mod update into the same PR to save a round of reviews
- Update the release-helper to enable the upstream branch to be passed in rather than it being hard coded during go-tag action
- Add an extra command to the release-helper to help with updating the CAA image tags in the install kustomization.yaml files for the various cloud providers, without impacting the file layout
> doc: Release doc updates

- src/cloud-api-adaptor/podvm-mkosi/Makefile
- remove the useless `docker buildx use default` command
- fix Error: unrecognized command `podman buildx use`
- with podman version 4.9.4-rhel on RHEL 9.4
> podvm-mkosi: let 'make binaries' works on RHEL with podman

- .github/workflows/e2e_libvirt.yaml
- The new version of the KBS client is failing the build in https://github.com/confidential-containers/cloud-api-adaptor/pull/1929
```
The file `openssl.pc` needs to be installed and the
PKG_CONFIG_PATH environment variable must contain its parent directory.
```
so install packages to get it building
> workflow: Install packages for KBS client

- .github/workflows/azure-e2e-test.yml
- src/cloud-api-adaptor/test/provisioner/azure/provision_common.go
- src/cloud-api-adaptor/test/provisioner/azure/provision_initializer.go
Added option to specify a federated credential name so we can remove it together with other resources (outside of the deprovisioner).
> azure: remove fed cred in e2e test cleanup

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/go.sum
- src/cloud-api-adaptor/test/provisioner/provision.go
- src/cloud-api-adaptor/versions.yaml
- src/csi-wrapper/go.mod
- src/csi-wrapper/go.sum
- Bump the kata-runtime go module to the 3.7.0 version in the csi-wrapper and cloud-api-adaptor modules
- Bump dependencies to match the versions used in the [Kata 3.7.0 release](https://github.com/kata-containers/kata-containers/blob/3.7.0/versions.yaml) to minimise the chances of incompatibilities and unstable code
> Kata 3.7.0 release bump

- src/cloud-api-adaptor/cmd/process-user-data/main.go
- src/cloud-api-adaptor/docs/registries-authentication.md
- src/cloud-api-adaptor/ibmcloud-powervs/image/copy-files.sh
- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
- src/cloud-api-adaptor/pkg/agent/config.go
- src/cloud-api-adaptor/pkg/agent/config_test.go
- src/cloud-api-adaptor/pkg/userdata/provision.go
- src/cloud-api-adaptor/pkg/userdata/provision_test.go
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/kata-agent.service.d/10-override.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/tmpfiles.d/peerpods.conf
- src/cloud-api-adaptor/podvm/files/etc/agent-config.toml
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-agent.service
- src/cloud-api-adaptor/podvm/qcow2/copy-files.sh
- src/cloud-providers/util/cloudinit/cloudconfig.go
- src/cloud-providers/util/cloudinit/cloudconfig_test.go
Kata introduced a flag to specify `image-registry-auth` which we can in guest pull. Since our agent-configuration is mostly static and we want to avoid brittle templating we provision the full kata-agent config from the CAA application like other config files.
If an auth secret is present in a CAA deployment, CAA will embed it in the agent config and provision it to the guest. The static agent-configuration has been removed and the configuration is pointing to `/run/peerpod/agent-config.toml` now, since it is a resource that changes at runtime.
> auth: allow specifying auth.json for guest-pull

- src/cloud-api-adaptor/pkg/userdata/provision.go
The config files were incorrectly assigned resulting in agent-config.toml not being created.
> process-user-data: Fix the assignment of config filenames

- src/cloud-api-adaptor/go.mod
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
We are working on the `v0.9.0` pre-release, so bump the go modules again to use the new tag we will create once they are merged.
> release: Update go modules for another pre-release

- docs/Release-Process.md
- Update to reflect that we need to wait for the operator payload change before starting the peer-pods release
> doc: Release process re-work

- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_run_all.yaml
Set the `AUTHENTICATED_REGISTRY_IMAGE` and
`REGISTRY_CREDENTIAL_ENCODED` secrets as environment variables in preparation for adding libvirt auth registry tests
> workflow: Add auth test secrets

- src/cloud-api-adaptor/podvm-mkosi/Makefile
Since #1923 was merged, the CI job using podvm_mkosi_image.yaml has been failing.
It turns out `docker buildx use default` needs to be run in the GHA environment where the Ubuntu self-hosted runner is running.
This PR adds support for both Debian and Fedora variants.
Fixes: #1949
> podvm-mkosi: Add support for Debian and Fedora variants

- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/ibmcloud_test.go
- Skip fail reason check for Completed pod. Refer to issue: https://github.com/confidential-containers/cloud-api-adaptor/issues/1938
- Set more timeout to recreate container by annotation. The default timeout 60 sec is too short to pull large image data
- Use `t.Skip` instead of `log.Infof` for skip cases
> e2e: improve test cases for ibmcloud provider

- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
- src/cloud-api-adaptor/pkg/forwarder/forwarder.go
- src/cloud-api-adaptor/pkg/userdata/provision.go
- src/cloud-api-adaptor/pkg/userdata/provision_test.go
Instead of nesting it into a daemon.json property for the forwarder the auth file is being moved to its own entry, which will simplify the logic and allow cloud-init based podvms to use authenticated registries without running process-user-data alongside cloud-init.
> cloud-config: streamline credentials provisioning

- README.md
fossa license issues are resolved, we can have a badge now.
> readme: add fossa badge

- src/cloud-api-adaptor/podvm/files/etc/ocicrypt_config.json
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-agent.service
this will (re-)enable support for encrypted images on kata#main
kata uses image-rs, which in turn uses ocicrypt-rs. the latter requires the env OCICRYPT_KEYPROVIDER_CONFIG to point to a file which defines how decryption keys can be retrieved from CDH. (note: it's called attestation-agent here, but that's a misnomer for historical reasons)
kata-agent is only setting this env in process and writing the file to a /tmp location, if it is actively managing the guest-component processes.
We start those processes as service units, so we have to take care of it on the podvm manually. the ocicrypt file is static and writing to /tmp wouldn't work well with a read-only rootfs anyway, so we can just include in the podvm image and referene the path in the env.
> kata-agent: set ocicrypt environment variable

- src/cloud-api-adaptor/aws/README.md
Update the instructions to create EKS cluster with Calico, as the default EKS CNI doesn't work with cloud-api-adaptor.
Also some minor formatting edits
> aws: Update docs

- src/cloud-api-adaptor/test/e2e/README.md
- src/cloud-api-adaptor/test/e2e/common.go
If your pre-configured environment uses a pod VM image with restrict agent policy, then some of the e2e tests may fail.  This commit introduces a variable to override the test pods with a relaxed agent policy allowing all APIs.
`POD_ALLOW_ALL_POLICY_OVERRIDE=yes`
Also updating the README with instructions on how to execute e2e tests against a pre-configured cluster
> test-e2e: Allow agent policy override

- src/cloud-api-adaptor/test/e2e/common.go
make align with [test/e2e/main_test.go#L106](https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/test/e2e/main_test.go#L106)
to fix the e2e testcase skipped
```
19:47:32  === RUN   TestLibvirtKbsKeyRelease
19:47:32      libvirt_test.go:109: Skipping kbs related test as kbs is not deployed
19:47:32  --- SKIP: TestLibvirtKbsKeyRelease (0.00s)
19:47:32  PASS
```
> tests/e2e: fix TestLibvirtKbsKeyRelease skip

- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/rolling_update.go
- src/cloud-api-adaptor/test/provisioner/libvirt/provision_common.go
The auth.json file is not provisioned for the authenticated registry tests in the libvirt test suite. This adds the file and adjusts the kustomize configuration to use it.
drive-by fix: log formatting
> libvirt-e2e: create auth.json file

- .github/workflows/podvm_mkosi_image.yaml
The following hooks:
- ACTIONS_RUNNER_HOOK_JOB_STARTED
- ACTIONS_RUNNER_HOOK_JOB_COMPLETED
could perfectly replace the existing {pre,post}-action scripts and will make a workflow independent of the runner context. This PR wipes out all GHA steps where the actions are triggered.
> GHA: Remove {pre,post}-action steps for self-hosted runners

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/versions.yaml
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
Updated the go.mod files and pinned to the CoCo operator v0.9.0.
$ git log --pretty=oneline v0.9.0-alpha.3...origin/main
142e772769db5bac7f9febf8825f64b13c3f53cd (origin/main, origin/HEAD) GHA: Remove {pre,post}-action steps for self-hosted runners
34b2c1c500fe5d06fa5e16d1a5b2e24a9a489d88 e2e-tests: use t.Log instead of fmt/log
9e6a4a760ed6112a64854d6fc770cd36ff66d67d libvirt-e2e: create auth.json file
c7c2a93501edf9bd469b5d4736301c6cfd7b3f0b tests/e2e: fix TestLibvirtKbsKeyRelease skip make align with test/e2e/main_test.go#L106
18b1d7d13ef2e75d165af5a348f1d790b9857567 e2e-test: use t.Log functions in tests
7f2ecddcce1c5e17b675f3d4fd8fef31585e0a63 test-e2e: Allow agent policy override
3f67b4e7deef4469f9997dc6380d3082691b4921 aws: Update docs
ee70b253776936d64a1a8b8b6440a160791ed156 podvm: …
> release: prepare for v0.9.0 alpha.4

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
These are the last code changes before we create tags and cut the v0.9.0 release.
> release: preparing for v0.9.0

- .github/workflows/azure-e2e-test.yml
- src/cloud-api-adaptor/test/provisioner/trustee_kbs.go
TDX attestation requires a pccs_url to be set. we'll introduce a flag CUSTOM_PCCS_URL that will configure kbs to use the it.
> e2e-tests: add option to deploy kbs with custom pccs_url

- src/cloud-api-adaptor/Makefile
- src/cloud-api-adaptor/ibmcloud/SECURE_EXECUTION.md
- src/cloud-api-adaptor/ibmcloud/image/build.sh
- src/cloud-api-adaptor/ibmcloud/image/push.sh
- src/cloud-api-adaptor/ibmcloud/image/verify.sh
- src/cloud-api-adaptor/podvm/Dockerfile.podvm.rhel
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.rhel
- src/cloud-api-adaptor/podvm/Makefile
- src/cloud-api-adaptor/podvm/README.md
- src/cloud-api-adaptor/podvm/qcow2/build-s390x-se-image-post.sh
- src/cloud-api-adaptor/podvm/qcow2/build-s390x-se-image.sh
- src/cloud-api-adaptor/podvm/qcow2/rhel/qemu-rhel.pkr.hcl
- src/cloud-api-adaptor/podvm/qcow2/rhel/variables.pkr.hcl
- src/cloud-api-adaptor/podvm/qcow2/ubuntu/qemu-ubuntu.pkr.hcl
This changes help build RHEL Se enabled podvm image with an extra Arg of SE_BOOT=true
Changes Made:-
Updated the build-s390x-se-image.sh script to generate SE PodVM images for both RHEL and Debian.
Used Dracut to update the initramfs on the RHEL machine, incorporating the newly created fstab, crypttab, and keys into the Dracut configuration file.
Revised the Packer configuration file (qemu-rhel.pkr.hcl) to include an additional disk for encryption purposes and to execute a script for enabling SE.
Updated the Makefile, Dockerfile.podvm.rhel, and variables.pkr.hcl to include the SE_BOOT variable option.
Also, as suggested in comments replaced all SE_BOOT=1 with SE_BOOT=true.
Temporary  fix: 
Due to issue https://gitlab.com/qemu-project/qemu/-/issues/2054, we can't install packages on RHEL …
> podvm:Enable se image build for s390x rhel podvm

- src/cloud-api-adaptor/test/e2e/common_suite.go
Test should not create resources with the same name, because this will introduce race conditions if the tests run in parallel.
> e2e-test: Remove naming conflicts

- src/cloud-api-adaptor/pkg/podnetwork/podnetwork_test.go
- src/cloud-api-adaptor/pkg/podnetwork/podnode.go
- src/cloud-api-adaptor/pkg/podnetwork/tunneler/routing/podnode.go
- src/cloud-api-adaptor/pkg/podnetwork/tunneler/tunneler.go
- src/cloud-api-adaptor/pkg/podnetwork/tunneler/vxlan/podnode.go
- src/cloud-api-adaptor/pkg/podnetwork/workernode.go
- src/cloud-api-adaptor/pkg/util/netops/netops.go
CNI plugins like PTP and GKE remove a route that is automatically added by kernel for eth0, and then add another route for the same destination.
This patch changes the code to manipulates routes to support such CNI plugins.
Fixes #1909
> podnetwork: Support CNI plugins like PTP and GKE 

- .github/workflows/daily-e2e-tests-ibmcloud.yaml
- libvirt_amd64
- libvirt_s390x
- s390x-non-secure-execution (s390x worker node)
- s390x-attestation-ibmse-tee (libvirt_s390x_ibmse_tee)
- push daily peerpod images (ubuntu-amd64, ubuntu-s390x and fedora-s390x-se)
> e2e-test: test result from ibm

- src/cloud-api-adaptor/test/e2e/assessment_helpers.go
- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
tests will run into into race conditions without a unique name when they run in parallel.
drive-by fix: use t.Logf when deleting pods
> e2e-tests: remove service naming conflicts

- src/cloud-api-adaptor/test/e2e/assessment_runner.go
We have elaborate condition checks on a job's pods, but we do not test the job status itself, which will produce wrong test results. A test for job that always fails (cmd: /bin/false) will pass.
This keeps the current assertions in-place, but makes the test fail on a failed job status
> e2e-test: assert job condition on job tests

- src/cloud-api-adaptor/test/e2e/common_suite.go
Sorry about the barrage of e2e PRs, but I keep stumbling over race conditions.
the nginx server/client tests use the same app= labels to pick a service, this will create problems when running both tests in parallel.
> e2e-tests: resolve ambiguous service labels

- src/cloud-api-adaptor/pkg/userdata/provision.go
- src/cloud-api-adaptor/pkg/userdata/provision_test.go
currently the process-user-data unit will fail because process-user-data will exit with a non-zero exit code if there is no initdata file on the file system. this PR will skip the initdata processing with a log message and exit successfully in such a case.
> initdata: don't fail process-user-data if absent

- src/cloud-api-adaptor/podvm/files/etc/kata-opa/default-policy.rego
- src/cloud-api-adaptor/podvm/files/etc/tmpfiles.d/policy.conf
- src/cloud-api-adaptor/podvm/qcow2/copy-files.sh
Since policy is provisioned by initdata to /run/peerpod/policy.rego we need to point the symlink to that file.
In case no init-data is provided allow-all.rego is copied by systemd to /run/peerpod/policy.rego
> policy: symlink default policy to /run/peerpod

- src/cloud-api-adaptor/docs/initdata.md
Add digest usage example in ibmse
> initdata: update doc for digest usage

- README.md
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/process-user-data.service.d/10-override.conf
This adds two post exec directives for process-user-data in the mkosi to extend PCR 8 (grub, which we don't use it mkosi podvms: https://uapi-group.org/specifications/specs/linux_tpm_pcr_registry/) with the digest of initdata. Sha256 and Sha384 banks are attempted. initdata.digest contains a hex value that will fit only in one of those. A failure of either post exec step will be ignored and do not turn the unit status into a failure.
This is a bit provisional, but since things with init-data and runtime measurement are a bit in flux still, which doesn't warrant to put such logic in code yet.
> initdata: measure initdata digest into rt register

- src/cloud-providers/ibmcloud/provider.go
> ibmcloud: Use ibm-cloud.kubernetes.io/subnet-id to look up VPC details

- src/cloud-providers/ibmcloud/provider.go
- src/cloud-providers/ibmcloud/provider_test.go
This PR ensures the arch information is captured when populating instance profile specs and then ensures that the architecture information is used when selecting the image. This PR also adds accompanying tests.
Fixes #1795
> ibmcloud: Fix arch suport for selectImage

- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
- src/cloud-api-adaptor/pkg/adaptor/proxy/proxy.go
Minor, almost trivial, logging enhancements
> Minor cloud-api-adaptor logging enhancements

- src/cloud-api-adaptor/pkg/adaptor/proxy/proxy.go
Use proxy timeout value to set dialer timeout. Default for TCP connections is documented as ~3 minutes, which has proven to be insufficient on AWS.
The proxy timeout value is set through `peer-pods-cm` ConfigMap as `PROXY_TIMEOUT`.
> Explicitly set proxy dialer timeout

- src/cloud-api-adaptor/pkg/securecomms/ppssh/ppssh.go
- src/cloud-api-adaptor/pkg/securecomms/sshproxy/sshproxy.go
Fixes: #2012
Avoid closing an already closed chan.
> cloud-api-adaptor: SecureComms fix panic for closing chan twice

- src/cloud-api-adaptor/pkg/podnetwork/podnode.go
- src/cloud-api-adaptor/pkg/podnetwork/tunneler/tunneler.go
- src/cloud-api-adaptor/pkg/podnetwork/workernode.go
- src/cloud-api-adaptor/pkg/util/netops/netops.go
Permanent ARP entries that are explicitly set in the network namespace for a pod in a worker node are propagated to
the podns network namespace in a peer pod VM.
The EKS CNI plugin sets such a permanent ARP entry, and this patch is necessary for peer pods to work with EKS networks.
Fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/1966
I tested this change with Flannel and Calico.
> Support EKS CNI plugin

- src/cloud-api-adaptor/Dockerfile
- src/cloud-api-adaptor/install/yamls/caa-pod.yaml
- src/cloud-api-adaptor/versions.yaml
This PR is a prerequisite to fix https://github.com/confidential-containers/cloud-api-adaptor/issues/2015
To run the iptables command within the cloud-api-adaptor container, we need a wrapper command for iptables, and volumes for accessing a lock file and kernel modules in the host side.
https://github.com/kubernetes-sigs/iptables-wrappers
Network-related projects such as [kube-proxy](https://github.com/kubernetes/release/blob/54644168fde905d452980d0d34984a993e6b24a5/images/build/distroless-iptables/distroless-bullseye/Dockerfile#L45-L47) and [flannel](https://github.com/flannel-io/flannel/blob/bb077808679ff71527d5a9a0ff7ffbf7d108dad4/images/Dockerfile#L20)  use this wrapper to manipulate netfilter on worker nodes.
Another PR that actually fixes the issue using iptables will follow after …
> Install iptables in cloud-api-adaptor daemonset

- src/cloud-providers/ibmcloud/provider.go
This PR enables the VM metadata service to avoid the timeouts when starting up.
Fixes: #2021
> ibmcloud: Fix slow VM startup

- src/cloud-api-adaptor/podvm/README.md
Current dockerfiles are not ready to build directly from the folder. Builder is broken as also depends on .git and .hack folders. Make targets are working, so lets redirect our readers to use those targets.
We can improve the targets as needed and this will be transparant for the readers.
> docs: redirect users to use make targets on builds

- src/cloud-api-adaptor/ibmcloud-powervs/README.md
- src/cloud-api-adaptor/ibmcloud-powervs/image/prereq.sh
Changes:
1. Moving from centos 8-stream to centos 9-stream for qcow2ova image.
2. Adding additional steps to setup a DHCP server
3. Updating pre-req.sh for installing additional packages `protobuf-compiler` and `device-mapper-devel`
> IBMCloud-Powervs docs and pre-req update

- src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.fedora
Fixes #2028
This patch also installs the `xz` command which is required here.
https://github.com/confidential-containers/cloud-api-adaptor/blob/81485e1f9427f07eff2e5f1bad49c31a283283fe/src/cloud-api-adaptor/podvm/Makefile.inc#L135
> podvm: Fix a build break of fedora-binaries-builder

- src/cloud-api-adaptor/pkg/podnetwork/tunneler/vxlan/iptables.go
- src/cloud-api-adaptor/pkg/podnetwork/tunneler/vxlan/podnode.go
- src/cloud-api-adaptor/pkg/podnetwork/tunneler/vxlan/workernode.go
- src/cloud-api-adaptor/pkg/util/netops/netops.go
This patch disables connection tracking of VXLAN UDP packets to prevent the conntrack table from filing up.
The Linux connection tracking system (conntrack) always tracks UDP packets as connections by default. This is OK for usual UDP communications, but does not work with VXLAN UDP packets, since a destination port of each VXLAN UDP packet is fixed (4789) in both directions, and a source port of each packet is randomly selected. This UDP packet flow does not creates a connection flow, and every UDP packet of a VXLAN tunnel is recognized as a first packet of a new UDP  sream.
If conntrack table fills up, it may affect other network connections that needs NAT. This patch will alleviate such problems.
Fixes #2015
We can confirm necessary iptable rules are added in a worker node as follows. …
> podnetwork: Disable connection tracking of VXLAN UDP packets

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/go.sum
- src/cloud-api-adaptor/versions.yaml
- src/csi-wrapper/go.mod
- src/csi-wrapper/go.sum
Bump components to sync with kata v3.8.0 release to try and ensure we stay up-to-date (ish)
> Kata 3.8.0 versions bump

- src/cloud-api-adaptor/libvirt/config_libvirt.sh
- src/cloud-api-adaptor/libvirt/kcli_cluster.sh
Get correct yq package name and specify virt machine type for aarch64 instead of relying on kcli (https://github.com/karmab/kcli/commit/7cad52ce9774ffc05b86ce2c127429345ee851fa won't override the machine type from user's input for aarch64 any more).
Also sent some minor `kcli` changes here: https://github.com/karmab/kcli/pull/718
With above changes, `kcli_cluster.sh create` can successfully create k8s cluster on aarch64.
```
$ ./libvirt/kcli_cluster.sh create
...
$ export KUBECONFIG=~/.kcli/clusters/peer-pods/auth/kubeconfig 
$ kubectl get nodes
NAME                   STATUS   ROLES           AGE    VERSION
peer-pods-ctlplane-0   Ready    control-plane   3m6s   v1.30.0
peer-pods-worker-0     Ready    worker          92s    v1.30.0
$ kubectl get pods -A
NAMESPACE       NAME …
```
> libvirt: support aarch64 arch VM

- .github/workflows/azure-podvm-image-build.yml
The kata build switched to oras, so this is a fix to use this in the azure podvm build as well.
Tested the workflow on a fork: https://github.com/mkulke/cloud-api-adaptor/actions/runs/10848485566/job/30105691657
> ci: Update azure podvm image build to use oras

- .github/workflows/e2e_libvirt.yaml
We've seen a few nightly and PR test runs fail due to e2e timeout. Looking into it our timeout for over a year has been fixed at 50m, but in that time we've added a lot of tests and do extra deployment stages, like trustee. Looking at a recently run around half of the 50m allowance was taking up just setting up the cluster before tests run. Whilst I think it would be good to try and refine/filter the tests we run and improve some of the slowness, in the short term increasing the timeout will help us avoid e2e failures and re-runs.
> workflows: Increase libvirt e2e test timeout

- src/cloud-api-adaptor/podvm-mkosi/Dockerfile.podvm
Remove the systemd "systemd-tmpfiles-setup.service" -delete
and tidy up docs and code to remove missing features
> Docker: podvm image: remove systemd tmpfiles setup delete

- src/cloud-api-adaptor/test/e2e/azure_test.go
- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/remote_attestation.go
Set initdata for remote attestation. allow kbs endpoint to be specified for manual test runs.
edit: tested on a [fork](https://github.com/mkulke/cloud-api-adaptor/actions/runs/10883561900/job/30197561320)
> ci: set initdata in remote-attestation test

- src/cloud-api-adaptor/test/e2e/libvirt_test.go
This test is causing lots of delays in merging PRs pre 0.10.0 release, so let's skip it for now.
> test/e2e: Skip nginx deployment test

- src/cloud-api-adaptor/test/e2e/assessment_helpers.go
- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/docker_test.go
- src/cloud-api-adaptor/test/e2e/ibmcloud_test.go
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/test/provisioner/docker/provision_common.go
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_kustomize.go
- src/cloud-api-adaptor/test/provisioner/kustomize.go
- src/cloud-api-adaptor/test/provisioner/libvirt/provision_common.go
Run the authenticated regsitry tests for libvirt cloud provider
Depends on #1931
> tests/e2e: Add auth registry libvirt tests

- src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.rhel
Updating the ARCH value on podvm-builder, so that it can pick up the respective architecture while it's being built.
Fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/2059
> podvm: Update hardcoded value for oras on podvm-builder

- .github/workflows/e2e_libvirt.yaml
This contain a fix for when printing the description of any test pod left on k8s. Also it will start collecting the journal messages from the workers (although I'm not sure yet how github will handle the many lines of logs....). Usually those log messages are useful to debug; not sure if it will for the peer pods case...I hope it helps.
> workflow/libvirt: improve debug step post-failure

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/go.sum
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/versions.yaml
- src/csi-wrapper/go.mod
- src/csi-wrapper/go.sum
- Following the bump of the guest-components and trustee in
https://github.com/kata-containers/kata-containers/pull/10313
to pick up the 0.10.0 and 0.10.1 versions of the
guest-components and trustee, and the kata containers 3.9.0
release, we need to bump versions to say in sync
> versions: Bump components to match kata 3.9.0

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
Update go mods and pin CAA image
> 0.10.0 release tasks

- src/cloud-api-adaptor/podvm/hack/download-image.sh
During some recent testing of bug fixes I spent quite a lot of time trying to understand why the fixes weren't having any effect on peer pods. After a while I found it was because although the registry version of the podvm image had been updated, when running `download-image.sh` it was just using the version I'd previously downloaded.
If we pass `--pull=always`, in the container create command, this should resolve that problem and it looks to be supported on docker and podman clis
> podvm: Make download-image.sh always pull

- .github/workflows/caa_build_and_push_per_arch.yaml
workflow: Partially revert actions/upload-artifact bump
The breaking change is causing problems for the multi-arch CAA
image build, so revert the bump from v2 to v4 there until we fix
the break this causes.
> Revert upload artifacts bump

- src/cloud-api-adaptor/cmd/agent-protocol-forwarder/main.go
- src/cloud-api-adaptor/docs/SecureComms.md
- src/cloud-api-adaptor/pkg/forwarder/forwarder.go
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/agent-protocol-forwarder.service
KataAgentNamespace parameter is controlling the namespace in which the pod runs (not the namespace in which the Kata Agent runs)
To make the code readable, it is renamed to PodNamespace
> APF: Rename KataAgentNamespace

- .github/workflows/azure-e2e-test.yml
The updated action doesn't allow the use of the same artifact name in a single wf run anymore.
> CI: adjust azure nightly workflow for actions/upload-artifact@4

- .github/workflows/caa_build_and_push_per_arch.yaml
- src/cloud-api-adaptor/hack/build.sh
Re-enable the upload-artifact and download-artifact version bumps and fix the workflow and script changes that meant there were non-unique file names being used.
The workflow running in my fork (with an additional commit to make the CAA build have a workflow dispatch for easier running): https://github.com/stevenhorsman/cloud-api-adaptor/actions/runs/11216651939/job/31176425619
> Bump artifact versions in caa multi arch build

- .github/workflows/azure-podvm-image-build.yml
This change will switch the nightly azure images to an mkosi-based image. The image will be used in the e2e tests and is hence becoming the reference image for azure, deprecating the packer image.
Successful test run with mkosi image [here](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/11070061926)
> azure: switch nightly podvm to mkosi-based image

- .lycheeignore
lychee is failing to follow
https://github.com/confidential-containers/cloud-api-adaptor/commits/main/
```
* [429] [https://github.com/confidential-containers/cloud-api-adaptor/commits/main/](https://github.com/confidential-containers/cloud-api-adaptor/commits/main/) | Failed: Network error: Too Many Requests
##[error]Process completed with exit code 2
```
So let's add that link to the list of exclusion.
> checklinks: add link to exclude

- .github/workflows/azure-podvm-image-build.yml
Due to a rebase fail, the workflow attempted to use the ubuntu mkosi build. Reverted to building using nix to stay close to the documented procedure. If we opt to use the ubuntu-packaged mkosi, more testing is required and we should change it everywhere.
In the mid-term this would make sense, because currently mkosi is marked as broken in nixos-24.05 and nix-unstable. the version we have pinned in the nix flake (v17) is rather old now.
Drive-by fix: sudo is not required for mkosi images on Ubuntu 22.04
> ci: fix azure nightly mkosi build

- .github/workflows/e2e_libvirt.yaml
In #2077 I forgot about pull_request_target not testing workflows in PRs and that self-hosted runners wouldn't have the gh cli installed, so this attempts to fix the workflows and install gh cli first.
I also set `GH_TOKEN` env in the step that uses `gh` based on the `gh help environment` doc that states:
GH_TOKEN: an authentication token for github.com API requests. Setting this avoids being prompted to authenticate.
Hopefully this is enough to get us back passing.
Note: I did find a few actions to do this, but they were only used by single digit projects, so I figured it would be safer to do it ourselves for now
*Disclaimer*: This assumes that `secrets.GITHUB_TOKEN` is created for self-hosted runners, which some guides hint is true, but I can't find concrete GitHub doc of this .
> workflows: Install gh cli on self-hosted runner

- .github/workflows/azure-podvm-image-build.yml
sry, for the stream of gh actions-related PRs. sadly, nested workflow invocations are pretty hard to test, even on forks.
Some workflow input/output glue didn't work anymore after switching to mkosi images, so the image id wasn't passed to the e2e test.
> ci: fix passing of image-id to e2e test

- .github/workflows/azure-e2e-test.yml
- .github/workflows/e2e_libvirt.yaml
We also need kustomize installed, which I think it needed on the self-hosted and github hosted runner
> workflows: Install kustomize on e2e workflows

- .github/workflows/azure-e2e-test.yml
- .github/workflows/e2e_libvirt.yaml
- src/cloud-api-adaptor/test/e2e/README.md
- src/cloud-api-adaptor/test/utils/checkout_kbs.sh
We have duplicate code in multiple e2e workflows
and manual doc instructions for checking out the KBS repo and switching to the correct branch. This both makes updating it prone to errors/omissions and means that if we make changes we can't test them in PRs due to the
`pull_request_target` limitation, so split these out into a single script we can call from elsewhere.
> test: Add checkout kbs helper script

- src/cloud-api-adaptor/test/utils/checkout_kbs.sh
Since we clone the repo we can use git to resolve a tag/branch to a sha. We probably want to avoid using gh cli in places where it's not required, because it involves setting secrets and makes executing tests more cumbersome. There could also be breakage if people specify a fork as KBS_REPO, since we use the gh cli with a hardcoded repository.
> test: don't use gh cli in kbs checkout

- .github/workflows/e2e_libvirt.yaml
- Fix kustomize install for non-root user by installing in a local
directory and then using sudo install to put it in /usr/local/bin/
This was tested in my fork with a non-root self-hosted runner in https://github.com/stevenhorsman/cloud-api-adaptor/actions/runs/11289806458/job/31400382940 so hopefully this is the last fix. Sorry for the missteps.
> Fix kustomize install for non root

- src/cloud-api-adaptor/cmd/cloud-api-adaptor/main.go
- src/cloud-api-adaptor/docs/SecureComms.md
Change the trustee operator namespace 
Add necessary initData to get SecureComms to work
> SecureComms: Fix needed following changes in other components

- src/cloud-api-adaptor/hack/verify-provenance.sh
This is prep-work to consume binaries with attestation from guest-components (#2074) The tool asserts that the OCI image has been built on the specified repo with a push on the main branch and the specified digest matches the git sha of the source code and of the workflow.
Note: such a verification is only solid when performed for an oci image w/ digest, since the tags are mutable. we want to resolve a tag to a digest uri and then verify and pull that digest uri. (oras resolve image:tag)
```bash
$ cd src/cloud-api-adaptor
$ ./hack/verify-provenance.sh \
-a ghcr.io/confidential-containers/guest-components/api-server-rest@sha256:0d2f600490caddb024c4e1e4c9d512c38a0d38e20131dd74702e6dfa4c6890b1 \
-r confidential-containers/guest-components \
-d d8da69072424e496486dfb5421a26f16ff2a7abf …
```
> util: verify provenance

- .github/workflows/azure-e2e-test.yml
- .github/workflows/e2e_libvirt.yaml
- Use Wainer's suggested approach of `sudo bash -s` rather than the separate install
- Also update Azure's e2e workflow with the fix
libvirt tested with forked workflow: https://github.com/stevenhorsman/cloud-api-adaptor/actions/runs/11295615233/job/31418883368
> workflow: Fix kustomize permission issue

- .github/workflows/azure-podvm-image-build.yml
Extend regions list to be able to use podvm in eastus2 region
> ci: add eastus2 region in azure nightly build

- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
- src/cloud-api-adaptor/pkg/util/cloud.go
- src/cloud-api-adaptor/pkg/util/cloud_test.go
- src/cloud-api-adaptor/test/e2e/assessment_helpers.go
- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/test/provisioner/libvirt/provision_common.go
- src/cloud-providers/libvirt/provider.go
- src/cloud-providers/types.go
Enable support for multiple PodVM images for libvirt provider with the merge of https://github.com/kata-containers/kata-containers/pull/10274
Fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/1282
**Working Scenario:**
Tried with the following busybox manifest:
```
apiVersion: v1
kind: Pod
metadata:
name: busybox
namespace: openshift-sandboxed-containers-operator
labels:
app: busybox
annotations:
io.katacontainers.config.hypervisor.image: "pppvm-nov-vol.qcow2"
spec:
containers:
- image: quay.io/prometheus/busybox
imagePullPolicy: Always
name: busybox-container
ports:
- containerPort: 80
protocol: TCP
restartPolicy: Always
runtimeClassName: kata-remote
```
Here the `pppvm-nov-vol.qcow2` is a valid libvirt volume and a podvm image is uploaded there.
CAA logs:
``` …
```
> libvirt: Enable multiple PodVM image scenario

- .github/workflows/lint.yaml
Github are updating their default ubuntu-latest runner from 22.04 to 24.04: https://github.com/actions/runner-images/issues/10636 The 24.04 image doesn't have terraform installed, so this breaks the terraform linting. Pin this at the old version to fix this.
The other linting jobs pass on 24.04, so pin these at 24.04, so we don't have a repeat of this in two years time (accidentally)
> ci: Pin the terraform lint runner

- src/cloud-api-adaptor/test/provisioner/trustee_kbs.go
- src/cloud-api-adaptor/versions.yaml
In https://github.com/confidential-containers/trustee/pull/521 I did some work to enable Trustee to work on s390x (without SE) and generally simplify deployments, such that overlays are only needed for ibm-se, not for x86/s390x in general.
This PR adapts us to use this approach.
> test: Update Trustee deployment to match the simplifed deployment overlays

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/podvm/go.mod
- src/cloud-providers/go.mod
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
- src/webhook/go.mod
make here is returning the following error:
go: download go1.22 for linux/amd64: toolchain not available
This change specifies the exact toolchain version (1.22.7) instead of
the language family version (1.22), a feature introduced in Go 1.21. It
ensures more precise toolchain resolution, improves reproducibility, and
avoids potential automatic upgrades to future versions.
Updating go.mod to use 1.22.7 instead.
> caa: fixing toolchain not available

- src/csi-wrapper/pkg/wrapper/podvmservice.go
A CSI driver may rely on the output of `ControllerPublishVolume` during the `NodeStageVolume` call.
Since the csi-wrapper simply creates a fake `ControllerPublishVolumeResponse`, information may be lost between the two calls.
Since the peerpod volume caches the real response, we can use this during the wrapper's `NodeStageVolume` to supply the driver with the real values.
> csi-wrapper: pass `PublishContext` from `ControllerPublishVolume` to `NodeStageVolume`

- src/csi-wrapper/pkg/wrapper/controllerservice.go
- src/csi-wrapper/pkg/wrapper/nodeservice.go
The peerpod volume custom resource is currently only created during the `CreateVolume` rpc of the controller service.
This endpoint is called by Kubernetes during the creation of a persistent volume claim (PVC) without an already existing persistent volume (PV).
All subsequent controller, node, and podvm csi-wrapper endpoints that interact with peerpod volumes CRs (e.g. `ControllerPublishVolume`) now assume that a peerpod volume already exists.
However, this is not the case if a PVC with a manually created, or already existing, PV is created.
This is required when statically provisioning a volume, for example, by the [azuredisk-csi-driver to consume a pre-existing disk through a PVC](https://learn.microsoft.com/en-us/azure/aks/azure-csi-disk-storage-provision#statically-provision-a-volume) …
> csi-wrapper: add support for creating peerpod volumes with manually created persistent volumes

- .github/workflows/e2e_libvirt.yaml
In github.com/confidential-containers/cloud-api-adaptor/pull/2074 we removed the RUST_VERSION env, but we still use it in The `Install rust toolchain` step which it needed to build the kbs client. I plan to remove this need very sooner by using the cached kbs client, but can't test those changes due to this error.
> workflow: e2e_libvirt fix rust version error

- .github/workflows/e2e_libvirt.yaml
- src/cloud-api-adaptor/test/e2e/README.md
- src/cloud-api-adaptor/test/provisioner/trustee_kbs.go
- src/cloud-api-adaptor/test/utils/checkout_kbs.sh
To save us storage space, time and the requirement
on the rust toolchain, we can pull down the cached
kbs-client rather than building it ourselves.
Update checkout_kbs.sh to use oras to pull the kbs-client
binary from the cache rather than building it.
> test/e2e: kbs: Use the cached kbs-client 

- .github/workflows/azure-e2e-test.yml
- .github/workflows/build.yaml
- .github/workflows/caa_build_and_push.yaml
- .github/workflows/caa_build_and_push_per_arch.yaml
- .github/workflows/csi_wrapper_images.yaml
- .github/workflows/e2e_libvirt.yaml
- .github/workflows/lint.yaml
- .github/workflows/webhook_image.yaml
This should speed up all go builds somewhat, since after reorganizing the repo, the cache that is set up by setup-go has not been working anymore:
```
Restore cache failed: Dependencies file is not found in
/home/runner/work/cloud-api-adaptor/cloud-api-adaptor.
```
drive-by fix: remove unnecessary steps from az oci image build
> ci: set golang cache key as **/go.sum glob

- .github/workflows/azure-e2e-test.yml
- .github/workflows/azure-nightly-build.yml
- .github/workflows/azure-podvm-image-build.yml
- .github/workflows/build-golang-fedora.yaml
- .github/workflows/build.yaml
- .github/workflows/commit-message-check.yaml
- .github/workflows/daily-e2e-tests-ibmcloud.yaml
- .github/workflows/daily-e2e-tests-libvirt.yaml
- .github/workflows/e2e_on_pull.yaml
- .github/workflows/links.yml
- .github/workflows/lint.yaml
- .github/workflows/publish_images_on_push.yaml
During some testing on my fork and sometimes when running PR testing I've found that I want to re-push whilst the existing CI runs are still going and I need to go in and cancel the old jobs first. This PR looks to address this.
Update our (non-callable) jobs to cancel if another push is done to the PR, or branch, or the unlikely event that another cron job is triggered in order to save time and costs running out of date jobs.
Approach based on stack overflow suggestion:
This is based on the following stack overflow suggestion: https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre which is the same approach that kata-containers uses.
Some of these feel a bit redundant as the jobs are quite short e.g. the …
> workflows: Cancel previous jobs if PR/branch is updated

- .github/workflows/e2e_libvirt.yaml
- src/cloud-api-adaptor/podvm/hack/download-image.sh
Workflow updates to support using the github-hosted runner. Specifically:
- docker image clean up due to reduced disk space on the runner. If we switch to oras for the podvm "publish" in future we might be able to reduce this, but after looking at it it's non-trivial, so doesn't seem worth adding support for this to the packer based podvm build, which we want to remove soon.
- Making the docker install optional to avoid clashes with the gh-provided version
If people feel we are ready to get switch over in this PR I'm happy to try it, but I thought that getting the changes in and stable first might de-risk the switch.
> GitHub hosted runner support

- .github/workflows/azure-e2e-test.yml
- .github/workflows/azure-podvm-image-build.yml
Those should not be set for callable workflows, since it's not supported to have concurrency groups set on both parent and children workflows.
https://github.com/github/vscode-github-actions/issues/135
> ci: disable concurrency for child workflows

- hack/Dockerfile.golang
- src/cloud-api-adaptor/Dockerfile
- src/cloud-api-adaptor/podvm-mkosi/Dockerfile.podvm
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.fedora
- src/peerpod-ctrl/Dockerfile
Fedora 39 is EoL in a couple of weeks and I've started seeing a few repo connection errors, so lets bump to F40 as the latest supported version.
> [!NOTE]
> Once `golang-fedora:1.22.7-39` is built, this will be followed up with
a bump of the builder_base as well.
> versions: Bump fedora base image to f40

- .github/workflows/e2e_libvirt.yaml
Now the pre-work changes have gone in in #2130,
we should be able to switch over to use the gh-hosted runner for libvirt e2e tests, so save Azure credits and make it easier to do testing on local forks.
Drive by fixes to add KBS debug info & add cluster clean-up support for "bare-metal" runners.
Tested in https://github.com/stevenhorsman/cloud-api-adaptor/actions/runs/11558678218/job/32171610739
> workflow: Switch libvirt e2e test to gh-runnner

- src/cloud-api-adaptor/test/e2e/assessment_helpers.go
- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/nginx_deployment.go
- src/cloud-api-adaptor/versions.yaml
Various refactors to the assessment helper and assessment runner to try and abstract out complexity of the large runner Assess section, to make it easier to read and reduce duplication
- Drive by fix to drop the rust version post the merge of #2121
> Assessment runner refactors

- src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.fedora
#2074 introduced the installation of the gh cli into the fedora podvm_builder Dockerfile using dnf. This isn't available for s390x and there isn't a released s390x version of the gh cli, so build it from source on that architecture.
> podvm_builder: Add s390x gh install support

- src/csi-wrapper/Dockerfile.csi_wrappers
In #2136 I completed missed that we'd forgotten to bump the base image for golang updates, so just updated the fedora version and broken things.
> versions: Fix csi-wrapper's base image

- src/cloud-providers/aws/provider.go
- src/cloud-providers/azure/provider.go
- src/cloud-providers/go.mod
- src/cloud-providers/util.go
- src/cloud-providers/util_test.go
aws: Avoid integer overflow when processing RootVolumeSize
azure: Verify the SSH key to ensure the file is using a supported  public key format
> Misc security related fixes for AWS and Azure

- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system-preset/30-coco.preset
- src/cloud-api-adaptor/podvm/files/etc/ocicrypt_config.json
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/agent-protocol-forwarder.service
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-agent.path
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-agent.service
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/multi-user.target.wants/kata-agent.path
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/multi-user.target.wants/kata-agent.service
- src/cloud-api-adaptor/versions.yaml
For sealed secrets to work kata-agent needs to connect to CDH, since it will repace env-variables in the container procoss with an unsealed confidential secret. A systemd path monitor watches for the CDH socket to appear to launch kata-agent.
Also, kata is writing the ocicrypt_config to /run in the agent process so we should not have bundle another in the podvm disk.
~Draft until https://github.com/kata-containers/kata-containers/pull/10481 is merged, need to bump kata to the new revision.~
> podvm: re-arrange service order for sealed secrets

- src/cloud-api-adaptor/docs/SecureComms.md
- src/cloud-api-adaptor/pkg/securecomms/sshproxy/sshproxy.go
- src/cloud-api-adaptor/pkg/securecomms/sshproxy/sshproxy_test.go
- src/cloud-api-adaptor/test/securecomms/test/httpClient.go
See:
- https://github.com/confidential-containers/cloud-api-adaptor/issues/2097
Support opening inbound ports in configurable network namespaces.
This allows opening an inbound port inside the pod network namespace of the podvm.
The traffic will be forwarded via the SecureComms ssh channel to the outbound at the worker node.
> SecureComms: Add support for inbound network namespace

- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_run_all.yaml
- src/cloud-api-adaptor/docs/SecureComms.md
- src/cloud-api-adaptor/libvirt/config_libvirt.sh
- src/cloud-api-adaptor/libvirt/e2e_matrix_libvirt.json
Modify the .github/workflow files to enable adding e2e tests for secure comms.
The added code is generalized to enable controlling the libvirt e2e testing matrix using a json file
> SecureComms: Add testing facility for e2e tests

- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/ibmcloud_test.go
- src/cloud-api-adaptor/test/e2e/nginx_deployment.go
- src/cloud-api-adaptor/test/e2e/versions.yaml
- src/cloud-api-adaptor/test/utils/test_versions.go
In some e2e tests, particularly the docker-provider ones, when you do multiple
runs we are likely to hit the rate limits of docker hub, so try switching to the
official mirrors of nginx and curl container images instead to reduce our usage of docker.io.
> Docker hub mirror switch

- .github/actionlint.yaml
- .github/workflows/actionlint.yaml
- .github/workflows/build.yaml
- .github/workflows/csi_wrapper_images.yaml
- .github/workflows/daily-e2e-tests-ibmcloud.yaml
- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_run_all.yaml
- .github/workflows/peerpod-ctrl_image.yaml
- .github/workflows/podvm_mkosi_image.yaml
- .github/workflows/test-images.yaml
- .github/workflows/webhook_image.yaml
On PRs that update anything in the workflows directory, add an actionlint run to validate our workflow files for errors and hopefully catch issues earlier.
Also fix the many issues we already have!
> workflow: Add actionlint workflows

- .github/workflows/azure-e2e-test.yml
- .github/workflows/azure-nightly-build.yml
- .github/workflows/build-golang-fedora.yaml
- .github/workflows/build.yaml
- .github/workflows/caa_build_and_push.yaml
- .github/workflows/caa_build_and_push_per_arch.yaml
- .github/workflows/commit-message-check.yaml
- .github/workflows/csi_wrapper_images.yaml
- .github/workflows/daily-e2e-tests-ibmcloud.yaml
- .github/workflows/e2e_on_pull.yaml
- .github/workflows/e2e_run_all.yaml
- .github/workflows/links.yml
- .github/workflows/peerpod-ctrl_image.yaml
- .github/workflows/podvm.yaml
- .github/workflows/podvm_binaries.yaml
- .github/workflows/podvm_builder.yaml
- .github/workflows/podvm_mkosi.yaml
- .github/workflows/test-images.yaml
- .github/workflows/webhook_image.yaml
Switch all our workflows to use the pinned ubuntu-24.04 runner rather than ubuntu-latest
> workflows: Switch to pin ubuntu runners

- .github/workflows/azure-e2e-test.yml
When the runners were fixed to 24.04 oras wasn't part of the base installation anymore.
> ci: install oras specifically for azure e2e tests

- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/initrd/mkosi.conf.d/fedora.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora.conf
We forgot to bump the mkosi version to fedora 40 in the mkosi config.
I triggered an azure e2e-test w/ an [fedora40 podvm image](https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/11894045370/job/33140667630#step:6:44) and it passed
> podvm-mkosi: bump to fedora 40

- .github/workflows/lib-codeql.yaml
- .github/workflows/lint.yaml
Ref: https://github.com/confidential-containers/confidential-containers/issues/46
The workflow was tested in my local branch and no errors reported
Fixes: #2024
> workflows: enable CodeQL checks

- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud_test.go
- src/cloud-api-adaptor/pkg/podnetwork/podnetwork_test.go
- src/cloud-api-adaptor/pkg/podnetwork/tunneler/routing/iptables_test.go
- src/cloud-api-adaptor/pkg/podnetwork/tuntest/tuntest.go
- src/cloud-api-adaptor/pkg/podnetwork/tuntest/util.go
- src/cloud-api-adaptor/pkg/securecomms/apic/apic_test.go
- src/cloud-api-adaptor/pkg/securecomms/ppssh/ppssh_test.go
- src/cloud-api-adaptor/pkg/securecomms/sshproxy/sshproxy_test.go
- src/cloud-api-adaptor/pkg/securecomms/wnssh/wnssh_test.go
- src/cloud-api-adaptor/test/securecomms/test/httpServer.go
- src/cloud-api-adaptor/test/securecomms/test/kbs.go
- src/cloud-api-adaptor/test/securecomms/test/namespacedHttpServer.go
Fixes: #2153
Seperate ListenAndServe() of test servers to perform Listen() in the same thread as used by the client that rely on the server port to be open.
Move to reuse tuntest network namespace test code rather that maintaining seperate network namespace test code for SecureComms.
> SecComms: Fix flaky tests

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/go.sum
- src/cloud-api-adaptor/versions.yaml
- src/csi-wrapper/go.mod
- src/csi-wrapper/go.sum
Bump kata-agent and go modules to use the 3.11.0 release version that will be used in CoCo 0.11.0
> Kata 3.11.0 bump

- src/cloud-api-adaptor/hack/verify-provenance.sh
- src/cloud-api-adaptor/podvm/Makefile.inc
The agent attestation can also be created by a workflow_trigger on main, so we have to allow that in the verification. There was also a bug in the routine that resolved a release tag to commit. kata doesn't tag their releases with a preceding 'v'.
> ci: fix verify-provenance for agent

- src/cloud-api-adaptor/aws/image/rhel/aws-rhel.pkr.hcl
- src/cloud-api-adaptor/aws/image/rhel/variables.pkr.hcl
- src/cloud-api-adaptor/aws/image/ubuntu/aws-ubuntu.pkr.hcl
- src/cloud-api-adaptor/aws/image/ubuntu/variables.pkr.hcl
- src/cloud-api-adaptor/azure/build-image.md
- src/cloud-api-adaptor/azure/image/rhel/azure-rhel.pkr.hcl
- src/cloud-api-adaptor/azure/image/rhel/variables.pkr.hcl
- src/cloud-api-adaptor/azure/image/ubuntu/azure-ubuntu.pkr.hcl
- src/cloud-api-adaptor/azure/image/ubuntu/variables.pkr.hcl
- src/cloud-api-adaptor/podvm-mkosi/Dockerfile.podvm
- src/cloud-api-adaptor/podvm/qcow2/misc-settings.sh
- src/cloud-api-adaptor/podvm/qcow2/rhel/qemu-rhel.pkr.hcl
- src/cloud-api-adaptor/podvm/qcow2/rhel/variables.pkr.hcl
- src/cloud-api-adaptor/podvm/qcow2/ubuntu/qemu-ubuntu.pkr.hcl
- src/cloud-api-adaptor/podvm/qcow2/ubuntu/variables.pkr.hcl
As mentioned in
https://github.com/confidential-containers/cloud-api-adaptor/issues/1951
the variable "DISABLE_CLOUD_CONFIG" was removed in this PR
> Retiring "DISABLE_CLOUD_CONFIG" variable

- src/cloud-api-adaptor/test/e2e/README.md
- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/azure_test.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/test/provisioner/trustee_kbs.go
this adds a test for image layer decryption to the libvirt & azure suite. The test currently uses a predefined image with hardcoded key + keyid. In the future we might want to do something more comprehensive, but it's crucial that we have CI coverage for this feature. 
note: we _do_ need the `io.containerd.cri.runtime-handler` annotation set for encrypted images, at least that was the case in my local tests.
> e2e: add encrypted image test

- src/cloud-api-adaptor/test/e2e/assessment_helpers.go
- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/azure_test.go
- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/docker_test.go
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/test/provisioner/trustee_kbs.go
The KbsKeyRelease tests have had errors setting the secret key, which are revealed when trace is on:
```
=== RUN   TestLibvirtKbsKeyRelease
time="2024-09-24T13:53:12Z" level=info msg="set key resource: ../../kbs/config/kubernetes/overlays/x86_64/key.bin"
time="2024-09-24T13:53:12Z" level=trace msg="./kbs-client --url http://192.168.122.140:31680 config --auth-private-key ../../kbs/config/kubernetes/base/kbs.key set-resource --path reponame/workload_key/key.bin --resource-file ../../kbs/config/kubernetes/overlays/x86_64/key.bin, output: Error: Request Failed, Response: \"{\\\"type\\\":\\\"https://github.com/confidential-containers/kbs/errors/SetSecretFailed\\\",\\\"detail\\\":\\\"Set secret failed: write local fs\\\"}\"\n"
```
I believe this is base the `reponame/workload_key` directory is …
> Kbs key release rework

- src/cloud-api-adaptor/versions.yaml
Pin the operator version to v0.11.0 to ensure that people deploying this release get a fixed and compatible version of the kata runtime deployed.
> version: Pin operator version

- src/cloud-api-adaptor/azure/README.md
- src/cloud-api-adaptor/docs/troubleshooting/README.md
The CAA documentation has been moved/deleted
from the CoCo website, so update the links and point to the old github source where no new version exists.
> doc: Update confidentialcontainers.org links

- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_initializer.go
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_kustomize.go
- src/cloud-api-adaptor/test/securecomms/test/kbs.go
- src/cloud-providers/libvirt/libvirt.go
Fix the 5 CodeQL security alerts we currently have
> Codeql security fixes

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
- update kustomize overlay image tags with HEAD sha refs
- bump the internal go.mod refs to 0.11.0
> 0.11.0 release

- src/cloud-api-adaptor/pkg/paths/paths.go
- src/cloud-api-adaptor/pkg/userdata/heuristics.go
- src/cloud-api-adaptor/pkg/userdata/provision.go
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/process-user-data.service.d/10-override.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/run-media-cidata.mount
- src/cloud-providers/docker/provider.go
- src/cloud-providers/util.go
The docker provider currently looks up a certain path to find a user data file. We can generalize this to use it also for config disks.
In mkosi the process-user-data service has a soft dependency on a mount unit that will mount a confidisk with the label "cidata". the service can then consume the userdata from the mount point.
This will enable mkosi x86_64 images to work on libvirt unmodified.
> process-user-data: create generic file provider for userdata

- src/cloud-api-adaptor/ibmcloud/image/import.sh
- src/cloud-api-adaptor/ibmcloud/image/login.sh
- src/cloud-api-adaptor/ibmcloud/image/multipart_upload.sh
Running import.sh on Mac required the following changes:
1. login.sh
- do not use mapfile
2. multipart_upload.sh
- reorder args for split command
3. import.sh
- added platform arg to download for different arch
- use tr instead of ,, variable expansion
> ibmcloud: make image import.sh work on Mac

- src/csi-wrapper/examples/aws/README.md
- src/csi-wrapper/examples/aws/dynamic-provisioning/pod.yaml
- src/csi-wrapper/examples/aws/dynamic-provisioning/storageclass.yaml
- src/csi-wrapper/examples/aws/rbac-ebs-csi-wrapper-podvm.yaml
Updating the csi driver to latest 1.37 release and RBAC.
Additionally the `peerpod` key is mandaotry in the storageclass definition, without which peerpodVolume CRD will not be created.
Fixes: #2144
> csi: Fix AWS example for CSI wrapper

- .github/workflows/azure-podvm-image-build.yml
Now the qcow2 build is part of the mkosi make image target, we need to install `qemu-utils`, so that the `qemu-img` tool is available
> azure: Install qemu-utils

- .github/workflows/stale.yaml
We have a small number of old PRs that look to be stale, so we can implement an auto-comment-then-close action on these.
The initial settings for this are to
- Mark all the PRs that have no activity for more than 90 days as stale.
- If there's no activity on the PR for 7 days, the PR will be automatically closed.
> workflows: Add workflow to close stale PRs

- src/webhook/Makefile
Install kustomize if not present when running undeploy
> webhook: Fix undeploy target

- .github/workflows/e2e_run_all.yaml
There are some potential permissions issues on the s390x runners, so skip these tests until Choi is online and available to help debug them.
> workflow: Temporarily skip the s390x e2e tests

- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_run_all.yaml
- src/cloud-api-adaptor/libvirt/e2e_matrix_libvirt.json
- src/cloud-api-adaptor/libvirt/kcli_cluster.sh
- src/cloud-api-adaptor/test/e2e/README.md
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/test/provisioner/libvirt/provision_common.go
- src/cloud-api-adaptor/versions.yaml
This is the minimum required to run e2e tests for libvirt on k8s configured with CRI-O.
* libvirt/kcli_cluster.sh can now provision k8s configured with CRI-O. Just need to export `CONTAINER_RUNTIME=crio`
* The e2e framework will handle the `container_runtime=crio` property in libvirt.properties
* Finally the changes on workflows to add a new job were made. Notice that the CRI-O will run with `continue-on-error` enabled for a while as we will be to fully check its stability by running on CI env.
Fixes #1981
> CI: run e2e tests for libvirt with CRI-O

- src/cloud-api-adaptor/test/e2e/fixtures/Dockerfile.curl-jq
This image is required to perform remote attestation tests which use api-server-rest. It will be built and pushed by the existing CI.
> e2e-test: Add curl-jq test image

- .github/workflows/e2e_run_all.yaml
I realised too late that adding a `false` to a list of or's does nothing. I wanted to preserve the code, but we can just revert, so it was pointless. Sorry!
>  workflow: Actually temporarily skip the s390x e2e tests

- src/cloud-api-adaptor/docs/addnewprovider.md
- src/cloud-api-adaptor/entrypoint.sh
- src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
- src/cloud-api-adaptor/test/e2e/README.md
- src/cloud-api-adaptor/test/provisioner/aws/provision_common.go
- src/cloud-api-adaptor/test/provisioner/azure/provision_common.go
- src/cloud-api-adaptor/test/provisioner/azure/provision_initializer.go
- src/cloud-api-adaptor/test/provisioner/docker/provision_common.go
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_common.go
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_ibmcloud.properties
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_initializer.go
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_kustomize.go
- src/cloud-api-adaptor/test/provisioner/libvirt/provision_common.go
This is a prerequisite of https://github.com/confidential-containers/cloud-api-adaptor/issues/688
This PR introduces a parameter to specify the tunnel type for pod networking. If this parameter is not set, the default VXLAN is used.
Some e2e test provisioners do not have a parameter for VXLAN port. This PR also introduces a parameter for it in such providers.
> Kustomize: parameterize tunnel type

- src/cloud-api-adaptor/test/e2e/common_suite.go
For the cri-o tests, the error we get back for
unauthorized access to a private image is
different to containerd, so add logic to handle
this.
> test/e2e: Fix cri-o auth tests

- src/cloud-api-adaptor/ibmcloud/README.md
- src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md
Added doc with streamlined instructions to set up the peer pod demo environment using an OpenShift cluster.
Also added references and made small corrections to the README.
> ibmcloud: PeerPod demo instructions for OpenShift clusters

- src/cloud-api-adaptor/Makefile
- src/cloud-api-adaptor/Makefile.defaults
- src/cloud-api-adaptor/hack/build.sh
- src/cloud-api-adaptor/versions.yaml
Support build cloud-api-adaptor (except podvm) on aarch64/arm64 platform, and it's tested on both x86_64 and aarch64 servers.
Podvm build support is excluded as it's recently changed from local build to ORAS cached artifacts to get guest-component in #2074. Will rebase with latest v0.11.0 changes later.
E2E test is able to run on aarch64/arm64 server with changes in #2193, plus operator's arm64 build and local built podvm (v0.9.0 and v0.10.0, and by packer and mkosi):
```
$ kubectl get pods -o wide
NAME             READY   STATUS    RESTARTS   AGE     IP           NODE                 NOMINATED NODE   READINESS GATES
busybox-remote   1/1     Running   0          6m16s   10.244.1.8   peer-pods-worker-0   <none>           <none>
$ kubectl exec pods/busybox-remote -- uname -srim
Linux …
```
> Makefile: support aarch64/arm64 build

- src/cloud-providers/libvirt/libvirt.go
- src/cloud-providers/libvirt/libvirt_test.go
Create domainXML for aarch64/arm64 arch in cloud-provider/libvirt, and check iommu=on for virtio device only in test.
This patch is similar to 63a002cc25b29627653f41e3f1d5a4dc4b71c534, and ARM CCA CVM will be added later like 4422f14fc6f3a4ffba5571cb049c3207cfe83630, when it's ready. This will initially support non-CCA workloads and eventually allow the creation of a Realm on a local/remote host.
go test on aarch64/arm64 host: 
```
$ LIBVIRT_URI="qemu+ssh://taoxu01@192.168.122.1/system?no_verify=1" go test -v
=== RUN   TestCloudInit
temp file: /tmp/CloudInit-12504980.iso--- PASS: TestCloudInit (0.01s)
=== RUN   TestInMemoryCopier
--- PASS: TestInMemoryCopier (0.00s)
=== RUN   TestLibvirtConnection
2024/12/06 11:27:46 [adaptor/cloud/libvirt] Created libvirt connection
--- PASS: …
```
> providers/libvirt: add support for aarch64 host

- .github/workflows/azure-e2e-test.yml
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/afterburn-checkin.service.d/10-override.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/process-user-data.service.d/10-override.conf
- src/cloud-api-adaptor/test/e2e/azure_test.go
~depends on #2187 to be merged first~
According to initdata spec the digest needs to be truncated/padded according to the requirements of the TEE. for az tpm we use the sha256 bank of TPM for initdata.
This will fix a bug when a initdata body with alg=sha384+ was used and the PCR8 value in the TEE evidence will not be extended, since you cannot extend sha256 w/ a digest that's bigger than 32 bytes.
An e2e test for azure was added to assert this behaviour.
> podvm: truncate initdata digest to 32 bytes on az

- .github/workflows/podvm_mkosi.yaml
- src/cloud-api-adaptor/podvm-mkosi/Makefile
Remove the push of the builder and binaries during the mkosi build, but just output them to the local directory always to simplify the flow and remove the need to use crane to pull them down.
> workflows: mksoi: Remove mid-build caching

- .github/workflows/e2e_run_all.yaml
Revert the changes that skipped s390x testing so we can debug the runners now that @BbolroC is back to help us.
Unfortunately we can't test it on fork runners as in a fresh environment it all passed, so we specifically need to ensure that the runners shared with other CoCo projects are cleaned up to run our workfloads
> S390x runner testing

- src/cloud-api-adaptor/test/e2e/nginx_deployment.go
The nginx deployment test isn't completely stable. Sometimes it fails and we don't know yet whether it's a legit bug on peer pods or not. With this PR I don't solve that problem either, as I still don't know the roots of the problem, however, it improves the test that it will run the `Teardown()` function even when `WithSetup()` failed. We have this suspect that the left nginx deployment might be messing with the next tests, so this change will at least solve that problem (if it's really a problem). Regardless, tests should always delete their resources at the execution end.
There is one thing that I'd like to implement, which is, do not run Teardown() if not running on CI. In other words, if I'm running the test locally and it fails I want to have the deployment running so I can inspect. …
> test/e2e: improve nginx deployment test

- .github/workflows/podvm_mkosi.yaml
There is a restriction introduced in new revisions of ubuntu runners. This change allows user ns to be created, so mkosi can be built rootless.
> podvm-ci: un-restrict user ns on ubuntu 24.04

- .github/workflows/e2e_run_all.yaml
The get stable libvirt e2e tests we need to just use the large runner, so switch the runner label over
> workflows: Switch s390x e2e runner

- .github/workflows/podvm_mkosi.yaml
A default directory is set workflow-wide that will only work after checkout, hence the sysctl call fails.
> ci: re-order sysctl step for podvm_mkosi wf

- src/webhook/tests/e2e/webhook_tests.bats
The third webhook test is frequently failing (see #2179), so skip this until there is time to investigate and fix it.
> webhook: Skip flakey e2e test

- .github/workflows/e2e_libvirt.yaml
- src/cloud-api-adaptor/libvirt/config_libvirt.sh
In newer versions of Ubuntu running `pip3 install kcli` results in the following error:
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
...
```
Solutions seem to be either use a virtual environment, install the package with apt (which isn't available for us as we need), or use pipx if installing an application, which we are.
This attempts to use the logic to install with pipx, including a shell reload at the end of the script to force the PATH to be updated
> libvirt: Support Ubuntu 23.04+

- src/cloud-api-adaptor/libvirt/config_libvirt.sh
I experimented with moving the shell reload straight after the pipx ensurepath when discussing this with Magnus, but in the GHA once merged this doesn't seem to be working as the reload means the script ends, so we need to move this back.
> libvirt: Fix shell reload

- .github/workflows/azure-podvm-image-build.yml
- src/cloud-api-adaptor/podvm-mkosi/Makefile
- src/cloud-api-adaptor/podvm-mkosi/README.md
Sorry, I didn't do the full job when merging the builder and binaries phase, so left some references to
fedora-binaries-builder in the code and docs (I was going to run both in parallel, but decided it
made more sense to switch and only did a partial job). This should fix the azure nightly build (and we still need to work
on integrating that with the other workflows I guess).
> podvm_mkosi: Remove remaining references to builder

- src/cloud-api-adaptor/libvirt/config_libvirt.sh
- src/cloud-api-adaptor/libvirt/e2e_matrix_libvirt.json
- src/cloud-api-adaptor/test/e2e/assessment_helpers.go
- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/test/e2e/main_test.go
- src/cloud-api-adaptor/test/provisioner/libvirt/provision_common.go
- src/cloud-api-adaptor/test/provisioner/provision.go
Support testing SecureComms without KBS
See
- https://github.com/confidential-containers/cloud-api-adaptor/issues/2096
Should be merged after #2065
> SecureComms: E2e Test SecureComms without KBS

- src/cloud-api-adaptor/test/e2e/assessment_helpers.go
- src/cloud-api-adaptor/test/e2e/assessment_runner.go
Print logs of failed pods and CAA in case of failures to help with debugging in the case of failures
> test/e2e: Add debug of failed pods

- src/cloud-api-adaptor/test/e2e/libvirt_test.go
Based in the test analysis done for 18 days of nighty tests in https://github.com/confidential-containers/cloud-api-adaptor/issues/1831#issuecomment-2541712756 the only containerd test failures we saw were:
- `TestLibvirtCreatePeerPodAndCheckEnvVariableLogsWithImageOnly` - three times
- `TestLibvirtCreatePeerPodAndCheckWorkDirLogs` - four times
- `TestLibvirtCreatePeerPodAndCheckEnvVariableLogsWithDeploymentOnly` - twice
Although the chances of failure for each of these tests is < 25%, we want to reduce the re-runs required, so if we skip these we should have more stable CI tests. It should also be noted that most of the failures were seen on the packer built images. This is probably just chance, but might indicate that the peer pod boot speed is related and we should re-evaluate again …
> tests/e2e: Skip tests after analysis

- src/cloud-api-adaptor/pkg/paths/paths.go
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system/process-user-data.service.d/10-override.conf
- src/cloud-api-adaptor/podvm/files/media/cidata/.gitignore
- src/cloud-providers/docker/provider.go
For docker provider we use systemd container which mounts /run as a tmpfs volume.
This mounting of /run happens after docker has bind mounted the userdata file inside the container and consequently the userdata file is no longer accessible.
This commit changes the path of the userdata file to not use `/run` for the docker provider.
> docker: Fix userdata bind mount path inside the container

- src/cloud-api-adaptor/aws/image/rhel/aws-rhel.pkr.hcl
> podvm: aws: set shutdown_behavior to terminate

- .github/workflows/azure-podvm-image-build.yml
- .github/workflows/podvm_mkosi.yaml
- src/cloud-api-adaptor/podvm-mkosi/Dockerfile.mkosi
- src/cloud-api-adaptor/podvm-mkosi/Makefile
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/initrd/mkosi.conf.d/fedora.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora.conf
There is a problem when running mkosi on a github ubuntu runner, the images will build successfully, but the EFI partition will not be setup in a way that libvirt can boot from it.
The packages on a generic github runner aren't really predictable, to make an mkosi build more reproducible, we can launch mkosi in a fedora container with `--tools-tree=default`.
Since this implies running a user ns within a container, we need to configure a docker buildx builder that allows this and run mkosi with a special flag in the Dockerfile.
Another problem has been introduced in f40 in recent days. With a bump from 6.12.8-100.fc40 => 6.12.9-100.fc40 in fedora40, there is a regression for peerpod, tests will not pass. We need further investigation about that, but to unblock the CI we can downgrade to …
> CI: build mkosi in docker + downgrade podvm to f39

- .github/workflows/podvm_smoketest.yaml
This workflow will build a podvm image, launch a vm and then attempt to address it via the kata agent API.
This should give earlier signals of podvm problems and can run on PRs.
nb: the wf is running on 22.04 b/c libvirt struggles with OVMF_CODE_4M firmware that is default on ub 24.04.
> ci: add podvm-smoketest workflow

- src/cloud-api-adaptor/Makefile
When the arm support was added in #2194 it seems
to have broken ppc64le builds: e.g.
https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/12747057891 so try and fix this
> caa: Re-add ppc64le support to build

- docs/Release-Process.md
- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/go.sum
- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/versions.yaml
- src/csi-wrapper/go.mod
- src/csi-wrapper/go.sum
Bump kata-containers, guest-components and trustee versions in response to them being bumped in the kata-containers 3.13.0 release.
> Kata 3.13.0 dependency bump

- src/cloud-providers/util.go
Use logger for consistent output, instead of fmt.Printf()
> Use logger instead of fmt.Printf()

- src/cloud-api-adaptor/gcp/README.md
Current rendering is wrong with most of content inside a block code. Also took the opportunity to adopt the same standard within all blocks.
> gcp: fix block code in README

- src/cloud-api-adaptor/podvm-mkosi/Makefile
This patch fixes the debug image build issue on s390x. 
Currently, I cannot build a debug podvm image on s390x. The following command just build a production podvm image.
```
sudo make image-debug
```
I guess this issue was revealed by this recent change.
https://github.com/confidential-containers/cloud-api-adaptor/commit/6e25be399498f9353e14cb826dba72cd877bdb89#diff-0578158244ea494f1ad5e1970ee5560d1cf6bfc62fd70243bd3a46280a237a14
> podvm: Fix debug image build issue on s390x

- src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md
- src/webhook/Makefile
1. Changed the instructions to use latest ghcr.io podvm image.
2. Fixed Makefile to download correct OS version of cmctl.
3. Other small corrections and improvements to the doc.
> ibmcloud: Fixes and improvements to ROKS demo instructions

- .golangci.yaml
Clean up warnings from `golangci-lint` during CI workflow
> ci: remove deprecated golangci-lint warnings

- src/cloud-providers/ibmcloud-powervs/provider.go
This PR ensures that the timeout used to wait the VM to be active is not used for getting the VM ip.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/2177
> ibmcloud-powervs: fix timeout creating PowerVS (DHCP request)

- .github/workflows/caa_build_and_push_per_arch.yaml
- .github/workflows/peerpod-ctrl_image.yaml
Due to an
[issue](https://github.com/actions/runner-images/issues/11471) with Ubuntu 24.04 20250120.5.0 runner image
we have been seeing failures in our multi-arch images for the last few days which is blocking the release. I assume that the issue is something related to qemu, so downgrade to 22.04 until this issue is resolved.
> workflow: Downgrade github runner

- hack/release-helper.sh
- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
- src/csi-wrapper/go.mod
- src/peerpod-ctrl/go.mod
Update go mods and pin CAA image
> 0.12.0 release tasks

- src/cloud-api-adaptor/test/e2e/aws_test.go
- src/cloud-api-adaptor/test/provisioner/aws/provision_common.go
A couple of changes I needed to pass the e2e tests for AWS.
> test/aws: disable, enable and fix tests

- src/cloud-api-adaptor/docs/troubleshooting/nydus-snapshotter.md
- src/cloud-api-adaptor/gcp/README.md
GKE uses `discard_unpacked_layers=true` for optimizations, starting with version 1.27. This can cause `failed to extract layer sha256:xxx: not found` errors with PeerPods. The note explains disabling this flag in containerd to avoid issues.
> gcp: add note on discard_unpacked_layers for GKE

- .github/workflows/e2e_docker.yaml
- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_run_all.yaml
- hack/ci-e2e-debug-fail.sh
This is based on Wainer's PR #1965, with some work done to make it fit into the new e2e world
> Docker provider e2e test

- src/cloud-api-adaptor/ibmcloud/image/import.sh
- src/cloud-api-adaptor/podvm/hack/download-image.sh
Currently, download-image.sh uses pull=always when it creates the container for the specified docker image, which fails if the image version is not available in the remote registry. Adding a pull option will allow users to import a docker image that is only available locally by specifying --pull=never.
> podvm: Add --pull option to import.sh and download-image.sh

- src/cloud-api-adaptor/entrypoint.sh
- src/cloud-providers/gcp/manager.go
- src/cloud-providers/gcp/provider.go
- src/cloud-providers/gcp/types.go
This PR allows users to set the PodVM disk type for GCP instead of using the hardcoded pd-standard.
Also cleaned up some CLI options to be more consistent across providers, by dropping extra gcp- prefix.
> gcp: allow users to set podvm disk-type and align CLI options

- .github/workflows/e2e_on_pull.yaml
Currently the e2e tests only are authorised if they contain `test_e2e_libvirt`, but now we have the docker provider tests we might want to trigger them in isolation too.
> workflow: Add test_e2e_docker trigger

- src/cloud-api-adaptor/podvm-mkosi/Dockerfile.podvm_docker_provider
- src/cloud-providers/docker/provider.go
Pod VM containers launched by Docker provider fail to start with the following error at least on my environment.
```
Feb 04 06:21:30 908cee3eddf7 agent-protocol-forwarder[208]: /usr/local/bin/agent-protocol-forwarder: error running a service *forwarder.daemon: failed to set up pod network: failed to set up tunnel "vxlan": failed to check the existence of iptables chain "peerpod-OUTPUT": running [/usr/sbin/iptables -t raw -S peerpod-OUTPUT 1 --wait]: exit status 3: modprobe: FATAL: Module ip_tables not found in directory /lib/modules/5.14.0-503.22.1.el9_5.x86_64
Feb 04 06:21:30 908cee3eddf7 agent-protocol-forwarder[208]: iptables v1.8.10 (legacy): can't initialize iptables table `raw': Table does not exist (do you need to insmod?)
```
This PR fixes this problem by using [iptables …
> docker: Use iptables-wrapper in pod VM container image

- src/cloud-providers/aws/provider.go
- src/cloud-providers/azure/provider.go
- src/cloud-providers/ibmcloud-powervs/provider.go
> Fix incorrect assignment of Image ID

- src/cloud-api-adaptor/ibmcloud/image/import.sh
Choosing the first bucket in an instance wil not work if the first bucket is not in the target region. This PR fixes the selection logic to choose the first bucket that is in the target region.
> ibmcloud: fix import.sh bucket selection

- src/cloud-api-adaptor/entrypoint.sh
- src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_common.go
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_initializer.go
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_kustomize.go
- src/cloud-providers/ibmcloud/manager.go
- src/cloud-providers/ibmcloud/provider.go
- src/cloud-providers/ibmcloud/provider_test.go
- src/cloud-providers/ibmcloud/types.go
Added the DISABLECVM property to the ibmcloud adaptor config and to the caa-provisioner-cli properties for ibmcloud.
> ibmcloud: add option to enable/disable confidential VM

- src/cloud-providers/aws/provider.go
I've been primarily working with AWS and created this PR to enhance log messages. The updates improve traceability by incorporating instance IDs and names where relevant.
Also, removed some extraneous whitespace and did some minor refactoring.
> AWS: improve logging for clarity

- src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md
Disable confidential VM for now, since it's not working yet.
> ibmcloud: disable confidential VM in ROKS demo doc

- src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md
1. Replaced kubectl with oc (bc Openshift)
2. Added caution about deleting cluster without deleting workload.
> ibmcloud: Improvements to ROKS demo instructions

- src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
- src/cloud-providers/libvirt/libvirt.go
- src/cloud-providers/libvirt/manager.go
- src/cloud-providers/libvirt/provider.go
- src/cloud-providers/libvirt/types.go
SEV has been deprecated in kata by the AMD team and wasn't supported for on-prem in CAA, so we can remove it.
> libvirt: Remove SEV code

- .github/workflows/e2e_libvirt.yaml
We are seeing the e2e_libvirt test jobs running out of space on the runner. From a quick google, there are a few suggested directories that can be removed to help with this.
> workflow: e2e_libvirt running out of space

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/go.sum
- src/cloud-api-adaptor/podvm-mkosi/Dockerfile.mkosi
- src/cloud-api-adaptor/podvm-mkosi/Makefile
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/initrd/mkosi.conf.d/fedora.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-s390x.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.repart/00-esp.conf
- src/cloud-api-adaptor/versions.yaml
- src/csi-wrapper/go.mod
- src/csi-wrapper/go.sum
Attempt to bump to F40. Since F39 is EOL since 2024-11-26. Which will conflict with 165e989
> mkosi: fix Fedora GPG key issue in mkosi build

- .github/workflows/podvm_smoketest.yaml
1s delay between claiming an IP address and launching kata-agent is not enough in some cases, resulting in a flaky test.
Changing the delay before attempting to connect to the agent to 5s seems to resolve the issue. Running the test in a loop with 25+ launches didn't produce a failure, while doing the same with the original 1s delay, will result in "connection refused" failure after a couple of runs.
> ci: add delay on podvm smoke-test

- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/main_test.go
- src/cloud-api-adaptor/test/provisioner/trustee_kbs.go
- src/cloud-api-adaptor/test/utils/checkout_kbs.sh
Support certificates in KBS and aa/cdh
fixes: #2300
> test/e2e: Update testcases for HTTPS KBS

- .github/workflows/e2e_run_all.yaml
With a recent change in the s390x CoCo runners, we now can only build the mkosi image on larger s390x runner (that runs on a different physical system), so update the workflow to reflect this.
> workflow:e2e_run_all: Switch s390x image build runner

- .github/workflows/podvm_mkosi.yaml
This is the other half of  6bd4e3297f98fe033560759e07f580758a05fa02 that I missed earlier in #2312 :(
With a recent change in the s390x CoCo runners,
coco-runner-02 (not tagged with s390x-large) is now running ubuntu 24.04. As documented in #2310, there are currently issues with the s390x building on ubuntu 24.04, so in the short-term, we should stop the mkosi build running on those systems and therefore switch to the s390x-large runner, which is still on 22.04.
> workflow: podvm_mkosi: Switch s390x image build runner

- src/cloud-api-adaptor/podvm/qcow2/misc-settings.sh
- src/cloud-api-adaptor/podvm/qcow2/rhel/qemu-rhel.pkr.hcl
- src/cloud-api-adaptor/podvm/qcow2/rhel/variables.pkr.hcl
Fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/2304
Extending the CLOUD_PROVIDER check for installing iptables which fixes the APF failure seen with libvirt provider.
Also, wrapping `setup-nat-for-imds` service only for `azure, aws and generic` providers.
> Update CLOUD_PROVIDER for iptables installation

- src/cloud-api-adaptor/pkg/adaptor/proxy/proxy.go
Print the error instead of the address in the log message when retrying a failed agent proxy connection attempt.
> adaptor: log error causing agent proxy connection failure

- .github/workflows/podvm_mkosi.yaml
- src/cloud-api-adaptor/podvm-mkosi/Makefile
This PR runs mkosi inside a Fedora-based container for building images. This would provide a more consistent environment and prevent issues caused by upgrading Ubuntu on GHA self-hosted runners.
The change has been verified on a Ubuntu 24.04 runner: https://github.com/BbolroC/cloud-api-adaptor/actions/runs/13654124912/job/38169137973
I confirmed that the change works on both Ubuntu 22.04 and Ubuntu 24.04.
Fixes: #2310
> podvm_mkosi: Use container to run mkosi on s390x

- src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md
Add instructions for enabling CVM mode for development purposes and update ROKS cluster version to latest.
> ibmcloud: add confidential mode instructions to ROKS demo doc

- src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md
IBM Cloud doesn't allow traffic between a cluster and its VPC by default anymore, so we need to add another security group to allow it to communicate with the peer pod VSIs.
> ibmcloud: add another security group in ROKS demo instructions

- src/cloud-providers/ibmcloud-powervs/manager.go
This PR uses the correct env var to initialize PowerVS processors.
Fixes: #2323
> ibmcloud-powervs: fix processors config

- .github/workflows/e2e_run_all.yaml
- .github/workflows/podvm_mkosi.yaml
As mentioned in #2310, this commit reverts #2312 and #2313 to use all `s390x` runners again for building libvirt test artifacts.
FYI: the libvirt e2e test should run on the `s390x-large` runner due to resource constraints. 
CC: @stevenhorsman @ldoktor
> GHA: Use 390x runners again for building libvirt test artifacts

- src/cloud-api-adaptor/Makefile
- src/cloud-api-adaptor/podvm/Dockerfile.podvm.rhel
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.rhel
- src/cloud-api-adaptor/versions.yaml
- Bump protoc to 3.16.0 because 3.15.0 is not available on s390x
- Ensure jq is installed in the builder image
- Ensure yq is in PATH in the builder image
- Ensure subscription credentials are passed to packer when running in a container
> Fixes for RHEL/s390x PODVM builds

- src/cloud-api-adaptor/Makefile.defaults
- src/cloud-api-adaptor/ibmcloud/image/Makefile
- src/cloud-api-adaptor/podvm/Dockerfile.podvm
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder
- src/cloud-api-adaptor/podvm/README.md
- src/cloud-api-adaptor/podvm/qcow2/rhel/variables.pkr.hcl
- src/cloud-api-adaptor/podvm/qcow2/ubuntu/variables.pkr.hcl
- src/cloud-api-adaptor/versions.yaml
- src/cloud-api-adaptor/vsphere/image/ubuntu/scripts/createconfig.sh
- src/csi-wrapper/Dockerfile.csi_wrappers
See if we can bump to a 24.04 base for the packer
podvm image as 20.04 is going EoL
> versions: Attempt to use Ubuntu 24.04 in packer

- src/cloud-api-adaptor/podvm-mkosi/Makefile
Starting from version 3.16.0, `protoc` changed the architecture name for s390x from `s390x` to `s390_64`.
This was addressed in #2194 but was not applied to `Dockerfile.podvm_binaries.fedora`.
This PR updates the configuration accordingly.
> podvm: Set PROTOC_ARCH for s390x to s390_64

- src/cloud-api-adaptor/ibmcloud/IMPORT_PODVM_TO_VPC.md
- src/cloud-api-adaptor/ibmcloud/cluster/README.md
- src/cloud-api-adaptor/ibmcloud/cluster/variables.tf
- src/cloud-api-adaptor/ibmcloud/image/import.sh
- src/cloud-api-adaptor/ibmcloud/image/push.sh
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_common.go
- src/csi-wrapper/examples/ibm/README.md
Ubuntu 20.04 is EoL soon, so switch our defaults to 22.04 for self-managed cluster creation (as s390x doesn't have a 24.04 image yet). Also update the import.sh to reflect that packer builds a 24.04 image now (again s390x doesn't support 24.04 label, so we need to fudge it a bit here).
> ibmcloud: Move away from Ubuntu 20.04

- src/cloud-api-adaptor/test/e2e/azure_test.go
- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/remote_attestation.go
The cert values weren't set in all places where initdata is used, which broke e2e tests on azure. The templating was put into its own fn to make this more obvious.
> e2e: fix initdata templating

- src/cloud-providers/ibmcloud-powervs/provider.go
This PR sets the PodVM name maximum length to 47 instead of 63.
Fixes: #2333
> ibmcloud-powervs: Set PodVM name maximum length to 47

- src/cloud-api-adaptor/docs/registries-authentication.md
- src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
- src/cloud-api-adaptor/install/rbac/peer-pod.yaml
- src/cloud-api-adaptor/install/yamls/caa-pod.yaml
- src/cloud-api-adaptor/libvirt/README.md
- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
- src/cloud-api-adaptor/pkg/adaptor/k8sops/node.go
- src/cloud-api-adaptor/test/e2e/assessment_helpers.go
- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/docker_test.go
- src/cloud-api-adaptor/test/e2e/ibmcloud_test.go
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/test/provisioner/docker/provision_common.go
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_kustomize.go
- src/cloud-api-adaptor/test/provisioner/kustomize.go
- src/cloud-api-adaptor/test/provisioner/libvirt/provision_common.go
This PR initializes auth.json with the imagePullSecrets listed on the pod and service account.
Fixes: #2231
> CAA: add support to look up imagePullSecrets for pods

- src/cloud-api-adaptor/ibmcloud-powervs/image/prereq.sh
Update the device-mapper-devel package version to fix the image build.
Fixes: #2338
> ibmcloud-powervs: fix podvm image build

- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/go.sum
- src/cloud-api-adaptor/test/provisioner/azure/provision_common.go
- src/cloud-api-adaptor/test/utils/checkout_kbs.sh
- src/cloud-api-adaptor/versions.yaml
- src/csi-wrapper/go.mod
- src/csi-wrapper/go.sum
Bump kata and guest-components to match the 3.15.0 release that will form the basis of CoCo 0.13.0
> 3.15.0 dependency bump

- src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md
The confiential-containers-system ns is already deleted by the caa-provisioner-cli uninstall command. Also made a couple of other minor improvements in the doc.
> ibmcloud: remove unneeded ns delete from ROKS doc

- src/cloud-api-adaptor/test/provisioner/provision.go
The caa-provisioner-cli -action=uninstall command fails to uninstall the controller manager because the github path is wrong. Once fixed, the following delete peerpod-ctrl deployment also fails because some of the resources are not found.
> provisioner: fix caa-provisioner-cli uninstall failures

- src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_common.go
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_initializer.go
- src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_kustomize.go
Add new CLI property to set the INITDATA field in the peer-pods-cm configmap.
> ibmcloud: add INITDATA to CLI peerpod properties

- src/cloud-api-adaptor/libvirt/kcli_cluster.sh
- src/cloud-api-adaptor/versions.yaml
This PR updates kcli to the latest to fix a CI issue for Ubuntu 24.04 on s390x. See the following issues:
- https://github.com/karmab/kcli/issues/793
- https://github.com/karmab/kcli/issues/796
> versions: Bump kcli to 99.0.202504041449

- src/cloud-providers/ibmcloud-powervs/provider.go
Avoid passing entire instance while fetching VM IP and modify getFromDHCPServer function name.
Fixes: #2367
> ibmcloud-powervs: pass instance ID instead of instance while fetching VM IP

- .github/workflows/azure-podvm-image-build.yml
- src/cloud-api-adaptor/hack/podvm-measure.sh
For mkosi images on x86_64 we can retrieve the golden measurements for a podvm image by booting it with swtpm and scraping serial output.
We then store the measurement record in OCI and add an attestation for it.
note: this workflow will not run on a PR branch. a test run on a fork run can be seen [here](https://github.com/mkulke/cloud-api-adaptor/actions/runs/14310191072)
> podvm: provide attested measurements in OCI

- src/cloud-api-adaptor/test/e2e/azure_test.go
- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/test/e2e/remote_attestation.go
Adding an end-to-end (E2E) test case to validate system behavior when invalied initdata body is provided.
> tests/e2e : Add initdata related test cases, invalied initdata 

- src/cloud-api-adaptor/podvm/qcow2/misc-settings.sh
The need for libtdx has been removed, so we can drop this code
> podvm: Remove libtdx library install

- src/cloud-api-adaptor/pkg/adaptor/k8sops/node.go
- src/cloud-api-adaptor/pkg/adaptor/server.go
Log the error instead of exiting when Kubernetes configuration is missing.
Similar to what already happens in `cloud.go`:
https://github.com/confidential-containers/cloud-api-adaptor/blob/main/src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go#L137
> caa: Enable running without Kubernetes

- src/cloud-providers/ibmcloud/provider.go
Update ibmcloud api provider to use image id provided in pod annotation to override the configured image id.
```
annotations:
io.katacontainers.config.hypervisor.image: "<your image id>"
```
> ibmcloud: pod annotation to override image id

- src/cloud-api-adaptor/podvm/qcow2/build-s390x-se-image.sh
- src/cloud-api-adaptor/podvm/qcow2/rhel/qemu-rhel.pkr.hcl
- src/cloud-api-adaptor/podvm/qcow2/rhel/variables.pkr.hcl
Currently in s390x SE image building flow we use --no-verify. I've removed that tag and SE image is built with signing cert, CA certs and crls. These are downloaded in operator build flow if the image is created manually these files can be placed inside files directory along with HKD.
> podvm: remove --no-verify 

- src/cloud-api-adaptor/podvm/Dockerfile.podvm.rhel
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_binaries.rhel
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.rhel
Add missing xz dependency and default values for BUILDER_IMG and BINARIES_IMG in rhel Dockerfiles.
For make command like:
```
PODVM_DISTRO=rhel ACTIVATION_KEY=<key> ORG_ID=<org id> IMAGE_URL=<path to base image>.qcow make podvm-builder podvm-binaries podvm-image
```
> podvm: add dependency and default images to rhel Dockerfiles

- .github/workflows/links.yml
The lychee action isn't working properly, so
skip the job until we have a CoCo wide strategy
see https://github.com/confidential-containers/confidential-containers/issues/301
> ci: Skip checklinks job

- .github/workflows/peerpod-ctrl_image.yaml
- src/cloud-api-adaptor/Makefile
This PRs adds ibmcloud_powervs to the list of providers to be added while building and publishing the caa image.
> caa: publish the cloud-api-adaptor image with ibmcloud_powervs provider

- .github/workflows/commit-message-check.yaml
Dependabot doesn't follow the current rules for
commit message subject, so skip this to avoid manual intervention each time
> workflows: dependabot commit check skip

- hack/Dockerfile.golang
- src/cloud-api-adaptor/Dockerfile
- src/cloud-api-adaptor/podvm-mkosi/Dockerfile.mkosi
- src/cloud-api-adaptor/podvm-mkosi/Dockerfile.podvm_docker_provider
- src/cloud-api-adaptor/podvm-mkosi/Makefile
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_binaries.fedora
- src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.rhel
- src/peerpod-ctrl/Dockerfile
- Bump image tag.
- Update dnf commands to the newer syntax.
- Add necessary dependencies that are not included in the new image.
> docker: bump fedora image to 41

- src/cloud-api-adaptor/alibabacloud/README.md
The new community image id is built on top of commit 2e14647b289242b2ce9adfd8ff1cadbfec15b443, which brings some changes about heuristic detective logic of alibaba cloud. The old version relies on the network and the new one aligns with the code.
> alibaba: update Community image id

- src/cloud-api-adaptor/test/e2e/assessment_helpers.go
- src/cloud-api-adaptor/test/e2e/assessment_runner.go
The current logic returns on some branches of processing each command, so if multiple commands are passed it, it could skip some of the tests and thereby give a false positive
It is not erroring out when pod is not found and skipping testcommand execution
enhanced to overcome above issues
Signed-off-by: PrakashMuddana **<Jyoti.Prakash.Muddanna@ibm.com>**
> tests/e2e:running all testcommands, erroring if pod not found

- .github/workflows/podvm_binaries.yaml
- .github/workflows/podvm_builder.yaml
- .github/workflows/test-images.yaml
We don't use docker hub in any of our
workflows and there are rate limiting issues,
so remove the secrets and logic to login
> workflows: Remove docker hub support

- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
This PR checks whether one VM IP is available before indexing array to avoid crashing in extreme situations.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/2453
> caa: handle unavailable VM IPs

- src/cloud-api-adaptor/entrypoint.sh
- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
- src/cloud-providers/azure/manager.go
- src/cloud-providers/azure/provider.go
- src/cloud-providers/azure/types.go
Add root volume size configuration for Azure VMs to match AWS/GCP functionality.
Set Environment variable ROOT_VOLUME_SIZE in peer-pods-cm, defaults to 0, which
implies the default image disk size.
This is the splitting of the following PR:
https://github.com/confidential-containers/cloud-api-adaptor/pull/2212
> azure: implement root-volume-size support

- src/cloud-api-adaptor/ibmcloud-powervs/README.md
- src/cloud-api-adaptor/ibmcloud-powervs/image/prereq.sh
agent-protocol-forwarder was failing to start with the error `"iptables": executable file not found in $PATH` while setting up the pod network.
```
agent-protocol-forwarder: error running a service *forwarder.daemon: failed to set up pod network: failed to set up tunnel "vxlan": failed to initialize iptables: exec: "iptables": executable file not found in $PATH
```
This PR adds instructions to install iptables during the build to fix the issue.
> ibmcloud-powervs: install iptables during podvm image build

- .github/workflows/azure-nightly-build.yml
The updated workflow permission in b02ef1ea need further adjustments, since azure-e2e-test is invoked as a nested workflow and requires `id-token: write` permissions.
> e2e-test: add id-token: write when invoking wf's

- src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md
A VPE gateway security group rule is needed to allow podvms to access services like icr.io.
> ibmcloud: add VPE gateway SG rule to ROKS setup doc

- src/cloud-api-adaptor/Makefile
- src/cloud-api-adaptor/cmd/az-copy-image/README.md
- src/cloud-api-adaptor/cmd/az-copy-image/main.go
The tool allows users to copy the community gallery images into their image galleries. This is necessary because we do not publish the community gallery images in all available regions.
> azure: add az-copy-image tool

- .github/workflows/podvm_smoketest.yaml
- src/cloud-api-adaptor/cmd/cloud-api-adaptor/main.go
- src/cloud-api-adaptor/entrypoint.sh
- src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
- src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
- src/cloud-api-adaptor/pkg/forwarder/forwarder.go
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora-debug.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/repart.d/30-scratch.conf
- src/cloud-api-adaptor/podvm-mkosi/mkosi.skeleton/usr/lib/systemd/system-preset/30-coco.preset
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/kata-agent.service
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/multi-user.target.wants/scratch-storage.service
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/scratch-storage.service
- src/cloud-api-adaptor/podvm/files/usr/local/bin/luks-encrypt-storage
- src/cloud-api-adaptor/podvm/files/usr/local/bin/setup-scratch-storage
- src/cloud-api-adaptor/podvm/hack/smoke_test.sh
The disk may be LUKS encrypted depending on the option. Default is to continue using tmpfs based storage for container images
Two new global parameters are introduced
- ENABLE_SCRATCH_DISK: A boolean to indicate if scratch space (partition) need to be created from the root disk.
- ENABLE_SCRATCH_ENCRYPTION: A boolean to indicate if LUKS encryption needs to be performed for the scratch space. The key is random and stored in tmpfs.
These two parameters are available as `enable-scratch-disk` and `enable-scratch-encryption` respectively inside the pod VM in daemon.json file.
In the current implementation, the disk storage comes from the primary root disk. If `ENABLE_SCRATCH_DISK` option is enabled, then a new partition is created consisting of all the freespace in the root disk, using …
> Add disk storage support for container image store

- src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md
Add tip for using Trusted Profile instead of an API key in the ROKS setup documentation.
> ibmcloud: add tip to use Trusted Profile to ROKS setup doc

- src/cloud-api-adaptor/versions.yaml
Bump the umoci package to v0.5.0 to reflect the latest umoci release and security fixes
Umoci 0.5.0 security fix:
```
A security flaw was found in the OCI image-spec, where it is possible to
cause a blob with one media-type to be interpreted as a different media-type.
As umoci is not a registry nor does it handle signatures, this vulnerability
had no real impact on umoci but for safety we implemented the now-recommended
media-type embedding and verification. https://github.com/advisories/GHSA-mc8v-mgrf-8f4m
```
Reference release: https://github.com/opencontainers/umoci/releases/tag/v0.5.0
> versions: Bump umoci to 0.5.0

- .github/workflows/podvm_smoketest.yaml
- src/cloud-api-adaptor/go.mod
- src/cloud-api-adaptor/go.sum
- src/cloud-api-adaptor/podvm/files/etc/agent-config.toml
- src/cloud-api-adaptor/podvm/files/etc/systemd/system/confidential-data-hub.service
- src/cloud-api-adaptor/test/e2e/libvirt_test.go
- src/cloud-api-adaptor/versions.yaml
- src/csi-wrapper/go.mod
- src/csi-wrapper/go.sum
Bump the kata-agent and runtime to 3.18.0
along with the matching guest-components
and trustee, to pick up the new image pull
in cdh approach
> versions: Bump to kata 3.18.0

- .github/workflows/e2e_libvirt.yaml
- .github/workflows/podvm.yaml
- src/cloud-api-adaptor/Makefile
- src/cloud-api-adaptor/podvm/Dockerfile.podvm
- src/cloud-api-adaptor/versions.yaml
We keep hitting rate limits in the kcli install, so bump to a version that should include https://github.com/karmab/kcli/commit/d640e9ecc5bba5138df7f6c81e4cb04a8c3de00c in an attempt to help this.
> versions: Bump kcli

- src/cloud-api-adaptor/docs/instance-selection.md
- src/cloud-api-adaptor/pkg/adaptor/cloud/cloud.go
- src/cloud-providers/util.go
- src/cloud-providers/util_test.go
This helps in the following cases:
- When GPU count is not available. For example in Azure, the GPU count is not available via the API used to get the cpu/mem details
- When a specific instance type must be used irrespective of the resource spec in the pod manifest
Also add a documentation on the instance selection flow.
> cloud: Prioritise instance type annotation for selection

- src/cloud-api-adaptor/podvm-mkosi/Makefile
- Bump the container image being used to fedora:41 as 40 is EOL
- Install the pinned version of mkosi from git, as the dnf version isn't compatible
> podvm_mkosi: Update s390x run_mkosi_in_container

- src/cloud-api-adaptor/test/e2e/libvirt_test.go
Add init pod test to libvirt e2e as part of https://github.com/confidential-containers/cloud-api-adaptor/issues/1604
> test/e2e: Add DoTestPodWithInitContainer to libvirt

- src/cloud-api-adaptor/aws/image/Dockerfile
- src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
- src/cloud-api-adaptor/test/provisioner/aws/provision_common.go
- src/cloud-providers/aws/ec2.go
- src/cloud-providers/aws/manager.go
- src/cloud-providers/aws/types.go
Amazon recommends workloads to use temporary credentials to access AWS whenever possible, in its best practices document (https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#bp-workloads-use-roles). The current caa implementation for AWS, however, relies only on the access key ID and secret access key to establish connection to AWS. It doesn't work with temporary credentials such as these generated by AWS STS API because it's missing one parameter: the session token. This PR fixes that problem by passing the session token (AWS_SESSION_TOKEN) all the way down to the cloud-api-adaptor program at launch time.
---
I faced that problem while working on enabling e2e daily CI for AWS. I've configured openID connect in AWS …
> aws: add support to use temporary credentials

- src/webhook/Makefile
very often I'm hitting timeouts when deploying CAA locally on kcli, let's increase these timeouts. This change should not increase deployment in correct cases.
> webhook: Increase cert deployment timeout

- src/cloud-providers/aws/provider_test.go
- src/cloud-providers/docker/docker.go
- src/cloud-providers/docker/provider.go
- src/cloud-providers/docker/provider_test.go
- src/cloud-providers/go.mod
Fixed the following unit tests errors:
```
2025-08-25T14:50:32.7895498Z === RUN   TestDeleteInstance/DeleteInstance
2025-08-25T14:50:32.7896042Z --- FAIL: TestDeleteInstance (0.00s)
2025-08-25T14:50:32.7896704Z     --- FAIL: TestDeleteInstance/DeleteInstance (0.00s)
2025-08-25T14:50:32.7897523Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2025-08-25T14:50:32.7898472Z 	panic: runtime error: invalid memory address or nil pointer dereference
2025-08-25T14:50:32.7905250Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x326ccb6]
```
```
2025-08-25T14:50:33.1288007Z --- FAIL: Test_dockerProvider_CreateInstance (0.00s)
2025-08-25T14:50:33.1290716Z     --- FAIL: Test_dockerProvider_CreateInstance/Test_CreateInstance (0.00s)
```
> cloud-providers: fix AWS and docker unit tests

- src/cloud-api-adaptor/entrypoint.sh
If an option that accepts a string with multiple comma-separated parameters like AZURE_IMAGE_SIZES contains spaces, the entrypoint parsing takes the spaces as separate options and therefore 1) AZURE_INSTANCE_SIZES will not have all the instances added, and 2) the remaining options coming after will be discarded.
> entrypoint: ensure that comma-separate options don't have spaces

- .github/workflows/actionlint.yaml
- .github/workflows/azure-e2e-test.yml
- .github/workflows/azure-podvm-image-build.yml
- .github/workflows/build-golang-fedora.yaml
- .github/workflows/build.yaml
- .github/workflows/caa_build_and_push.yaml
- .github/workflows/caa_build_and_push_per_arch.yaml
- .github/workflows/csi_wrapper_images.yaml
- .github/workflows/e2e_aws.yaml
- .github/workflows/e2e_docker.yaml
- .github/workflows/e2e_libvirt.yaml
- .github/workflows/e2e_run_all.yaml
- .github/workflows/lib-codeql.yaml
- .github/workflows/links.yml
- .github/workflows/lint.yaml
- .github/workflows/peerpod-ctrl_image.yaml
- .github/workflows/podvm.yaml
- .github/workflows/podvm_binaries.yaml
- .github/workflows/podvm_builder.yaml
- .github/workflows/podvm_mkosi.yaml
- .github/workflows/podvm_smoketest.yaml
- .github/workflows/scorecard.yaml
- .github/workflows/stale.yaml
- .github/workflows/test-images.yaml
- .github/workflows/webhook_image.yaml
otherwise dependabot won't update the version string.
includes https://github.com/confidential-containers/cloud-api-adaptor/pull/2565
> Actions: Use x.y.z version string for gh actions

- src/cloud-api-adaptor/Dockerfile
- src/cloud-api-adaptor/docs/addnewprovider.md
- src/csi-wrapper/Dockerfile.csi_wrappers
- src/peerpod-ctrl/Dockerfile
Update the builder base of the Docker files
to pick up both the 1.24.6 golang based image
Depends on #2534
> versions: Bump the builder image

- src/cloud-api-adaptor/test/e2e/assessment_runner.go
- src/cloud-api-adaptor/test/e2e/common.go
- src/cloud-api-adaptor/test/e2e/common_suite.go
- src/cloud-api-adaptor/test/e2e/ibmcloud_test.go
Enhanced `WithSecretBinding` and `WithPVCBinding` to handle multi-container scenario.
Enhanced `NewPVC` to handle different type of volumes by using PVCOptions. 
Introduced a delay function while creating PVC, as it takes few seconds to bound to Persistent Volume. Without this delay we get a warning in PodEvents as the PVC will not be ready before the pod creation. Which causes the testcases to fail because of a transient warning.
> test/e2e: adding pvc options and refactoring pvc/secret binding

- src/cloud-api-adaptor/podvm/files/etc/systemd/system/scratch-storage.service
fixes #2516
The scratch-storage unit was always enabled, as the ConditionPathExists= clause was not put in the `[Unit]` hierarchy. Hence large images couldn't be pulled: A very small dmcrypt partition was created (~200M) and mounted as backing storage for the pod sandbox.
> podvm: place scratch-space condition correctly

- .github/workflows/azure-podvm-image-build.yml
- .github/workflows/azure-podvm-release.yml
- src/cloud-api-adaptor/ci-infra/azure/release.tf
- src/cloud-api-adaptor/ci-infra/azure/variables.tf
PodVM release images should be built on the CI using a workflow. This is preferable over manual steps, but also useful since we have provenance attestation for the measurements. The measurements can only be verified to be valid if we generate them on the CI.
The required terraform infra has been added, which allows github actions to write to the image gallery that holds release images.
A azure-podvm-release.yml workflow has been added that overrides a couple of defaults in the azure-podvm-build.yml workflow.
drive-by-fix: the podvm build workflow has been adjusted to expand input/secret/vars fields in a step's env block (to avoid injections problems).
(the workflow has been tested in a fork [here](https://github.com/mkulke/cloud-api-adaptor/actions/runs/17946385520))
> ci: add azure workflow + infra for podvm release

- .github/workflows/e2e_docker.yaml
- .github/workflows/e2e_libvirt.yaml
- hack/ci-helper.sh
The docker e2e test has been consistently failing
and Wainer spotted that sometimes there is a space issue, so port the clean up we have in the libvirt e2e tests to try it out.
To make this easier to modify in future, refactor this out of the `pull_request_target` triggered workflows
> workflows: e2e_docker: Clean up space

- .github/workflows/daily-e2e-tests.yaml
- .github/workflows/e2e_aws.yaml
- .github/workflows/e2e_on_pull.yaml
- .github/workflows/e2e_run_all.yaml
- hack/ci-e2e-aws-cleanup.sh
- src/cloud-api-adaptor/test/e2e/README.md
- src/cloud-api-adaptor/test/e2e/aws_test.go
- src/cloud-api-adaptor/test/provisioner/aws/provision_common.go
Continuing [part 1](https://github.com/confidential-containers/cloud-api-adaptor/pull/2274) in this PR I've got:
- more failing tests are disabled
- securing the AWS account by leveraging OIDC short-lived credentials. The job will effectively run if `AWS_IAM_ROLE_ARN` secret is configured in the repository and some magic done on AWS account (https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-aws). Contain two commits that are being reviewed in https://github.com/confidential-containers/cloud-api-adaptor/pull/2551 that adds support to use temporary credentials
- added a post step to run clean up code for the case where the e2e tests were interrupted or crashed and the native teardown routine didn't run. Long-term I'm considering to remove that …
> Introduce CI for AWS - part 2

- .github/workflows/azure-podvm-image-build.yml
The wrong env was used when constructing the imageid, making the podvm deployments fail.
> e2e-test: fix azure community gallery name

- .github/workflows/e2e_run_all.yaml
To that AWS CI will be triggered on nightly (currently it's getting skipped).
> workflows: trigger AWS on 'schedule' event
