confidential-containers/cloud-api-adaptor

docs/addnewprovider.md

Basic info to add a new provider

---

docs/DEVELOPMENT.md

Update instructions to build the binaries

---

.github/workflows/build.yaml
docs/addnewprovider.md

This added a Github workflow to build the project for each cloud
provider on pull requests.

github: add workflow to build the project

---

pkg/adaptor/hypervisor/aws/service.go
pkg/adaptor/hypervisor/ibmcloud/service.go
pkg/adaptor/hypervisor/libvirt/service.go

Fix incorrect error checking for empty namespace in annotation

---

ibmcloud/README.md

Updated README to reflect splitting of ansible playbook.
Step now runs two new playbooks consecutively.
Fixes #21
Signed-off-by: [Jonah-Farrow] <jonah.farrow@ibm.com>

doc: update manual ansible playbook step

---

pkg/adaptor/hypervisor/aws/ec2.go
pkg/adaptor/hypervisor/aws/server.go
pkg/adaptor/hypervisor/aws/service.go

Fix linter errors in aws implementation

---

ibmcloud/README.md
ibmcloud/TROUBLESHOOTING.md

- Moved existing troubleshooting tip into separate doc
- Added tip with regard to User Policy-related issues
Fixes #40
Signed-off-by: Dave Hay <david_hay@uk.ibm.com>

Add separate troubleshooting guide

---

cmd/cloud-api-adaptor/main.go
pkg/adaptor/hypervisor/libvirt/libvirt.go

Fixes: #63
while here, add libvirt to help msg

libvirt: create data-dir path if not exist

---

pkg/adaptor/hypervisor/aws/server.go
pkg/adaptor/hypervisor/ibmcloud/server.go
pkg/adaptor/hypervisor/libvirt/server.go

if exist bind may fail
Fixes: #65

pkg: clean socket if exist

---

cmd/cloud-api-adaptor/main.go
ibmcloud/README.md
ibmcloud/terraform/start-cloud-api-adaptor/ansible/apply_playbook.yml
pkg/adaptor/hypervisor/ibmcloud/server_test.go
pkg/adaptor/hypervisor/ibmcloud/service.go
pkg/adaptor/hypervisor/ibmcloud/types.go

ibmcloud: add resource group para

---

pkg/adaptor/forwarder/forwarder.go
pkg/adaptor/forwarder/forwarder_test.go
pkg/adaptor/hypervisor/aws/service.go
pkg/adaptor/hypervisor/ibmcloud/service.go
pkg/adaptor/hypervisor/libvirt/service.go

- Introduce max retry count of connection establishment  for socket forwarding
- Stop socket forwarder at shutdown
Fixes #75

Stop socket forwarder when reaching max retry count

---

pkg/adaptor/hypervisor/aws/service.go

Fix AWS VM tag key name

---

aws/README.md
aws/image/.gitignore
aws/image/Makefile
aws/image/aws-ubuntu.pkr.hcl
aws/image/copy-files.sh
aws/image/files/etc/containers/policy.json
aws/image/files/etc/systemd/system/agent-protocol-forwarder.service
aws/image/files/etc/systemd/system/kata-agent.service
aws/image/files/etc/systemd/system/multi-user.target.wants/agent-protocol-forwarder.service
aws/image/files/etc/systemd/system/multi-user.target.wants/kata-agent.service
aws/image/files/etc/systemd/system/multi-user.target.wants/run-kata\x2dcontainers-shared-containers.mount
aws/image/files/etc/systemd/system/multi-user.target.wants/run-kata\x2dcontainers.mount
aws/image/files/etc/systemd/system/run-kata\x2dcontainers-shared-containers.mount
aws/image/files/etc/systemd/system/run-kata\x2dcontainers.mount
aws/image/files/usr/bin/skopeo
aws/image/variables.pkr.hcl

aws: Add support for AWS AMI generation using packer tool

---

cmd/cloud-api-adaptor/main.go
go.mod
go.sum
pkg/adaptor/hypervisor/aws/server.go
pkg/adaptor/hypervisor/aws/service.go
pkg/adaptor/hypervisor/ibmcloud/server.go
pkg/adaptor/hypervisor/ibmcloud/service.go
pkg/adaptor/hypervisor/libvirt/server.go
pkg/adaptor/hypervisor/libvirt/service.go
pkg/adaptor/hypervisor/types.go
pkg/adaptor/proxy/proxy.go
pkg/adaptor/proxy/proxy_test.go
pkg/adaptor/proxy/service.go

proxy: fetch imageName from digest

---

ibmcloud/terraform/start-cloud-api-adaptor/ansible/apply_playbook.yml
ibmcloud/terraform/start-cloud-api-adaptor/main.tf
ibmcloud/terraform/start-cloud-api-adaptor/variables.tf

ibmcloud: add cri_runtime_endpoint variable

---

cmd/cloud-api-adaptor/main.go
pkg/adaptor/hypervisor/aws/service.go
pkg/adaptor/hypervisor/aws/types.go

aws: Make EC2 launch template name configurable

---

install/README.md
install/pre-install-payload/scripts/run-hyp.sh
install/runtime-payload/config/configuration-remote.toml
install/runtime-payload/scripts/run-aws.sh
install/runtime-payload/scripts/run-ibmcloud.sh
install/yamls/ccruntime-peer-pods.yaml

install: Update images based on latest changes

---

.github/workflows/build.yaml

ci: fix test issue due to sudo usage

---

Dockerfile
aws/README.md
install/yamls/ccruntime-peer-pods-in-pod.yaml
install/yamls/kustomization.yaml

add missing kustomization.yaml file
update runtime-payload tag
modify Dockerfile to avoid shipping unnecessary files
**while here, also minor fix to aws docs**
Fixes: #170

install: fix caa pod deployment

---

install/overlays/aws/kustomization.yaml
install/overlays/libvirt/kustomization.yaml

install: disable suffix generation for configmap and secrets

---

pkg/adaptor/hypervisor/aws/ec2.go

aws: fix usage of aws-region command line param

---

install/overlays/libvirt/kustomization.yaml
install/yamls/ccruntime-peer-pods-in-pod.yaml

by passing the ssh private key to the container
Fixes: #186 
**this is WIP as i didn't test it doesn't break the other setup yet**

install: allow libvirt ssh key authorization

---

ibmcloud/image/.gitignore
ibmcloud/image/Makefile

ibmcloud: Embed pause container image

---

README.md
install/README.md

1. fix incorrect link to webhook doc
2. Add link to install guide in the main readme
3. Fix minor formatting issues

doc: update readme

---

ibmcloud/image/.gitignore
ibmcloud/image/Makefile

Fixes #206
Signed-off-by: Yohei Ueda <yohei@jp.ibm.com>

ibmcloud: Build static libseccomp for kata-agent

---

ibmcloud/terraform/cluster/ansible/kube-playbook.yml

Fixes #208
Signed-off-by: Dave Hay <david_hay@uk.ibm.com>

ibmcloud: Define GOPATH for Ansible build

---

ibmcloud/terraform/cluster/ansible/kube-playbook.yml

Fixes #213
Signed-off-by: Dave Hay <david_hay@uk.ibm.com>

ibmcloud: refactor the way that GOPATH is set

---

cmd/cloud-api-adaptor/main.go
go.mod
go.sum
pkg/adaptor/hypervisor/registry/vsphere.go
pkg/adaptor/hypervisor/vsphere/server.go
pkg/adaptor/hypervisor/vsphere/service.go
pkg/adaptor/hypervisor/vsphere/types.go
pkg/adaptor/hypervisor/vsphere/vsphere.go

This pull request contains the patch which is the initial peer pod cloud-api-adapter for vsphere vcenter.

vsphere: Initial CAA implementation

---

pkg/forwarder/interceptor/interceptor.go

For CSI mounts, the source dir will not be copied from worker to Peer Pod VM (under `/run/kata-containers/shared`), so the source dirs (such as `/var/lib/kubelet`, `/var/lib/kubelet/pods/*/volumes/kubernetes.io~csi/*/mount`) doesn't exist on Peer Pod VM.
Just try to check the mount sources of OCI spec in forwarder interceptor, so that we can create empty dir for non-existing mount source before creating containers.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/128
Signed-off-by: Lei Li [cdlleili@cn.ibm.com](mailto:cdlleili@cn.ibm.com)

pkg/forwarder: create non-existing mount source dir

---

libvirt/image/Makefile

libvirt: embed pause container image in the pod VM image

---

azure/image/Makefile

azure: embed pause container image in the pod VM image

---

entrypoint.sh
install/overlays/vsphere/cri_runtime_endpoint.yaml
install/overlays/vsphere/kustomization.yaml

vsphere: Add container image support for deployment

---

docs/DEVELOPMENT.md
install/overlays/aws/kustomization.yaml

-aws image docs
-devel docs
-remove deprecated template aws option

Various minor fixes

---

hack/build.sh
install/pre-install-payload/hack/build.sh
install/runtime-payload/hack/build.sh

in all image build scripts
see: https://github.com/docker/cli/issues/954
Fixes: #242

build.sh: clean manifest cache after push

---

entrypoint.sh
install/overlays/aws/kustomization.yaml

aws: fix aws provider cloud image

---

cmd/cloud-api-adaptor/main.go
pkg/adaptor/hypervisor/ibmcloud/shim_test.go
pkg/podnetwork/podnetwork_test.go
pkg/podnetwork/tunneler/tunneler.go
pkg/podnetwork/tunneler/vxlan/podnode.go
pkg/podnetwork/tunneler/vxlan/tunnel_test.go
pkg/podnetwork/tunneler/vxlan/workernode.go
pkg/podnetwork/tuntest/tuntest.go
pkg/podnetwork/workernode.go

podnetwork: Parameterize VXLAN port and ID

---

pkg/adaptor/hypervisor/vsphere/vsphere.go

vsphere: Set data center before looking for template

---

entrypoint.sh

install: fix optionals var expansion in entrypoint.sh

---

azure/README.md

Some information about routing table and adding routing table to VNET subnet was missing.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/270

Azure: update readme

---

webhook/pkg/mutating_webhook/remove-resourcespec.go

webhook: Remove duplicate golang imports

---

entrypoint.sh
install/overlays/azure/cri_runtime_endpoint.yaml
install/overlays/azure/kustomization.yaml

This adds CAA image for azure provider
Fixes: #226

Azure: Create caa image

---

aws/image/Makefile
azure/image/Makefile
libvirt/image/Makefile

Fix dependency for skopeo and umoci

---

azure/image/Makefile
azure/image/azure-ubuntu.pkr.hcl
azure/image/variables.pkr.hcl

resource_group is the azure standard.
Fixes: #298

azure: Rename resource_group_name to resource_group

---

pkg/adaptor/hypervisor/vsphere/server.go
pkg/adaptor/hypervisor/vsphere/service.go
pkg/adaptor/hypervisor/vsphere/vsphere.go

vsphere: Use session manager to issue keep alive pings to vcenter

---

install/README.md
install/yamls/ccruntime-peer-pods-in-pod.yaml

caa-peer-pods: Run as Daemonset

---

webhook/config/manager/manager.yaml
webhook/config/webhook/manifests.yaml
webhook/docs/INSTALL.md
webhook/hack/webhook-deploy.yaml

webhook: update webhook manifest to avoid deadlock

---

Dockerfile
entrypoint.sh

also use exec form in Dockerfile
Fixes: #289

entrypoint: exec cloud-api-adaptor process

---

entrypoint.sh

install: fix optionals parameter handling in the entrypoint script

---

entrypoint.sh

These secrets can be passed in as environment variables.
Fixes: #313

all: remove secrets from entrypoint.sh

---

install/overlays/libvirt/ssh_mount.yaml

libvirt: adapt ssh_mount to DaemonSet

---

pkg/adaptor/hypervisor/aws/service.go
pkg/adaptor/hypervisor/azure/service.go
pkg/adaptor/hypervisor/ibmcloud/service.go
pkg/adaptor/hypervisor/libvirt/service.go
pkg/adaptor/hypervisor/vsphere/service.go
pkg/util/hvutil/hvutil.go
pkg/util/hvutil/hvutil_test.go

hvutil: Truncate too long instance name

---

aws/image/copy-files.sh
aws/image/files/etc/agent-config.toml
aws/image/files/etc/systemd/system/kata-agent.service
azure/image/copy-files.sh
azure/image/files/etc/agent-config.toml
azure/image/files/etc/systemd/system/kata-agent.service
ibmcloud/image/files/etc/agent-config.toml
ibmcloud/image/files/etc/systemd/system/kata-agent.service
libvirt/image/copy-files.sh
libvirt/image/files/etc/agent-config.toml
libvirt/image/files/etc/systemd/system/kata-agent.service

Add agent image section to stop signature verification being enabled

Default agent config

---

pkg/adaptor/hypervisor/vsphere/server.go
pkg/adaptor/hypervisor/vsphere/service.go
pkg/adaptor/hypervisor/vsphere/vsphere.go

vsphere: Reauthorize session when session is invalidated due to error

---

.github/workflows/lint.yaml
Makefile
pkg/adaptor/hypervisor/libvirt/libvirt.go

Signed-off-by: Sam Yuan <yy19902439@126.com>

CI: enhance with go check and escapes detect

---

cmd/cloud-api-adaptor/main.go
entrypoint.sh
install/overlays/aws/kustomization.yaml
pkg/adaptor/hypervisor/aws/imds.go
pkg/adaptor/hypervisor/aws/server.go
pkg/adaptor/hypervisor/aws/service.go
pkg/adaptor/hypervisor/aws/types.go

if not explicitly set, retrieve subnet-id, region and key-name from
AWS Instance Metadata Service
Fixes: #315
(we may fetch also SGs later, this was in mind when created)
to test on aws: quay.io/snir/cloud-api-adaptor-aws:315

aws: retrieve instance metadata from IMDS

---

entrypoint.sh

for shorter functions
Fixs: #326

entrypoint: make optionals oneliner

---

docs/troubleshooting/network-calico.md

Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/347

doc: add tips for network debugging

---

README.md

doc: add collaborations information

---

README.md

doc: format collaboration info

---

pkg/podnetwork/workernode.go

podnetwork: Handle network interface with multiple addresses

---

libvirt/README.md

and volume creation required sizes
Fixes: #365

libvirt: update installation instructions

---

aws/README.md
aws/image/copy-files.sh
azure/README.md
azure/image/copy-files.sh
libvirt/README.md
libvirt/image/copy-files.sh
vsphere/README.md

from within the podvm
Fixes: #367
tested only with AWS

aws,libvirt,azure,vsphere: allow authentication against container image registries

---

docs/vxlan-network-topology.md

Add network topology diagrams when using vxlan

---

pkg/adaptor/hypervisor/vsphere/server.go

vsphere: Add redaction of private config info

---

ibmcloud/README.md

ibmcloud: fix some strings for ibmcloud document

---

pkg/adaptor/hypervisor/vsphere/server.go

vsphere: Add error log statement to NewServer

---

entrypoint.sh

vcenter url, datastore, and datacenter are now mandatory
Fixes #415

vsphere: Make more inputs mandatory

---

podvm/Dockerfile.podvm_builder

podvm: Fix incorrect download folder for kata containers

---

ibmcloud/SECURE_EXECUTION.md
ibmcloud/image/build.sh
ibmcloud/image/push.sh
ibmcloud/image/verify.sh
ibmcloud/terraform/cluster/ansible/kata-playbook.yml

- add document for IBM Secure Execution support
- update build.sh script to generate an IBM Secure Execution image
- handle multiple host keys to generate SE image
- using LUKS encrypted root partition
fixes: #406
Co-authored-by: leilibj <cdlleili@cn.ibm.com>

ibmcloud: Secure Execution Support for Peer Pods on IBM Cloud VPC

---

install/runtime-payload/config/configuration-remote.toml

Make config updates based on
https://github.com/kata-containers/kata-containers/pull/4813
Fixes: #438

Update operator config to include selinux

---

webhook/config/webhook/manifests.yaml
webhook/docs/INSTALL.md
webhook/hack/webhook-deploy.yaml

webhook: Ensure webhook gets called for pods created in all user namespaces

---

aws/raw-to-ami.sh

it uploads a raw image to a s3 bucket and creates an ami based on it
Fixes: #455

aws: helper script for ami creation

---

ibmcloud/README.md

Link in the docs was not correctly marked down.
Fixes: #479

ibmcloud: Fix doc

---

aws/raw-to-ami.sh

to avoid failure on some of the regions
Fixes: #455

aws: fix bucket creation in helper script

---

pkg/adaptor/hypervisor/vsphere/service.go

vsphere: Remove visible credentials

---

pkg/adaptor/hypervisor/aws/service.go

aws: Allow instance creation without SSH keypair name

---

pkg/adaptor/proxy/service.go

otherwise agent will try to get it from path
Fixes: #492

proxy: add cid to pull request

---

Makefile
ibmcloud/image/Makefile
podvm/Makefile
podvm/Makefile.inc

- Add GOOS/GOARCH setting
- Add RUST cross-compile options (CC/ARCH)
Fixes: #403
Holding until #396 has been merged so can do updates for building cross arch podvm images too.

all: Add Cross-build options for image binaries

---

peer-pod-controller/controllers/peerpodconfig_controller.go

instead of only ConfigMap
Fixes: #464

controller: fetch CLOUD_PROVIDER from either cm or secret

---

podvm/Dockerfile.podvm
podvm/Dockerfile.podvm.centos
podvm/Dockerfile.podvm.rhel

Also add some minor cleanups with this PR

Add Attestation Agent to the Pod VM image

---

peer-pod-controller/controllers/peerpodconfig_controller.go

so it can be used safely
Fixes: #464

controller: get and validate cloud-porvider

---

install/yamls/deploy.yaml

Set correct namespace via env CCRUNTIME_NAMESPACE. 
Fixes #491
Signed-off-by: Lei Li <cdlleili@cn.ibm.com>

install: fix x86 operator issues on ibmcloud

---

go.mod
go.sum
pkg/adaptor/proxy/service.go

proxy: Handle retries for PullImage

---

podvm/Makefile.inc

podvm: Allow setting of LIBC dynamically

---

Dockerfile
hack/build.sh

- Build cross-compiled cloud-api-adaptor in builder step of Dockerfile.
- Update build script to fully utilise buildx
Test run: https://hub.docker.com/r/jamesnelson/cloud-api-adaptor-ibmcloud/tags
Fixes: #533

operator: multiarch adaptor image

---

install/README.md
install/runtime-payload/Dockerfile
install/runtime-payload/Makefile
install/runtime-payload/hack/binaries.sh
install/runtime-payload/hack/build.sh

- build out s390x containerd-shim-kata-v2 binary via cross go build
- build s390x runtime payload docker image
Fixes: #513

operator: runtime payload multi-arch support

---

pkg/adaptor/hypervisor/vsphere/vsphere.go

vsphere: Log error return from Resource Pool

---

hack/build.sh

image: include latest tag and default to single arch

---

ibmcloud/IMPORT_PODVM_TO_VPC.md
ibmcloud/image/import.sh
podvm/hack/download-image.sh

Example usage
```
cd ibmcloud/image
./import.sh jamesnelson/podvm-ibmcloud-ubuntu-amd64:latest ca-tor --instance jt-cos-instance --bucket podvm-image-cos-bucket-jt --region jp-tok
```

ibmcloud|podvm: create vpc image from public podvm images

---

install/overlays/azure/kustomization.yaml

azure: kustomization.yaml udpate path to ssh key

---

cmd/cloud-api-adaptor/main.go
pkg/adaptor/hypervisor/vsphere/types.go
pkg/adaptor/hypervisor/vsphere/vsphere.go

vsphere: Add thumbprint for secure TLS login

---

entrypoint.sh
install/overlays/azure/kustomization.yaml
pkg/adaptor/hypervisor/azure/service.go

Add change to support user defined subnet, NSG and image ids to improve flexibility.
Signed-off-by: Kartik Joshi <kartikjoshi@microsoft.com>

Azure: Add support for user defined environment variables

---

entrypoint.sh

Fixes:#584
Signed-off-by: Kartik Joshi <kartikjoshi@microsoft.com>

Fix missing double quotes for azure image id

---

aws/raw-to-ami.sh

in aws/raw-to-ami.sh
Fixed: #587

aws: explicitly specify region for aws commands

---

docs/registries-authentication.md

Fixes: #539
Co-authored-by: Pradipta Banerjee pradipta.banerjee@gmail.com

docs: Add workflow for authenticated registries

---

pkg/adaptor/cloud/vsphere/provider.go
pkg/adaptor/cloud/vsphere/vsphere.go

vsphere: Call DeleteGovmomiClient on Teardown

---

pkg/adaptor/cloud/azure/provider.go

VM, nic and disk were not getting cleaned up when instance deletion request was made.
Fixes: #612

azure: fix cleaning up resources

---

.gitignore
cmd/agent-protocol-forwarder/main.go
pkg/adaptor/cloud/aws/types.go
pkg/adaptor/cloud/cloud.go
pkg/adaptor/cloud/cloud_test.go
pkg/adaptor/proxy/proxy.go
pkg/adaptor/server.go
pkg/adaptor/shim_test.go
pkg/forwarder/forwarder.go
pkg/podnetwork/podnode.go
pkg/podnetwork/tunneler/tunneler.go
pkg/podnetwork/tuntest/tuntest.go
pkg/util/netops/netops.go

It would be good to add `fieldalignment` to the linter or `make check` option.  However couldn't find an easy way to do it.
Hope to implement it as a separate issue.

Align the struct fields for optimal memory use

---

.github/workflows/image.yaml

Fixes: #633
Tested locally using nektos/act

gh-action: fix workflow error

---

install/yamls/ccruntime-peer-pods.yaml

Update runtime payload to use the latest tag
Fixes: #651

install: Update runtime payload

---

install/overlays/aws/kustomization.yaml
install/overlays/azure/kustomization.yaml
install/overlays/ibmcloud/kustomization.yaml
install/overlays/libvirt/kustomization.yaml
install/overlays/vsphere/kustomization.yaml
install/yamls/caa-pod.yaml

- Update the kustomization files for the cloud providers now we have a single binary, so we point to the latest versions
Fixes: #643

all: Update Cloud provider kustomization

---

ibmcloud/cluster/outputs.tf

ibmcloud: Add outputs.tf for cluster

---

test/e2e/README.md
test/e2e/main_test.go
test/provisioner/kustomize.go
test/provisioner/provision.go
test/provisioner/provision_azure.go
test/provisioner/provision_ibmcloud.go
test/provisioner/provision_libvirt.go

e2e: refactor the provisioner code

---

ibmcloud/cluster/main.tf
ibmcloud/cluster/outputs.tf

ibmcloud: Extra Terraform cluster outputs

---

ibmcloud/IMPORT_PODVM_TO_VPC.md
ibmcloud/image/import.sh

Allow import.sh to upload a direct qcow2 file to ibm cloud
Fixes: #661

ibmcloud: Allow import of qcow2 file

---

peer-pod-controller/Makefile

Adds checks to verify go modules and go generated code.
Fixes: #674

controller: Add verify-gen and verify-modules targets

---

test/e2e/README.md

E2E: fix document for libvirt e2e test

---

cmd/cloud-api-adaptor/cloudmgr/vsphere.go
entrypoint.sh
pkg/adaptor/cloud/vsphere/provider.go
pkg/adaptor/cloud/vsphere/types.go

Fixes: #623
This patch also includes a fix in DeleteInstance when the instanceID is null.

vsphere: Support more types of vcenter configs

---

cmd/cluster-provisioner/main.go
test/provisioner/provision_ibmcloud.go
test/provisioner/provision_ibmcloud_initializer.go

ibmcloud: e2e test provisioner block cluster creating and deleting until complete

---

cmd/cluster-provisioner/main.go
go.mod
go.sum
pkg/adaptor/cloud/ibmcloud/provider.go
pkg/adaptor/cloud/ibmcloud/provider_test.go
test/provisioner/provision_ibmcloud.go
test/provisioner/provision_ibmcloud.properties
test/provisioner/provision_ibmcloud_initializer.go

ibmcloud: e2e test harden cluster subnet and vpc

---

test/provisioner/provision_ibmcloud.go
test/provisioner/provision_ibmcloud.properties
test/provisioner/provision_ibmcloud_initializer.go

ibmcloud: e2e prov to create ssh key

---

test/provisioner/provision_ibmcloud.properties
test/provisioner/provision_ibmcloud_initializer.go

ibmcloud: e2e prov remove iam and vpc url in props

---

install/overlays/aws/kustomization.yaml
install/overlays/azure/kustomization.yaml
install/overlays/ibmcloud/kustomization.yaml
install/overlays/libvirt/kustomization.yaml
install/overlays/vsphere/kustomization.yaml
libvirt/README.md

deployments, cm, secrets..
Fixes: #708

controller: remove cloud-provider suffix from k8s objects

---

ibmcloud/IMPORT_PODVM_TO_VPC.md
ibmcloud/image/import.sh

- Add OS override
- Sanitise file names for vpc image rules
Fixes: #715

ibmcloud: Implement import.sh improvements

---

cmd/cluster-provisioner/main.go
test/provisioner/kustomize.go
test/provisioner/provision.go
test/provisioner/provision_ibmcloud.go
test/provisioner/provision_ibmcloud.properties
test/provisioner/provision_ibmcloud_initializer.go

ibmcloud: support e2e test overlay yaml

---

.gitignore

git: Ensure files under cmd/* are not ignored

---

cmd/cluster-provisioner/main.go
test/e2e/main_test.go
test/provisioner/provision_azure_initializer.go
test/provisioner/provision_ibmcloud.properties
test/provisioner/provision_ibmcloud_initializer.go

test: use fatal for program exit errors in e2e test

---

podvm/qcow2/misc-settings.sh

podvm: Disable unnecessary systemd services

---

podvm/qcow2/centos/qemu-centos.pkr.hcl
podvm/qcow2/centos/variables.pkr.hcl
podvm/qcow2/rhel/qemu-rhel.pkr.hcl
podvm/qcow2/rhel/variables.pkr.hcl

podvm: Add boot_wait param for CentOS and RHEL

---

podvm/Dockerfile.podvm_binaries
podvm/Dockerfile.podvm_binaries.centos
podvm/Dockerfile.podvm_binaries.rhel

as if we set AA_KBC it switch the value at runtime

podvm_binaries: add agent-config.toml to container

---

.github/workflows/daily-e2e-test-ibmcloud-amd64.yaml

Fixes https://github.com/confidential-containers/cloud-api-adaptor/issues/781

workflow: daily e2e test for ibmcloud with operator (amd64)

---

azure/README.md
azure/image/Makefile
azure/image/azure-ubuntu.pkr.hcl

Update packer config to build pod vm image using resource group specific scope

Azure: Build peerpod vm image using packer with limited scope

---

test/e2e/common_suite_test.go
test/e2e/main_test.go
test/provisioner/provision.go
test/provisioner/provision_ibmcloud.go
test/provisioner/provision_ibmcloud.properties
test/provisioner/provision_ibmcloud_initializer.go

- add public-gateway name
- wait more time for caa ready
- fix some typo 
Fixes: #804

ibmcloud: add public-gateway name and wait more time for caa ready

---

.github/workflows/podvm_builder.yaml
go.mod
go.sum
podvm/Dockerfile.podvm_builder
podvm/Dockerfile.podvm_builder.centos
podvm/Dockerfile.podvm_builder.rhel
podvm/Makefile.inc

- Update attestation-agent and kata-containers to the 0.5 tags
Fixes: #814

versions: Point to 0.5 releases

---

.github/workflows/podvm_binaries.yaml
.github/workflows/podvm_builder.yaml

Tested locally using 
``` 
act workflow_dispatch -j build -W .github/workflows/podvm_binaries.yaml  | tee out.log
```

Add workflow to create podvm binaries image

---

docs/consuming-prebuilt-podvm-images.md

docs: Update with the new format of podvm images

---

docs/registries-authentication.md
pkg/util/cloudinit/cloudconfig.go

Update credentials format to match upstream KBC URI change

all: Update credentials format

---

peerpodconfig-ctrl/config/manager/manager.yaml
peerpodconfig-ctrl/controllers/peerpodconfig_controller.go

peerpodconfig-ctrl: Make caa image configurable using env var

---

test/provisioner/provision_ibmcloud.go
test/provisioner/provision_ibmcloud.properties
test/provisioner/provision_ibmcloud_initializer.go

Fixes #834
Signed-off-by: Lei Li <genjuro214@gmail.com>
Signed-off-by: Lei Li <cdlleili@cn.ibm.com>

ibmcloud: add new provision property to configure provider type

---

peerpodconfig-ctrl/controllers/peerpodconfig_controller.go

as it's not needed anymore.
if validator for the peerpod ConfigMap/Secret fields is needed can be implemented in separate
Fixes: #820

peerpodconfig-ctrl: remove provider fetching

---

azure/README.md
azure/image/Makefile
azure/image/azure-ubuntu.pkr.hcl

Reverts confidential-containers/cloud-api-adaptor#866
It'll be easier to merge PR-860 first and then make the changes for PR-866
I'll do the work to apply changes added to PR-866

Revert "azure: Update image build docs"

---

peerpod-ctrl/README.md

peerpod-ctrl: fix README.md

---

peerpod-ctrl/controllers/peerpod_controller.go

otherwise it may be completely silent
Fixes: #881

peerpod-ctrl: add log to identify dynamic provider configuration

---

aws/README.md
aws/image/Dockerfile
aws/image/centos/aws-centos.pkr.hcl
aws/image/centos/variables.pkr.hcl

Tested successfully with Ubuntu.
For CentOS, SSH is failing.

Build AWS AMI by running packer inside a container

---

pkg/adaptor/k8sops/peerpod.go

so their name can be fetched correctly at release
Fixes: #897
<del>added hold until verified </del>

k8sops: map Pods to their owned PeerPod objects

---

aws/image/rhel/aws-rhel.pkr.hcl
podvm/Dockerfile.podvm_builder.rhel

and adapt binaries creation
Fixes: #724

aws: bump rhel version for ami creation

---

azure/README.md
azure/image/Dockerfile
azure/image/Makefile
azure/image/centos/variables.pkr.hcl
azure/image/rhel/variables.pkr.hcl
azure/image/ubuntu/variables.pkr.hcl

Azure Packer Remove Build `location` variable

---

webhook/docs/INSTALL.md

Fix command to check node object. Also doing some smaller refactoring
to improve the reading flow of the document.
Fixes #927
---
As far as I understood, the extended resources are also needed for kind, right? Otherwise this section could also be moved under the remote cluster heading.

webhook: improve install docs

---

ci-infra/azure/main.tf
ci-infra/azure/outputs.tf

Azure Static CI Infra: Update role assignment reference

---

entrypoint.sh

ibmcloud: add missing line break in entrypoint

---

.gitignore
test/tools/README.md
test/tools/provisioner-cli/main.go

Reuse e2e test code to deploy operator components into existing cluster.
Fixes: #922

provisioncli: Add install and uninstall actions

---

.github/workflows/podvm_builder.yaml
podvm/Dockerfile.podvm_builder
podvm/Dockerfile.podvm_builder.centos
podvm/Dockerfile.podvm_builder.rhel

Update the kata branch to CCv0 to prepare for 0.6.0 release

podvm: Update kata branch to CCv0

---

podvm/README.md

This is a minor update to the README and a left over from PR #880

podvm: Update description of CAA_SRC_REF

---

test/e2e/main_test.go
test/provisioner/provision.go
test/provisioner/provision_azure.go
test/provisioner/provision_ibmcloud_kustomize.go
test/provisioner/provision_libvirt.go
test/tools/README.md
test/tools/provisioner-cli/main.go

Allow for provisioner-cli to be run from anywhere

---

webhook/go.mod
webhook/main.go

webhook: Fix module naming

---

.github/workflows/daily-e2e-tests-ibmcloud.yaml
podvm/.dummy
podvm/Dockerfile.podvm
podvm/files/.dummy.crt
podvm/qcow2/build-s390x-se-image.sh

- e2e-test: add nightly e2e-test for ibmcloud with secure execution
- podvm: try to fix podvm image build
fixes: #964 #969 

e2e-test: ibmcloud se image test pipeline and one fix for ubuntu podvm image build

---

ci-infra/azure/outputs.tf

azure-static-ci: Output gallery & image def name

---

azure/README.md

azure-docs: Add steps to build container image

---

azure/README.md
azure/image/Dockerfile

azure-packer: No need to specify AZURE_REGION

---

versions.yaml

Super simple yaml file to document what the default versions currently are for our third party dependencies.
Also included is an example of how this would be used in the Makefile to get the ubuntu image URL and checksum.
Welcome any comments. Thanks.

Add versions.yaml file

---

docs/addnewprovider.md

Updates the doc for adding support for a new cloud provider considering the latest upstream changes.
Fixes: #996

docs: update the doc for adding a new provider

---

pkg/adaptor/proxy/proxy.go

proxy: Use fixed delay for proxy connection

---

.github/workflows/lint.yaml
Makefile
aws/image/copy-files.sh
aws/image/misc-settings.sh
azure/image/copy-files.sh
azure/image/misc-settings.sh
hack/golangci-lint.sh
hack/shellcheck.sh
ibmcloud/cluster/kube-init.sh
ibmcloud/image/build.sh
ibmcloud/image/delete.sh
ibmcloud/image/login.sh
ibmcloud/image/multipart_upload.sh
ibmcloud/image/push.sh
ibmcloud/image/verify.sh
ibmcloud/terraform/cluster/scripts/keygen.sh
ibmcloud/terraform/cluster/scripts/setup.sh
install/pre-install-payload/scripts/cloud-api-adaptor-deploy.sh
install/runtime-payload/hack/binaries.sh
install/runtime-payload/hack/build.sh
install/runtime-payload/scripts/kata-deploy.sh
libvirt/install_operator.sh
podvm/qcow2/build-s390x-se-image-post.sh
podvm/qcow2/build-s390x-se-image.sh
podvm/qcow2/copy-files.sh
podvm/qcow2/misc-settings.sh
volumes/csi-wrapper/hack/ibm/cleanandreinstall.sh
vsphere/image/misc-settings.sh
vsphere/vmdk-to-ovf.sh
webhook/tests/e2e/run-local.sh

For now, this fixes findings with severity "warning" and also uses this severity level for the workflow.

ci: add shellcheck to lint workflow and fix issues

---

podvm/Makefile.inc

podvm: Update AA install path

---

.github/workflows/csi_wrapper_images.yaml
volumes/csi-wrapper/Dockerfile.csi_wrappers
volumes/csi-wrapper/Makefile

- Clean Dockerfiles
- support local dev and remote release build
- build three csi-wrappers images in one Dockerfile
fixes #1030

csi-wrapper: Build csi-wrapper images via GHA

---

volumes/csi-wrapper/hack/ibm/ibm-vpc-block-csi-driver.patch
volumes/csi-wrapper/hack/ibm/nginx-kata-with-my-pvc-and-csi-wrapper.yaml
volumes/csi-wrapper/hack/ibm/patch-controller.yaml
volumes/csi-wrapper/hack/ibm/patch-node.yaml

- update driver patch
- replace patches for new kustomize version
- fix args issue for new k8s version
- update csi-wrapper images urls
fixes #1042
Signed-off-by: Lei Li <genjuro214@gmail.com>
Signed-off-by: Lei Li <cdlleili@cn.ibm.com>

volume/csi-wrapper: replay and update yaml files

---

volumes/csi-wrapper/README.md

- no need to ssh on worker node
- no need to build wrapper images locally
fixes #1042

volume/csi-wrapper: update README doc

---

pkg/adaptor/cloud/aws/provider.go
pkg/adaptor/cloud/aws/provider_test.go

Fixes: #1050
This is initial framework and more unit tests will be added in due course.

aws: Add unit tests

---

test/e2e/common.go
test/e2e/common_suite_test.go
test/e2e/ibmcloud_test.go

Added test cases to check peer pod created via job in ibmcloud cloud-provider
Resolves: #930, Resolves: #1004

ibmcloud: Added test case to check peer pod created with job

---

.github/workflows/webhook-build.yaml
.github/workflows/webhook-test.yaml
webhook/docs/INSTALL.md

Content of commit
Build and push the webhook image if any changes occur during a merge to staging
Fixes: #1067

webhook: Add automation for building the webhook

---

.github/workflows/test-images.yaml
test/e2e/common_suite_test.go
test/e2e/fixtures/Dockerfile.testuser
test/e2e/ibmcloud_test.go

Added e2e-test cases for ibmcloud to check peer-pod Logs User from container
Fixes: #1001 
Note: Current PR is dependent on #942

ibmcloud: e2e-test cases for ibmcloud to check peer-pod Logs User from container

---

.github/workflows/test-images.yaml

Updated username for test-images workflow file
Fixes: #1001

ibmcloud: Updating username in workflow

---

test/e2e/common_suite_test.go

Fixes the bug which Fails the pod with COMPLETED status
Fixes: #1001

ibmcloud: Bug fix for test case with user image

---

.github/workflows/test-images.yaml

Test Workflow trigger updated to workflow_dispatch
Fixes: #1001

ibmcloud: Test trigger updated to workflow_dispatch

---

volumes/csi-wrapper/README.md
volumes/csi-wrapper/hack/ibm/ibm-vpc-block-csi-driver.patch

- still need update csi driver image tags
fixes #1042

volume/csi-wrapper: update README doc and fix patch

---

aws/image/misc-settings.sh
azure/image/misc-settings.sh
podvm/qcow2/misc-settings.sh

Install missing lib on Azure Ubuntu podvm image so that a KBC with for Azure SNP vTPM can run successfully.
Fixes: #1041

podvm: install libtss2 for ubuntu azure

---

test/e2e/common_suite_test.go

Added code to catch PodVM Failure error
Fixes: #930, #1004

ibmcloud: Bug fix to catch PodVm Failure

---

.github/workflows/csi_wrapper_images.yaml
.github/workflows/daily-e2e-tests-ibmcloud.yaml
.github/workflows/image.yaml
.github/workflows/podvm_builder.yaml
.github/workflows/test-images.yaml
.github/workflows/webhook-build.yaml
azure/README.md
docs/addnewprovider.md
podvm/Dockerfile.podvm_builder
podvm/Dockerfile.podvm_builder.centos
podvm/Dockerfile.podvm_builder.rhel
podvm/README.md
versions.yaml
volumes/csi-wrapper/Dockerfile.csi_wrappers

Updates to reflect us updating the default branch name from staging to main

Rename staging to main

---

volumes/csi-wrapper/README.md
volumes/csi-wrapper/hack/ibm/apply-required-labels.sh
volumes/csi-wrapper/hack/ibm/ibm-vpc-block-csi-driver-master.yaml
volumes/csi-wrapper/hack/ibm/nginx-kata-with-my-pvc-and-csi-wrapper.yaml
volumes/csi-wrapper/hack/ibm/patch-controller.yaml

- include the template file of deployemnt for ibm-vpc-block-csi-driver master version
- updated csi-wrapper readme document
- add debug section
fixes: #1101

csi-wrapper: Run csi-wrapper with ibm-vpc-block-csi-driver master version

---

.github/workflows/podvm_builder.yaml
podvm/Dockerfile.podvm_builder
podvm/Dockerfile.podvm_builder.centos
podvm/Dockerfile.podvm_builder.rhel

Bump versions to `CCv0`
Fixes: #1105

podvm: Update kata-version to `CCv0`

---

entrypoint.sh
go.mod
go.sum
install/overlays/aws/kustomization.yaml
pkg/adaptor/cloud/aws/manager.go
pkg/adaptor/cloud/aws/provider.go
pkg/adaptor/cloud/aws/provider_test.go
pkg/adaptor/cloud/aws/types.go
pkg/adaptor/cloud/azure/provider.go
pkg/adaptor/cloud/cloud.go
pkg/adaptor/cloud/cloud_test.go
pkg/adaptor/cloud/ibmcloud-powervs/provider.go
pkg/adaptor/cloud/ibmcloud/provider.go
pkg/adaptor/cloud/ibmcloud/provider_test.go
pkg/adaptor/cloud/libvirt/provider.go
pkg/adaptor/cloud/types.go
pkg/adaptor/cloud/util.go
pkg/adaptor/cloud/vsphere/provider.go
pkg/adaptor/server_test.go
pkg/util/cloud.go
pkg/util/cloud_test.go

This is the initial version implemented only for AWS to kickstart discussion on the approach.

Add support for flexible instance types

---

ibmcloud-powervs/README.md

- cloud-api-adpator staging branch renamed to main
- Fix the install path for ibmcloud-powervs
Fixes: #1117

powervs: minor fixes in image build doc

---

docs/Release-Process.md

Document the release process
Fixes: #1108

doc: release doc

---

test/e2e/common_suite_test.go
test/e2e/fixtures/Dockerfile.largeimage
test/e2e/ibmcloud_test.go

Added test cases to check peer pod pulls larger image in ibmcloud cloud-provider
Fixes: #1111

ibmcloud: Added test cases to check peer pod with large image

---

.github/workflows/build.yaml
.github/workflows/controller.yaml
.github/workflows/csi_wrapper_images.yaml
.github/workflows/image.yaml
.github/workflows/lint.yaml
.github/workflows/podvm_builder.yaml
.github/workflows/webhook-build.yaml
.github/workflows/webhook-test.yaml
.golangci.yaml
go.mod
versions.yaml

Upgrading to the latest Go version.
Fixes: #1139

deps: upgrade to Go 1.20.5

---

azure/README.md

azure-docs: minor instructions fixs

---

azure/README.md
ibmcloud/cluster/label-nodes.sh
install/README.md
install/yamls/caa-pod.yaml
libvirt/install_operator.sh
peerpodconfig-ctrl/controllers/peerpodconfig_controller.go
test/provisioner/provision_azure.go
test/provisioner/provision_ibmcloud.go
volumes/csi-wrapper/README.md
webhook/hack/extended-resources/ext-res-ds.yaml

Update node label from node-role.kubernetes.io to node.kubernetes.io
Fixes: #780

Update node label prefix

---

entrypoint.sh

entrypoint: Fix formatting

---

pkg/adaptor/proxy/service.go
pkg/forwarder/interceptor/interceptor.go
volumes/csi-wrapper/cmd/csi-podvm-wrapper/main.go

volume/csi-wrapper: support multiple mount path
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/1077

volume/csi-wrapper: support multiple mount path in a single container

---

go.mod
go.sum
pkg/adaptor/cloud/azure/provider.go

Cleanup NIC/disk together with VM using "DeleteOption" properties when creating the VM.
Haven't tested this yet!

Azure resource cleanup

---

go.sum

deps: fix go.sum

---

podvm/Dockerfile.podvm_builder
podvm/Dockerfile.podvm_builder.centos
podvm/Dockerfile.podvm_builder.rhel

- use another way to checkout kata-container codes
Fixes: #1228

podvm: fix podvm image build

---

.github/workflows/podvm_builder.yaml

- Add missing quote
Fixes: #1232

podvm: Fix `KATA_SRC_BRANCH`

---

install/overlays/aws/kustomization.yaml
install/overlays/azure/kustomization.yaml
install/overlays/ibmcloud-powervs/kustomization.yaml
install/overlays/libvirt/kustomization.yaml
install/overlays/vsphere/kustomization.yaml

Using the
quay.io/repository/confidential-containers/cloud-api-adaptor:6d7d2a3fe8243809b3c3a710792c8498292e2fc3 image.
That image was built by https://github.com/confidential-containers/cloud-api-adaptor/actions/runs/5646326401 after the PR https://github.com/confidential-containers/cloud-api-adaptor/pull/1235 (Update Kata Containers and CoCo operator for 0.7.0) was merged.
I tested it locally for libvirt:
```
=== RUN   TestLibvirtCreateSimplePod
=== RUN   TestLibvirtCreateSimplePod/SimplePeerPod_test
=== RUN   TestLibvirtCreateSimplePod/SimplePeerPod_test/PodVM_is_created
time="2023-07-24T15:55:46-03:00" level=info msg="Deleting pod... nginx"
--- PASS: TestLibvirtCreateSimplePod (85.12s)
--- PASS: TestLibvirtCreateSimplePod/SimplePeerPod_test (85.12s)
--- PASS: …
```

install: pin cloud-api-adaptor image for v0.7.0

---

test/provisioner/provision_azure.go

Use default vnet and fetch defaut vnet subnet id in azure provisioner
Fixes: #1221

Azure: Remove vnet creation dependency from provisioner

---

azure/image/centos/variables.pkr.hcl
azure/image/rhel/variables.pkr.hcl
azure/image/ubuntu/variables.pkr.hcl

azure-packer: Add sensitive flag to variables

---

Makefile
test/e2e/common_suite_test.go
test/e2e/fixtures/Dockerfile.testuser

Added fixes to resolve unstable test results in daily-e2e-test jenkins job
Fixes: #1127

ibmcloud: Added fixes to resolve unstable test results

---

azure/image/Makefile

azure: mask client secret in image makefile

---

test/provisioner/provision_ibmcloud.go

Added wait condition to delete the subnet completely
Fixes: #1257

ibmcloud: Wait condition for deleting subnets

---

azure/image/centos/variables.pkr.hcl
azure/image/rhel/variables.pkr.hcl

Add defaults to RHEL and CentOS's variables file for the variables like publisher, offer, sku, etc.
Fixes: #1255

azure-packer: Add defaults to RHEL,CentOS image SKUs

---

test/provisioner/provision_libvirt.go

Rewrites the UploadPodvm() implementaiton in for libvirt testing in Go rather than a call to virsh.
Fixes: #1162

test/e2e/libvirt: UploadPodvm() Go Rewrite

---

ibmcloud/SECURE_EXECUTION.md
test/tools/README.md

bug: fix the provisioner-cli readme when build libvirt

---

README.md

New time is 14:00 UTC on Wednesday.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/1283

readme: update meeting time

---

podvm/Makefile.inc

podvm: replace sed seperators in pod image makefile

---

ci-infra/azure/outputs.tf

azure-ci-static-infra: Output the managed identity name

---

azure/image/misc-settings.sh

azure: add tdx runtime libraries to podvm

---

.github/workflows/azure-e2e-test.yml
ci-infra/README.md

Add workflow for e2e test. 
Steps: 
1. Build podvm image 
2. Setup cluster and test e2e
3. cleanup resources

Azure: Add CI pipeline for e2e test

---

test/provisioner/provision_ibmcloud.go

Added wait condition for SSH key deletion
Fixes: #1303

ibmcloud: wait condition for ssh deletion

---

test/e2e/common_suite_test.go

Included Logs for debugging nightly tests
Fixes: #1127

ibmcloud: Logs for debugging nightly tests

---

test/e2e/common.go
test/e2e/common_suite_test.go
test/e2e/ibmcloud_test.go

Add fix for podvm hitting container execution error
Fixes: #1127

ibmcloud: Fix container execution error

---

pkg/adaptor/cloud/libvirt/libvirt.go

Currently after the Libvirt domain is created it will wait for a fixed amount of time (30s) before query libvirt for the domain's IP addresses. This is clearly sub-optimal.
Moreover, while working on the CI job for libvirt (https://github.com/confidential-containers/cloud-api-adaptor/pull/1318) I realized 30s is not enough if the job runner is in an Azure VM, but if I increase the timeout too much....even worse.
So I am sending those changes the refactor the code to get the IP addresses. It will now be polling the domain every 3 seconds and retry up to 20 times. So approximately 60s of wait time on worst case.

libvirt: improve the get domain IPs mechanism

---

.github/workflows/azure-e2e-test.yml

azure: convert e2e test to manual trigger

---

ci-infra/azure/main.tf

azure: point federated credentials to main

---

.github/workflows/controllers.yaml
peerpod-ctrl/Makefile
peerpodconfig-ctrl/Makefile

- This PR adds verify targets to check if go modules and manifests are up to date
- It also refactor the verify targets in peerpodconfig-ctrl and add the checks to the controllers workflow
Fixes: #1349

controllers: refactor and add verify checks

---

libvirt/install_operator.sh

LIBVIRT_IP is required to run install_operator.sh for libvirt. This ip address should refer to the ip address defined in the network XML configuration and error out if it is undefined.
Rather than manually exporting this, this can be determined by looking at the network's xmldump.
By default, this is typically 192.168.122.1, but can be changed.
Note that kcli, which is used to create the cluster in kcli_cluster.sh must be past commit 0160f70 to create a cluster using a network that is does belong under the cidr submask 192.168.122.0/24. see:
github.com/karmab/kcli/commit/0160f7000f2bcc09b52b449e837e3ad386006a6a
Fixes: #1238

libvirt: Get LIBVIRT_IP from network XML config

---

webhook/.gitignore

webhook: add .gitignore file

---

test/e2e/azure_test.go
test/e2e/common_suite_test.go
test/e2e/ibmcloud_test.go

tests: add functionality to test pod removal

---

.github/workflows/azure-e2e-test.yml

test: kata-agent step in az e2etest requires go

---

.github/workflows/peerpod-ctrl_image.yaml

working-directory is not applied to steps.uses

workflow: set context to build peerpod-ctrl image

---

aws/README.md
aws/image/Dockerfile
aws/image/Makefile
aws/image/centos/aws-centos.pkr.hcl
aws/image/centos/variables.pkr.hcl
aws/image/rhel/aws-rhel.pkr.hcl
aws/image/rhel/variables.pkr.hcl
aws/image/ubuntu/aws-ubuntu.pkr.hcl
aws/image/ubuntu/variables.pkr.hcl
entrypoint.sh
install/overlays/aws/kustomization.yaml
pkg/adaptor/cloud/aws/manager.go
pkg/adaptor/cloud/aws/provider.go
pkg/adaptor/cloud/aws/provider_test.go
pkg/adaptor/cloud/aws/types.go

* Switch to Ubuntu 22.04 
* Allow specifying root volume in packer builds
* Allow specifying root volume size in cloud-api-adaptor

Misc AWS fixes

---

peerpod-ctrl/Makefile

ibmcloud: add provider to peerpod-ctl

---

cmd/cloud-api-adaptor/main.go
entrypoint.sh
install/overlays/aws/kustomization.yaml
install/overlays/azure/kustomization.yaml
install/overlays/ibmcloud-powervs/kustomization.yaml
install/overlays/ibmcloud/kustomization.yaml
install/overlays/libvirt/kustomization.yaml
install/overlays/vsphere/kustomization.yaml
pkg/adaptor/cloud/aws/provider.go
pkg/adaptor/cloud/aws/provider_test.go
pkg/adaptor/cloud/azure/provider.go
pkg/adaptor/cloud/cloud.go
pkg/adaptor/cloud/cloud_test.go
pkg/adaptor/cloud/ibmcloud-powervs/provider.go
pkg/adaptor/cloud/ibmcloud/provider.go
pkg/adaptor/cloud/ibmcloud/provider_test.go
pkg/adaptor/cloud/libvirt/provider.go
pkg/adaptor/cloud/types.go
pkg/adaptor/cloud/vsphere/provider.go
pkg/adaptor/server.go
pkg/adaptor/server_test.go
pkg/adaptor/shim_test.go

- Check podvm image id is not empty
- Only verify cloud config when `CLOUD_CONFIG_VERIFY` env is `yes`
fixes: #1417

ConfigVerifier: Veify cloud service config before Start cloud services

---

.github/workflows/peerpod-ctrl_image.yaml
peerpod-ctrl/Dockerfile
peerpod-ctrl/Makefile

peerpod-ctl: build multi-arch images for peerpod-ctl

---

azure/image/rhel/azure-rhel.pkr.hcl
azure/image/rhel/variables.pkr.hcl

to allow support in RHEL CVM image builds

azure: add shared_image_gallery_destination for RHEL

---

azure/README.md
azure/build-image.md

This commit makes it even more easier and hands-off approach for the user when following the Azure documentation.

azure-docs: Minor changes to instructions

---

CITATION.cff
docs/Release-Process.md

Add a citation so people can easily cite our software and use a
unified format.
[See the documentation for details](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)

github: add citation

---

volumes/csi-wrapper/README.md
volumes/csi-wrapper/examples/aws/README.md
volumes/csi-wrapper/examples/aws/dynamic-provisioning/claim.yaml
volumes/csi-wrapper/examples/aws/dynamic-provisioning/pod.yaml
volumes/csi-wrapper/examples/aws/dynamic-provisioning/storageclass.yaml
volumes/csi-wrapper/examples/aws/example-iam-policy.json
volumes/csi-wrapper/examples/aws/patch-controller.yaml
volumes/csi-wrapper/examples/aws/patch-node.yaml
volumes/csi-wrapper/examples/aws/rbac-ebs-csi-wrapper-podvm.yaml
volumes/csi-wrapper/examples/aws/rbac-ebs-csi-wrapper-runner.yaml

and how to add the peer-pods CSI wrapper to it
Fixes: #1363

csi-wrapper: add example for AWS EBS CSI driver

---

pkg/adaptor/cloud/ibmcloud-powervs/manager.go
pkg/adaptor/cloud/ibmcloud/manager.go

Fixes: #1454
This PR will fix the `Fix the LoadEnv() function` described in #1454

adaptor: Fix problem in LoadEnv in cloud Providers

---

ibmcloud-powervs/README.md
install/overlays/ibmcloud-powervs/.gitignore
install/overlays/ibmcloud-powervs/kustomization.yaml

This PR adds changes to store the api key and related credentials in an env file which is set in kustomization.
Fixes: part of #1136

install: store secrets in an env file for ibmcloud-powervs

---

.github/workflows/azure-podvm-image-build.yml

azure-podvm-image-build: Install protobuf

---

azure/image/Makefile
azure/image/centos/azure-centos.pkr.hcl
azure/image/rhel/azure-rhel.pkr.hcl
azure/image/ubuntu/azure-ubuntu.pkr.hcl

azure-packer: Add azure packer provider block

---

.github/workflows/lint.yaml
Makefile
aws/image/centos/aws-centos.pkr.hcl
aws/image/centos/variables.pkr.hcl
aws/image/rhel/aws-rhel.pkr.hcl
aws/image/rhel/variables.pkr.hcl
aws/image/ubuntu/aws-ubuntu.pkr.hcl
aws/image/ubuntu/variables.pkr.hcl
hack/packer-check.sh
hack/terraform-check.sh
ibmcloud/cluster/main.tf
ibmcloud/cluster/node/version.tf
ibmcloud/cluster/outputs.tf
ibmcloud/cluster/provider.tf
ibmcloud/cluster/variables.tf
ibmcloud/cluster/version.tf
ibmcloud/cluster/vpc/main.tf
ibmcloud/cluster/vpc/version.tf
podvm/qcow2/centos/qemu-centos.pkr.hcl
podvm/qcow2/centos/variables.pkr.hcl
podvm/qcow2/rhel/qemu-rhel.pkr.hcl
podvm/qcow2/rhel/variables.pkr.hcl
podvm/qcow2/ubuntu/qemu-ubuntu.pkr.hcl
podvm/qcow2/ubuntu/variables.pkr.hcl
vsphere/image/rhel/variables.pkr.hcl
vsphere/image/rhel/vsphere-rhel.pkr.hcl

ci: add formatting for terraform and packer files

---

pkg/adaptor/proxy/service.go

Fixes: #1511
Signed-off-by: Qi Feng Huo <huoqif@cn.ibm.com>

image: pull image via remote-snapshotter

---

.github/workflows/azure-e2e-test.yml

This will reduce the time to run the e2e tests by at least five minutes.

azure-e2e: Install AKS in parallel to podvm image build

---

peerpod-ctrl/Dockerfile

and update golang-fedora container version
Fixes: #1241

peerpod-ctrl: add libvirt ssh authentication support

---

.github/workflows/peerpodconfig-ctrl_image.yaml

The gh-action job included incorrect build target resulting in job failure.
Fixes: #1525

peerpodconfig-ctrl: Fix the gh-action job

---

test/e2e/assessment_helpers_test.go
test/e2e/assessment_runner_test.go
test/e2e/aws_test.go
test/e2e/azure_test.go
test/e2e/common.go
test/e2e/common_suite_test.go
test/e2e/ibmcloud_test.go
test/e2e/libvirt_test.go
test/provisioner/provision_ibmcloud.go
test/provisioner/provision_ibmcloud_kustomize.go

Added e2e  test cases for flexible instance profiles
Fixes: #1161

ibmcloud: e2e test for flexible instance profiles

---

test/e2e/common.go
test/e2e/common_suite_test.go
test/e2e/ibmcloud_test.go

Included Readiness Probe along with nginx containers
Fixes:  #1450

ibmcloud: Included Readiness Probe along with nginx containers

---

.github/workflows/caa_build_and_push_per_arch.yaml
.github/workflows/image.yaml
Dockerfile
Makefile
hack/build.sh
hack/image-manifest.sh

image: build dev and release image for all arch

---

libvirt/README.md

Updates the uninstallation instructions for libvirt.
Fixes: #1329

libvirt: update README uninstall

---

test/e2e/assessment_runner_test.go

Added excluded code snippets while rebasing the PR https://github.com/confidential-containers/cloud-api-adaptor/pull/1502. Enhanced Debugging for Readiness Probe Status in Nightly Jenkins Run
Fixes: #1450

ibmcloud: Included missing code changes

---

README.md

Added a badge to show the status of the nightly libvirt tests.

README: add CI badge for libvirt

---

versions.yaml

Bumping kata to include a fix for image layer ordering

versions: bump kata ref

---

ibmcloud/IMPORT_PODVM_TO_VPC.md
test/e2e/README.md

Add more details to document to run e2e test on ibmcloud
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/1646

doc: update doc to add ibmcloud specific properties

---

aws/README.md
podvm/addons/nvidia_gpu/setup.sh

1. Set default nvidia driver version 
2. Update example in AWS README

Misc fixes

---

.github/workflows/azure-e2e-test.yml

Azure: enable e2e workflow on daily basis

---

ibmcloud/image/build.sh

bug: fix the misc se-build error

---

ibmcloud/cluster/README.md
ibmcloud/cluster/ansible/tasks/k8s.yaml
ibmcloud/cluster/main.tf
ibmcloud/cluster/variables.tf

fixes #1729 
switch to k8s Community-Owned Package Repositories

ibmcloud: switch to k8s Community-Owned Package Repositories

---

.github/workflows/podvm_mkosi_image.yaml
src/cloud-api-adaptor/aws/README.md
src/cloud-api-adaptor/docs/addnewprovider.md
src/cloud-api-adaptor/podvm-mkosi/Makefile
src/cloud-api-adaptor/test/e2e/README.md

- fix podvm mkosi build
- and some bad links

podvm: fix podvm_mkosi_image build and some links issues

---

src/cloud-api-adaptor/hack/build.sh

This reverts commit f1fd4d9da8d1a6353d208ed6ed5f44649ff5a8b1.
Fixes: #1792

Revert "Build: Update build.sh"

---

src/cloud-api-adaptor/versions.yaml

Update kbs image tag to make it compatible with current guest component and caa.
Fixes: #1785

versions: update kbs image tag

---

src/cloud-api-adaptor/test/e2e/main_test.go
src/cloud-api-adaptor/test/tools/README.md
src/cloud-api-adaptor/test/tools/provisioner-cli/main.go
src/cloud-api-adaptor/versions.yaml

We are in release freeze, so pushing PRs, especially those that update the versions we are relying on away from an official release is NOT acceptable.

Revert 1789 and 1796

---

docs/Release-Process.md

Small fixes improving our next release process.

Release process: small changes

---

src/cloud-api-adaptor/libvirt/README.md

Some small improvements I found when following the latest docs.

Docs/libvirt: small improvements

---

src/peerpodconfig-ctrl/controllers/peerpodconfig_controller.go

The CAA daemonset spec was not getting updated
as the code never updated the spec post creation

peerpodconfig-ctrl: Handle updating the CAA DS spec

---

CITATION.cff
docs/Release-Process.md
src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml

Complete the tasks from https://github.com/confidential-containers/cloud-api-adaptor/blob/main/docs/Release-Process.md#post-release

0.8.2 post release tasks

---

src/cloud-api-adaptor/test/e2e/main_test.go
src/cloud-api-adaptor/test/tools/README.md
src/cloud-api-adaptor/test/tools/provisioner-cli/main.go
src/cloud-api-adaptor/versions.yaml

Reverts confidential-containers/cloud-api-adaptor#1800. Merge these changes back again after code freeze is lifted.

Revert "Revert 1789 and 1796"

---

README.md

README: add CI badge for azure

---

src/cloud-api-adaptor/versions.yaml

Update versions file to support new nodeport changes in kbs
Fixes: #1785

versions: Update version file with new nodeport changes

---

.github/workflows/e2e_libvirt.yaml
src/cloud-api-adaptor/libvirt/config_libvirt.sh
src/cloud-api-adaptor/versions.yaml

libvirt: enable e2e test for attestation case in gha

---

src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/initrd/mkosi.conf.d/fedora.conf
src/cloud-api-adaptor/podvm-mkosi/mkosi.presets/system/mkosi.conf.d/fedora.conf

Bump fedora version from 38 to 39.

fedora: bump fedora to version 39

---

src/cloud-api-adaptor/podvm-mkosi/Makefile
src/cloud-api-adaptor/podvm-mkosi/README.md

- Added ATTESTER=se-attester when build s390x PeerPod image via mkosi

doc: update s390x mkosi build doc

---

src/cloud-providers/azure/provider.go

Delete network interface synchronously if vm creation is failed
Fixes: #1842

azure: Delete network interface synchronously

---

src/cloud-api-adaptor/go.mod
src/cloud-api-adaptor/versions.yaml
src/csi-wrapper/go.mod
src/peerpod-ctrl/go.mod

The go mod changes look a bit funny as we are going from an alpha release to a pre-release

0.9.0 pre release

---

src/cloud-api-adaptor/podvm/addons/nvidia_gpu/setup.sh

According to https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/precompiled/ the correct way to install pre-compiled drivers is to update kernel and opt-into a precompiled modularity stream, however, it may take some time between latest kernel version is released until the precompiled pkgs are available; which may cause driver failure.
This commit adds a function which tries to update the kernel to the latest version supported by the nvidia precompiled drivers, if fails it upgrades to the latest kernel version available.

addons: rhel kernel version matching

---

src/cloud-api-adaptor/podvm/Dockerfile.podvm_builder.rhel

This commit also aligns the deps with the Fedora Dockerfile

podvm: Add attester build deps to RHEL Dockerfile

---

src/cloud-api-adaptor/test/e2e/assessment_runner.go
src/cloud-api-adaptor/test/e2e/azure_common.go
src/cloud-api-adaptor/test/e2e/azure_test.go
src/cloud-api-adaptor/test/e2e/common.go
src/cloud-api-adaptor/test/e2e/common_suite.go
src/cloud-api-adaptor/test/e2e/main_test.go
src/cloud-api-adaptor/test/e2e/nginx_deployment.go
src/cloud-api-adaptor/test/provisioner/azure/provision_azure.properties
src/cloud-api-adaptor/test/provisioner/azure/provision_common.go
src/cloud-api-adaptor/test/provisioner/azure/provision_initializer.go

Bunch of small commits to add new Azure tests and enable running of these with crio runtime.
Also enables running of tests against an existing fully configured setup.

Add additional e2e tests and introduce the capability to run Azure tests on crio runtime

---

src/cloud-api-adaptor/docs/SecureComms.md

Update Secure-Comms readme file following changes in trustee-operator

cloud-api-adaptor: Update Secure-Comms readme file

---

src/cloud-api-adaptor/docker/prereqs.sh
src/webhook/Makefile
src/webhook/pkg/mutating_webhook/mutating-webhook_test.go
src/webhook/pkg/mutating_webhook/remove-resourcespec.go
src/webhook/tests/e2e/run-local.sh

Fix handling of fractional cpu units during mutation
Reliably install cert-manager for webhook if needed.
~~Deploy webhook by default during install~~ : Will create a separate PR for this

Webhook changes

---

src/cloud-api-adaptor/go.mod
src/cloud-api-adaptor/versions.yaml
src/csi-wrapper/go.mod
src/peerpod-ctrl/go.mod

- Update the operator version for release
- Update the CAA go modules for pre-release

0.10.0 pre release version updates

---

CITATION.cff
src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
src/cloud-api-adaptor/versions.yaml

Post release tasks:
- Update Citation
- Revert operator version back to main
- Revert CAA image in installs back to latest

V0.10.0 post release tasks

---

src/cloud-api-adaptor/test/e2e/common.go
src/cloud-api-adaptor/test/e2e/common_suite.go
src/cloud-api-adaptor/test/e2e/libvirt_test.go

Added test for sealed secrets and consolidated code that sets initdata annotation.

e2e: Add sealed secret test

---

CITATION.cff
docs/Release-Process.md
src/cloud-api-adaptor/install/README.md
src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
src/cloud-api-adaptor/versions.yaml

- Revert pinning of operator version
- Revert sha pinning of image refs in kustomization
- Adjust strings in doc
- Update CITATION
- Refine release process description

release: v0.11.0 post-release work

---

src/cloud-api-adaptor/aws/README.md

aws: Update pre-built AMI id for 0.11.0

---

src/cloud-api-adaptor/gcp/README.md

I revisited the PeerPods instructions for GKE today and noticed a few minor areas that could be improved.

Small fixes on GCP deployment

---

.github/workflows/e2e_libvirt.yaml

Get the logs of kbs on failure for debugging

tests/e2e: Add kbs logs

---

src/cloud-api-adaptor/test/e2e/nginx_deployment.go
src/cloud-api-adaptor/test/provisioner/ibmcloud/provision_kustomize.go
src/cloud-api-adaptor/test/provisioner/provision.go
src/cloud-api-adaptor/test/provisioner/trustee_kbs.go

Resolve golangci-lint warnings

---

.github/workflows/podvm_mkosi.yaml

Update the registry for the docker provider image, so that it uses the input variable, rather than being hard-coded.

workflow: podvm_mkosi: Update registry

---

src/cloud-providers/gcp/provider.go

This allow users to use public images shared outside the project scope.

gcp: handle image in two formats

---

src/cloud-providers/ibmcloud-powervs/provider.go

This PR checks the instance type spec and adjusts systemType, processsors and memory accordingly.
Fixes: #2342

ibmcloud-powervs: adjust systemType/processors/memory from annotations

---

src/cloud-api-adaptor/go.mod
src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
src/csi-wrapper/go.mod
src/peerpod-ctrl/go.mod

Update go mods and pin CAA image

0.13.0 release

---

CITATION.cff
src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
src/cloud-api-adaptor/versions.yaml

V0.13.0 post release tasks

---

src/cloud-api-adaptor/pkg/adaptor/proxy/service.go

This will allow kata-agent to know a Nvidia devices should be present and look for the CDI spec
This is currently supports only Nvidia and "all" devices attached to the selected instance type
Related-to: https://github.com/confidential-containers/cloud-api-adaptor/issues/2255
**NOTE:**
This was tested with custom podvm image, I'm working on adding the CDI spec creation and driver installation to the podvm-mkosi fedora image to allow this to be easily usable, having said that, it's ready for feedback on this part :)

nvidia: set Nvidia's CDI annotation based on default_gpus

---

src/cloud-providers/ibmcloud/provider.go

Add log message when podvm image is chosen from pod annotation.

ibmcloud: improve image selection logging

---

src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md

Added instructions to the ROKS setup doc to include a sample Trustee that can be used for attestation testing.

ibmcloud: add instructions to deploy a sample Trustee.

---

src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md

Update the ROKS demo instructions to gzip and then base64 encode the INITDATA, to conform to latest design (ref: #2388).
Also made a few other small improvements to the doc.

ibmcloud: gzip INITDATA in ROKS setup instructions.

---

src/cloud-api-adaptor/ibmcloud-powervs/README.md
src/cloud-api-adaptor/ibmcloud-powervs/image/Makefile
src/cloud-api-adaptor/ibmcloud-powervs/image/copy-files.sh
src/cloud-api-adaptor/ibmcloud-powervs/image/prereq.sh

Add command installation for oras in prereq.sh and mody copy-files.sh to add missing dependencies.
Fixes: #2365

ibmcloud-powervs: install oras and modify copy-files.sh for image build

---

src/cloud-providers/gcp/provider.go

- Added more prefixes which should not follow internal project image source location.
- Added support for full URL project name definitions

gcp: improved image source format detection

---

src/cloud-api-adaptor/ibmcloud/ROKS_SETUP.md

Add instructions for building a TDX-enabled RHEL image in the PeerPod VM Custom Image section.

ibmcloud: update ROKS demo doc image instructions

---

.github/dependabot.yml

Let dependabot create PRs for updating go module dependencies as well as github actions

Dependabot go configuration

---

src/cloud-api-adaptor/alibabacloud/README.md
src/cloud-api-adaptor/install/overlays/alibabacloud/kustomization.yaml

This PR mainly includes two update for alibaba cloud mainly for user guides than code changes. Please see the concrete commit message.

AlibabaCloud: document and kustomization update

---

src/cloud-api-adaptor/go.mod
src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
src/cloud-api-adaptor/versions.yaml
src/csi-wrapper/go.mod
src/peerpod-ctrl/go.mod

Bumps as bump of the 0.14.0 release

0.14.0 release

---

src/cloud-api-adaptor/pkg/adaptor/k8sops/node.go

This PR reads username/password in docker pull secrets and initializes auth param if missing.
Fixes: https://github.com/confidential-containers/cloud-api-adaptor/issues/2455

caa: allow docker image pull secrets with username/password only

---

.github/workflows/azure-e2e-test.yml
.github/workflows/azure-nightly-build.yml
.github/workflows/azure-podvm-image-build.yml
.github/workflows/build-golang-fedora.yaml
.github/workflows/caa_build_and_push.yaml
.github/workflows/caa_build_and_push_per_arch.yaml
.github/workflows/csi_wrapper_images.yaml
.github/workflows/daily-e2e-tests-libvirt.yaml
.github/workflows/e2e_aws.yaml
.github/workflows/e2e_docker.yaml
.github/workflows/e2e_libvirt.yaml
.github/workflows/e2e_on_pull.yaml
.github/workflows/e2e_run_all.yaml
.github/workflows/peerpod-ctrl_image.yaml
.github/workflows/podvm.yaml
.github/workflows/podvm_binaries.yaml
.github/workflows/podvm_builder.yaml
.github/workflows/podvm_mkosi.yaml
.github/workflows/podvm_publish.yaml
.github/workflows/publish_images_on_push.yaml
.github/workflows/release.yaml
.github/workflows/test-images.yaml
.github/workflows/webhook_image.yaml

Having secrets unconditionally being inherited is
bad practice, so update the workflows to only pass through the minimal secrets that are needed.
As part of this also shuffle some things that were secrets to variables to clean up the workflows

workflows: Remove inherit secrets

---

README.md

Steve's efforts produces good grades, we should show them :)

Readme: add openssf badge

---

src/cloud-api-adaptor/go.mod
src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
src/csi-wrapper/go.mod
src/peerpod-ctrl/go.mod

0.15.0 release

---

.github/workflows/scorecard.yaml

Add a workflow to update our scorecard score on
each change that's merged

workflows: Add scorecard workflow

---

hack/release-helper.sh
src/cloud-api-adaptor/go.mod
src/cloud-api-adaptor/install/overlays/aws/kustomization.yaml
src/cloud-api-adaptor/install/overlays/azure/kustomization.yaml
src/cloud-api-adaptor/install/overlays/docker/kustomization.yaml
src/cloud-api-adaptor/install/overlays/gcp/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud-powervs/kustomization.yaml
src/cloud-api-adaptor/install/overlays/ibmcloud/kustomization.yaml
src/cloud-api-adaptor/install/overlays/libvirt/kustomization.yaml
src/cloud-api-adaptor/install/overlays/vsphere/kustomization.yaml
src/csi-wrapper/go.mod
src/peerpod-ctrl/go.mod

Image tag and go mod version updates ready for the 0.16.0 release

release: 0.16.0 release pins & bumps
